package wechatdoc

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestAuditComplaintAlignment_CoversQueryHistoryAndWebhook(t *testing.T) {
	extraction := &Extraction{
		Sections: []Section{
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "查询投诉单列表", "接口说明"},
				Endpoints: []Endpoint{{Method: "GET", Path: "/v3/merchant-service/complaints-v2"}},
			},
			{
				Heading: "请求参数",
				Path:    []string{"消费者投诉 2.0", "查询投诉单列表", "请求参数"},
				Fields: []Field{
					{Name: "limit"},
					{Name: "offset"},
					{Name: "begin_date", Description: "投诉发生的开始日期，格式YYYY-MM-DD"},
					{Name: "end_date", Description: "投诉发生的结束日期，格式YYYY-MM-DD"},
					{Name: "complainted_mchid"},
				},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "查询投诉单列表", "应答参数"},
				Fields: []Field{
					{Name: "data.complaint_id"},
					{Name: "data.complaint_time", Description: "投诉时间，遵循RFC3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "data.complaint_detail"},
					{Name: "data.complaint_state", EnumValues: []string{"PENDING", "PROCESSING", "PROCESSED"}},
					{Name: "data.complainted_mchid"},
					{Name: "data.payer_phone"},
					{Name: "data.complaint_order_info.transaction_id"},
					{Name: "data.complaint_order_info.out_trade_no"},
					{Name: "data.complaint_order_info.amount", Description: "订单金额，单位（分）"},
					{Name: "data.complaint_full_refunded"},
					{Name: "data.incoming_user_response"},
					{Name: "data.user_complaint_times"},
					{Name: "data.complaint_media_list.media_type", EnumValues: []string{"USER_COMPLAINT_IMAGE", "OPERATION_IMAGE"}},
					{Name: "data.complaint_media_list.media_url"},
					{Name: "data.problem_description"},
					{Name: "data.problem_type", EnumValues: []string{"REFUND", "SERVICE_NOT_WORK", "OTHERS"}},
					{Name: "data.apply_refund_amount", Description: "仅当问题类型为申请退款时有值，单位:分"},
					{Name: "data.user_tag_list", EnumValues: []string{"TRUSTED", "HIGH_RISK"}},
					{Name: "data.service_order_info.order_id"},
					{Name: "data.service_order_info.out_order_no"},
					{Name: "data.service_order_info.state", EnumValues: []string{"DOING", "REVOKED", "WAITPAY", "DONE"}},
					{Name: "data.additional_info.type", EnumValues: []string{"SHARE_POWER_TYPE"}},
					{Name: "data.additional_info.share_power_info.return_time", Description: "遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "data.additional_info.share_power_info.return_address_info.return_address"},
					{Name: "data.additional_info.share_power_info.return_address_info.longitude"},
					{Name: "data.additional_info.share_power_info.return_address_info.latitude"},
					{Name: "data.additional_info.share_power_info.is_returned_to_same_machine"},
					{Name: "data.in_platform_service"},
					{Name: "data.need_immediate_service"},
					{Name: "data.is_agent_mode"},
					{Name: "limit"},
					{Name: "offset"},
					{Name: "total_count"},
				},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "查询投诉单列表", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "查询投诉单详情", "接口说明"},
				Endpoints: []Endpoint{{Method: "GET", Path: "/v3/merchant-service/complaints-v2/{complaint_id}"}},
			},
			{
				Heading: "请求参数",
				Path:    []string{"消费者投诉 2.0", "查询投诉单详情", "请求参数"},
				Fields:  []Field{{Name: "complaint_id"}},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "查询投诉单详情", "应答参数"},
				Fields: []Field{
					{Name: "complaint_id"},
					{Name: "complaint_time", Description: "投诉时间，遵循RFC3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "complaint_detail"},
					{Name: "complaint_state", EnumValues: []string{"PENDING", "PROCESSING", "PROCESSED"}},
					{Name: "complainted_mchid"},
					{Name: "payer_phone"},
					{Name: "payer_openid"},
					{Name: "complaint_order_info.transaction_id"},
					{Name: "complaint_order_info.out_trade_no"},
					{Name: "complaint_order_info.amount", Description: "订单金额，单位（分）"},
					{Name: "complaint_full_refunded"},
					{Name: "incoming_user_response"},
					{Name: "user_complaint_times"},
					{Name: "complaint_media_list.media_type", EnumValues: []string{"USER_COMPLAINT_IMAGE", "OPERATION_IMAGE"}},
					{Name: "complaint_media_list.media_url"},
					{Name: "problem_description"},
					{Name: "problem_type", EnumValues: []string{"REFUND", "SERVICE_NOT_WORK", "OTHERS"}},
					{Name: "apply_refund_amount", Description: "仅当问题类型为申请退款时有值，单位:分"},
					{Name: "user_tag_list", EnumValues: []string{"TRUSTED", "HIGH_RISK"}},
					{Name: "service_order_info.order_id"},
					{Name: "service_order_info.out_order_no"},
					{Name: "service_order_info.state", EnumValues: []string{"DOING", "REVOKED", "WAITPAY", "DONE"}},
					{Name: "additional_info.type", EnumValues: []string{"SHARE_POWER_TYPE"}},
					{Name: "additional_info.share_power_info.return_time", Description: "遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "additional_info.share_power_info.return_address_info.return_address"},
					{Name: "additional_info.share_power_info.return_address_info.longitude"},
					{Name: "additional_info.share_power_info.return_address_info.latitude"},
					{Name: "additional_info.share_power_info.is_returned_to_same_machine"},
					{Name: "in_platform_service"},
					{Name: "need_immediate_service"},
					{Name: "is_agent_mode"},
				},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "查询投诉单详情", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "查询投诉单协商历史", "接口说明"},
				Endpoints: []Endpoint{{Method: "GET", Path: "/v3/merchant-service/complaints-v2/{complaint_id}/negotiation-historys"}},
			},
			{
				Heading: "请求参数",
				Path:    []string{"消费者投诉 2.0", "查询投诉单协商历史", "请求参数"},
				Fields: []Field{
					{Name: "complaint_id"},
					{Name: "limit"},
					{Name: "offset"},
				},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "查询投诉单协商历史", "应答参数"},
				Fields: []Field{
					{Name: "data.log_id"},
					{Name: "data.operator"},
					{Name: "data.operate_time", Description: "操作时间，遵循RFC3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "data.operate_type", EnumValues: []string{"USER_CREATE_COMPLAINT", "USER_CONTINUE_COMPLAINT", "USER_RESPONSE", "PLATFORM_RESPONSE", "MERCHANT_RESPONSE", "MERCHANT_CONFIRM_COMPLETE", "USER_CREATE_COMPLAINT_SYSTEM_MESSAGE", "COMPLAINT_FULL_REFUNDED_SYSTEM_MESSAGE", "USER_CONTINUE_COMPLAINT_SYSTEM_MESSAGE", "USER_REVOKE_COMPLAINT", "USER_COMFIRM_COMPLAINT", "PLATFORM_HELP_APPLICATION", "USER_APPLY_PLATFORM_HELP", "MERCHANT_APPROVE_REFUND", "MERCHANT_REFUSE_RERUND", "USER_SUBMIT_SATISFACTION", "SERVICE_ORDER_CANCEL", "SERVICE_ORDER_COMPLETE", "COMPLAINT_PARTIAL_REFUNDED_SYSTEM_MESSAGE", "COMPLAINT_REFUND_RECEIVED_SYSTEM_MESSAGE", "COMPLAINT_ENTRUSTED_REFUND_SYSTEM_MESSAGE", "USER_APPLY_PLATFORM_SERVICE", "USER_CANCEL_PLATFORM_SERVICE", "PLATFORM_SERVICE_FINISHED", "USER_CLICK_RESPONSE"}},
					{Name: "data.operate_details"},
					{Name: "data.image_list"},
					{Name: "data.complaint_media_list.media_type", EnumValues: []string{"USER_COMPLAINT_IMAGE", "OPERATION_IMAGE"}},
					{Name: "data.complaint_media_list.media_url"},
					{Name: "data.user_appy_platform_service_reason"},
					{Name: "data.user_appy_platform_service_reason_description"},
					{Name: "data.normal_message.blocks.type", EnumValues: []string{"TEXT", "IMAGE", "LINK", "FAQ_LIST", "BUTTON", "BUTTON_GROUP"}},
					{Name: "data.normal_message.blocks.text.text"},
					{Name: "data.normal_message.blocks.text.color", EnumValues: []string{"DEFAULT", "SECONDARY"}},
					{Name: "data.normal_message.blocks.text.is_bold"},
					{Name: "data.normal_message.blocks.image.media_id"},
					{Name: "data.normal_message.blocks.image.image_style_type", EnumValues: []string{"IMAGE_STYLE_TYPE_NARROW", "IMAGE_STYLE_TYPE_WIDE"}},
					{Name: "data.normal_message.blocks.link.text"},
					{Name: "data.normal_message.blocks.link.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "data.normal_message.blocks.link.action.jump_url"},
					{Name: "data.normal_message.blocks.link.action.mini_program_jump_info.appid"},
					{Name: "data.normal_message.blocks.link.action.mini_program_jump_info.path"},
					{Name: "data.normal_message.blocks.link.action.message_info.content"},
					{Name: "data.normal_message.blocks.link.action.message_info.custom_data"},
					{Name: "data.normal_message.blocks.link.action.action_id"},
					{Name: "data.normal_message.blocks.link.invalid_info.expired_time", Description: "过期时间，遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "data.normal_message.blocks.link.invalid_info.multi_clickable"},
					{Name: "data.normal_message.blocks.faq_list.faqs.faq_id"},
					{Name: "data.normal_message.blocks.faq_list.faqs.faq_title"},
					{Name: "data.normal_message.blocks.faq_list.faqs.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "data.normal_message.blocks.button.text"},
					{Name: "data.normal_message.blocks.button.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "data.normal_message.blocks.button.invalid_info.expired_time", Description: "过期时间，遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "data.normal_message.blocks.button.invalid_info.multi_clickable"},
					{Name: "data.normal_message.blocks.button_group.buttons.text"},
					{Name: "data.normal_message.blocks.button_group.buttons.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "data.normal_message.blocks.button_group.button_layout", EnumValues: []string{"LAYOUT_UNKNOWN", "LAYOUT_HORIZONTAL", "LAYOUT_VERTICAL"}},
					{Name: "data.normal_message.blocks.button_group.invalid_info.expired_time", Description: "过期时间，遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "data.normal_message.blocks.button_group.invalid_info.multi_clickable"},
					{Name: "data.normal_message.sender_identity", EnumValues: []string{"UNKNOWN", "MANUAL", "MACHINE"}},
					{Name: "data.normal_message.custom_data"},
					{Name: "data.click_message.message_content"},
					{Name: "data.click_message.action_id"},
					{Name: "data.click_message.clicked_log_id"},
					{Name: "limit"},
					{Name: "offset"},
					{Name: "total_count"},
				},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "查询投诉单协商历史", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "投诉通知回调", "接口说明"},
				Endpoints: []Endpoint{{Method: "POST", Path: "/v1/webhooks/wechat-ecommerce/complaint-notify"}},
			},
			{
				Heading: "Body 参数",
				Path:    []string{"消费者投诉 2.0", "投诉通知回调", "Body 参数"},
				Fields: []Field{
					{Name: "complaint_id"},
					{Name: "action_type", EnumValues: []string{"CREATE_COMPLAINT", "CONTINUE_COMPLAINT", "USER_RESPONSE", "RESPONSE_BY_PLATFORM", "SELLER_REFUND", "MERCHANT_RESPONSE", "MERCHANT_CONFIRM_COMPLETE", "USER_APPLY_PLATFORM_SERVICE", "USER_CANCEL_PLATFORM_SERVICE", "PLATFORM_SERVICE_FINISHED", "MERCHANT_APPROVE_REFUND", "MERCHANT_REJECT_REFUND", "REFUND_SUCCESS"}},
				},
			},
		},
	}

	report := AuditComplaintAlignment(extraction)
	require.Equal(t, "complaint", report.Scope)
	require.Equal(t, 4, report.Summary.DocumentedEndpointCount)
	require.Equal(t, 4, report.Summary.AuditedEndpointCount)
	require.Empty(t, report.Endpoints)
}

func TestAuditComplaintAlignment_CoversConfigHandlingAndImages(t *testing.T) {
	extraction := &Extraction{
		Sections: []Section{
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "创建投诉通知回调地址", "接口说明"},
				Endpoints: []Endpoint{{Method: "POST", Path: "/v3/merchant-service/complaint-notifications"}},
			},
			{
				Heading: "Body 参数",
				Path:    []string{"消费者投诉 2.0", "创建投诉通知回调地址", "Body 参数"},
				Fields:  []Field{{Name: "url"}},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "创建投诉通知回调地址", "应答参数"},
				Fields:  []Field{{Name: "mchid"}, {Name: "url"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "创建投诉通知回调地址", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "查询投诉通知回调地址", "接口说明"},
				Endpoints: []Endpoint{{Method: "GET", Path: "/v3/merchant-service/complaint-notifications"}},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "查询投诉通知回调地址", "应答参数"},
				Fields:  []Field{{Name: "mchid"}, {Name: "url"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "查询投诉通知回调地址", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "更新投诉通知回调地址", "接口说明"},
				Endpoints: []Endpoint{{Method: "PUT", Path: "/v3/merchant-service/complaint-notifications"}},
			},
			{
				Heading: "Body 参数",
				Path:    []string{"消费者投诉 2.0", "更新投诉通知回调地址", "Body 参数"},
				Fields:  []Field{{Name: "url"}},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "更新投诉通知回调地址", "应答参数"},
				Fields:  []Field{{Name: "mchid"}, {Name: "url"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "更新投诉通知回调地址", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "删除投诉通知回调地址", "接口说明"},
				Endpoints: []Endpoint{{Method: "DELETE", Path: "/v3/merchant-service/complaint-notifications"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "删除投诉通知回调地址", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "回复用户", "接口说明"},
				Endpoints: []Endpoint{{Method: "POST", Path: "/v3/merchant-service/complaints-v2/{complaint_id}/response"}},
			},
			{
				Heading: "Body 参数",
				Path:    []string{"消费者投诉 2.0", "回复用户", "Body 参数"},
				Fields: []Field{
					{Name: "complaint_id"},
					{Name: "complainted_mchid"},
					{Name: "response_content"},
					{Name: "response_images"},
					{Name: "jump_url"},
					{Name: "jump_url_text"},
					{Name: "mini_program_jump_info.appid"},
					{Name: "mini_program_jump_info.path"},
					{Name: "mini_program_jump_info.text"},
				},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "回复用户", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "反馈处理完成", "接口说明"},
				Endpoints: []Endpoint{{Method: "POST", Path: "/v3/merchant-service/complaints-v2/{complaint_id}/complete"}},
			},
			{
				Heading: "Body 参数",
				Path:    []string{"消费者投诉 2.0", "反馈处理完成", "Body 参数"},
				Fields:  []Field{{Name: "complaint_id"}, {Name: "complainted_mchid"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "反馈处理完成", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "更新退款审批结果", "接口说明"},
				Endpoints: []Endpoint{{Method: "POST", Path: "/v3/merchant-service/complaints-v2/{complaint_id}/update-refund-progress"}},
			},
			{
				Heading: "Body 参数",
				Path:    []string{"消费者投诉 2.0", "更新退款审批结果", "Body 参数"},
				Fields: []Field{
					{Name: "complaint_id"},
					{Name: "action", EnumValues: []string{"REJECT", "APPROVE"}},
					{Name: "launch_refund_day"},
					{Name: "reject_reason"},
					{Name: "reject_media_list"},
					{Name: "remark"},
				},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "更新退款审批结果", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "回复需要即时服务的投诉单", "接口说明"},
				Endpoints: []Endpoint{{Method: "POST", Path: "/v3/merchant-service/complaints-v2/{complaint_id}/response-immediate-service"}},
			},
			{
				Heading: "Body 参数",
				Path:    []string{"消费者投诉 2.0", "回复需要即时服务的投诉单", "Body 参数"},
				Fields: []Field{
					{Name: "complaint_id"},
					{Name: "complainted_mchid"},
					{Name: "message.blocks.type", EnumValues: []string{"TEXT", "IMAGE", "LINK", "FAQ_LIST", "BUTTON", "BUTTON_GROUP"}},
					{Name: "message.blocks.text.text"},
					{Name: "message.blocks.text.color", EnumValues: []string{"DEFAULT", "SECONDARY"}},
					{Name: "message.blocks.text.is_bold"},
					{Name: "message.blocks.image.media_id"},
					{Name: "message.blocks.image.image_style_type", EnumValues: []string{"IMAGE_STYLE_TYPE_NARROW", "IMAGE_STYLE_TYPE_WIDE"}},
					{Name: "message.blocks.link.text"},
					{Name: "message.blocks.link.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "message.blocks.link.action.jump_url"},
					{Name: "message.blocks.link.action.mini_program_jump_info.appid"},
					{Name: "message.blocks.link.action.mini_program_jump_info.path"},
					{Name: "message.blocks.link.action.message_info.content"},
					{Name: "message.blocks.link.action.message_info.custom_data"},
					{Name: "message.blocks.link.action.action_id"},
					{Name: "message.blocks.link.invalid_info.expired_time", Description: "过期时间，遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "message.blocks.link.invalid_info.multi_clickable"},
					{Name: "message.blocks.faq_list.faqs.faq_id"},
					{Name: "message.blocks.faq_list.faqs.faq_title"},
					{Name: "message.blocks.faq_list.faqs.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "message.blocks.button.text"},
					{Name: "message.blocks.button.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "message.blocks.button.invalid_info.expired_time", Description: "过期时间，遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "message.blocks.button.invalid_info.multi_clickable"},
					{Name: "message.blocks.button_group.buttons.text"},
					{Name: "message.blocks.button_group.buttons.action.action_type", EnumValues: []string{"ACTION_TYPE_SEND_MESSAGE", "ACTION_TYPE_JUMP_URL", "ACTION_TYPE_JUMP_MINI_PROGRAM"}},
					{Name: "message.blocks.button_group.button_layout", EnumValues: []string{"LAYOUT_UNKNOWN", "LAYOUT_HORIZONTAL", "LAYOUT_VERTICAL"}},
					{Name: "message.blocks.button_group.invalid_info.expired_time", Description: "过期时间，遵循rfc3339标准格式，格式为yyyy-MM-DDTHH:mm:ss+TIMEZONE"},
					{Name: "message.blocks.button_group.invalid_info.multi_clickable"},
					{Name: "message.sender_identity", EnumValues: []string{"UNKNOWN", "MANUAL", "MACHINE"}},
					{Name: "message.custom_data"},
					{Name: "idempotent_id"},
				},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "回复需要即时服务的投诉单", "应答参数"},
				Fields:  []Field{{Name: "log_id"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "回复需要即时服务的投诉单", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "图片上传接口", "接口说明"},
				Endpoints: []Endpoint{{Method: "POST", Path: "/v3/merchant-service/images/upload"}},
			},
			{
				Heading: "Form 参数",
				Path:    []string{"消费者投诉 2.0", "图片上传接口", "Form 参数"},
				Fields: []Field{
					{Name: "file"},
					{Name: "meta.filename"},
					{Name: "meta.sha256"},
				},
			},
			{
				Heading: "应答参数",
				Path:    []string{"消费者投诉 2.0", "图片上传接口", "应答参数"},
				Fields:  []Field{{Name: "media_id"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "图片上传接口", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
			{
				Heading:   "接口说明",
				Path:      []string{"消费者投诉 2.0", "图片请求接口", "接口说明"},
				Endpoints: []Endpoint{{Method: "GET", Path: "/v3/merchant-service/images/{media_id}"}},
			},
			{
				Heading: "请求参数",
				Path:    []string{"消费者投诉 2.0", "图片请求接口", "请求参数"},
				Fields:  []Field{{Name: "media_id"}},
			},
			{
				Heading:    "错误码",
				Path:       []string{"消费者投诉 2.0", "图片请求接口", "错误码"},
				ErrorCodes: []ErrorCode{{Code: "PARAM_ERROR"}, {Code: "INVALID_REQUEST"}, {Code: "SIGN_ERROR"}, {Code: "SYSTEM_ERROR"}},
			},
		},
	}

	report := AuditComplaintAlignment(extraction)
	require.Equal(t, 10, report.Summary.DocumentedEndpointCount)
	require.Equal(t, 10, report.Summary.AuditedEndpointCount)
	require.Empty(t, report.Endpoints)
}
