// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: abnormal_stats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAbnormalStatsSummary = `-- name: GetAbnormalStatsSummary :one

SELECT
    COALESCE(SUM(total_orders), 0)::INT AS total_orders,
    COALESCE(SUM(abnormal_claims), 0)::INT AS abnormal_claims
FROM abnormal_stats_daily
WHERE entity_type = $1
  AND entity_id = $2
  AND stat_date >= $3
  AND stat_date <= $4
`

type GetAbnormalStatsSummaryParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   int64       `json:"entity_id"`
	StatDate   pgtype.Date `json:"stat_date"`
	StatDate_2 pgtype.Date `json:"stat_date_2"`
}

type GetAbnormalStatsSummaryRow struct {
	TotalOrders    int32 `json:"total_orders"`
	AbnormalClaims int32 `json:"abnormal_claims"`
}

// Phase3: abnormal stats aggregation queries
func (q *Queries) GetAbnormalStatsSummary(ctx context.Context, arg GetAbnormalStatsSummaryParams) (GetAbnormalStatsSummaryRow, error) {
	row := q.db.QueryRow(ctx, getAbnormalStatsSummary,
		arg.EntityType,
		arg.EntityID,
		arg.StatDate,
		arg.StatDate_2,
	)
	var i GetAbnormalStatsSummaryRow
	err := row.Scan(&i.TotalOrders, &i.AbnormalClaims)
	return i, err
}

const listAbnormalStatsDaily = `-- name: ListAbnormalStatsDaily :many
SELECT id, stat_date, entity_type, entity_id, total_orders, abnormal_claims, created_at, updated_at FROM abnormal_stats_daily
WHERE entity_type = $1
  AND entity_id = $2
  AND stat_date >= $3
  AND stat_date <= $4
ORDER BY stat_date ASC
`

type ListAbnormalStatsDailyParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   int64       `json:"entity_id"`
	StatDate   pgtype.Date `json:"stat_date"`
	StatDate_2 pgtype.Date `json:"stat_date_2"`
}

func (q *Queries) ListAbnormalStatsDaily(ctx context.Context, arg ListAbnormalStatsDailyParams) ([]AbnormalStatsDaily, error) {
	rows, err := q.db.Query(ctx, listAbnormalStatsDaily,
		arg.EntityType,
		arg.EntityID,
		arg.StatDate,
		arg.StatDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AbnormalStatsDaily{}
	for rows.Next() {
		var i AbnormalStatsDaily
		if err := rows.Scan(
			&i.ID,
			&i.StatDate,
			&i.EntityType,
			&i.EntityID,
			&i.TotalOrders,
			&i.AbnormalClaims,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
