// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agreement.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveAgreementByType = `-- name: GetActiveAgreementByType :one
SELECT id, type, title, content, version, published_on, is_active, created_at, updated_at FROM agreements
WHERE type = $1 AND is_active = true
ORDER BY published_on DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetActiveAgreementByType(ctx context.Context, type_ string) (Agreement, error) {
	row := q.db.QueryRow(ctx, getActiveAgreementByType, type_)
	var i Agreement
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.PublishedOn,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveAgreements = `-- name: ListActiveAgreements :many
SELECT type, title, version, published_on 
FROM agreements
WHERE is_active = true
ORDER BY type ASC
`

type ListActiveAgreementsRow struct {
	Type        string      `json:"type"`
	Title       string      `json:"title"`
	Version     string      `json:"version"`
	PublishedOn pgtype.Date `json:"published_on"`
}

func (q *Queries) ListActiveAgreements(ctx context.Context) ([]ListActiveAgreementsRow, error) {
	rows, err := q.db.Query(ctx, listActiveAgreements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAgreementsRow{}
	for rows.Next() {
		var i ListActiveAgreementsRow
		if err := rows.Scan(
			&i.Type,
			&i.Title,
			&i.Version,
			&i.PublishedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
