// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: behavior_trace.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserOrders = `-- name: CountUserOrders :one

SELECT COUNT(*)::INT AS total_orders
FROM orders
WHERE user_id = $1
`

// ==============================
// behavior_trace_snapshots
// ==============================
func (q *Queries) CountUserOrders(ctx context.Context, userID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countUserOrders, userID)
	var total_orders int32
	err := row.Scan(&total_orders)
	return total_orders, err
}

const createBehaviorAction = `-- name: CreateBehaviorAction :one

INSERT INTO behavior_actions (
    decision_id,
    action_type,
    target_entity,
    status,
    detail
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, decision_id, action_type, target_entity, status, detail, executed_at, created_at
`

type CreateBehaviorActionParams struct {
	DecisionID   int64  `json:"decision_id"`
	ActionType   string `json:"action_type"`
	TargetEntity string `json:"target_entity"`
	Status       string `json:"status"`
	Detail       []byte `json:"detail"`
}

// ==============================
// behavior_actions
// ==============================
func (q *Queries) CreateBehaviorAction(ctx context.Context, arg CreateBehaviorActionParams) (BehaviorAction, error) {
	row := q.db.QueryRow(ctx, createBehaviorAction,
		arg.DecisionID,
		arg.ActionType,
		arg.TargetEntity,
		arg.Status,
		arg.Detail,
	)
	var i BehaviorAction
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.ActionType,
		&i.TargetEntity,
		&i.Status,
		&i.Detail,
		&i.ExecutedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createBehaviorAppeal = `-- name: CreateBehaviorAppeal :one

INSERT INTO behavior_appeals (
    entity_type,
    entity_id,
    decision_id,
    reason,
    evidence,
    status,
    reeval_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, entity_type, entity_id, decision_id, reason, evidence, status, created_at, reeval_at
`

type CreateBehaviorAppealParams struct {
	EntityType string             `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	DecisionID pgtype.Int8        `json:"decision_id"`
	Reason     string             `json:"reason"`
	Evidence   pgtype.Text        `json:"evidence"`
	Status     string             `json:"status"`
	ReevalAt   pgtype.Timestamptz `json:"reeval_at"`
}

// ==============================
// behavior_appeals
// ==============================
func (q *Queries) CreateBehaviorAppeal(ctx context.Context, arg CreateBehaviorAppealParams) (BehaviorAppeal, error) {
	row := q.db.QueryRow(ctx, createBehaviorAppeal,
		arg.EntityType,
		arg.EntityID,
		arg.DecisionID,
		arg.Reason,
		arg.Evidence,
		arg.Status,
		arg.ReevalAt,
	)
	var i BehaviorAppeal
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.DecisionID,
		&i.Reason,
		&i.Evidence,
		&i.Status,
		&i.CreatedAt,
		&i.ReevalAt,
	)
	return i, err
}

const createBehaviorBlocklist = `-- name: CreateBehaviorBlocklist :one

INSERT INTO behavior_blocklist (
    entity_type,
    entity_id,
    reason_code,
    block_until,
    status
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, entity_type, entity_id, reason_code, block_until, status, created_at, updated_at
`

type CreateBehaviorBlocklistParams struct {
	EntityType string             `json:"entity_type"`
	EntityID   int64              `json:"entity_id"`
	ReasonCode string             `json:"reason_code"`
	BlockUntil pgtype.Timestamptz `json:"block_until"`
	Status     string             `json:"status"`
}

// ==============================
// behavior_blocklist
// ==============================
func (q *Queries) CreateBehaviorBlocklist(ctx context.Context, arg CreateBehaviorBlocklistParams) (BehaviorBlocklist, error) {
	row := q.db.QueryRow(ctx, createBehaviorBlocklist,
		arg.EntityType,
		arg.EntityID,
		arg.ReasonCode,
		arg.BlockUntil,
		arg.Status,
	)
	var i BehaviorBlocklist
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.ReasonCode,
		&i.BlockUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBehaviorDecision = `-- name: CreateBehaviorDecision :one

INSERT INTO behavior_decisions (
    order_id,
    user_id,
    merchant_id,
    rider_id,
    decision_version,
    reason_codes,
    responsible_party,
    compensation_source,
    decision_status,
    trace_summary
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, order_id, user_id, merchant_id, rider_id, decision_version, reason_codes, responsible_party, compensation_source, decision_status, trace_summary, created_at, updated_at
`

type CreateBehaviorDecisionParams struct {
	OrderID            int64       `json:"order_id"`
	UserID             pgtype.Int8 `json:"user_id"`
	MerchantID         pgtype.Int8 `json:"merchant_id"`
	RiderID            pgtype.Int8 `json:"rider_id"`
	DecisionVersion    string      `json:"decision_version"`
	ReasonCodes        []string    `json:"reason_codes"`
	ResponsibleParty   string      `json:"responsible_party"`
	CompensationSource string      `json:"compensation_source"`
	DecisionStatus     string      `json:"decision_status"`
	TraceSummary       pgtype.Text `json:"trace_summary"`
}

// ==============================
// behavior_decisions
// ==============================
func (q *Queries) CreateBehaviorDecision(ctx context.Context, arg CreateBehaviorDecisionParams) (BehaviorDecision, error) {
	row := q.db.QueryRow(ctx, createBehaviorDecision,
		arg.OrderID,
		arg.UserID,
		arg.MerchantID,
		arg.RiderID,
		arg.DecisionVersion,
		arg.ReasonCodes,
		arg.ResponsibleParty,
		arg.CompensationSource,
		arg.DecisionStatus,
		arg.TraceSummary,
	)
	var i BehaviorDecision
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.RiderID,
		&i.DecisionVersion,
		&i.ReasonCodes,
		&i.ResponsibleParty,
		&i.CompensationSource,
		&i.DecisionStatus,
		&i.TraceSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBehaviorEvidence = `-- name: CreateBehaviorEvidence :one

INSERT INTO behavior_evidence (
    decision_id,
    evidence_type,
    payload
) VALUES (
    $1, $2, $3
) RETURNING id, decision_id, evidence_type, payload, created_at
`

type CreateBehaviorEvidenceParams struct {
	DecisionID   int64  `json:"decision_id"`
	EvidenceType string `json:"evidence_type"`
	Payload      []byte `json:"payload"`
}

// ==============================
// behavior_evidence
// ==============================
func (q *Queries) CreateBehaviorEvidence(ctx context.Context, arg CreateBehaviorEvidenceParams) (BehaviorEvidence, error) {
	row := q.db.QueryRow(ctx, createBehaviorEvidence, arg.DecisionID, arg.EvidenceType, arg.Payload)
	var i BehaviorEvidence
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.EvidenceType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const createBehaviorTraceSnapshot = `-- name: CreateBehaviorTraceSnapshot :one
INSERT INTO behavior_trace_snapshots (
    decision_id,
    window_days,
    abnormal_count,
    total_count,
    abnormal_rate,
    association_hits
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, decision_id, window_days, abnormal_count, total_count, abnormal_rate, association_hits, created_at
`

type CreateBehaviorTraceSnapshotParams struct {
	DecisionID      int64          `json:"decision_id"`
	WindowDays      int32          `json:"window_days"`
	AbnormalCount   int32          `json:"abnormal_count"`
	TotalCount      int32          `json:"total_count"`
	AbnormalRate    pgtype.Numeric `json:"abnormal_rate"`
	AssociationHits []string       `json:"association_hits"`
}

func (q *Queries) CreateBehaviorTraceSnapshot(ctx context.Context, arg CreateBehaviorTraceSnapshotParams) (BehaviorTraceSnapshot, error) {
	row := q.db.QueryRow(ctx, createBehaviorTraceSnapshot,
		arg.DecisionID,
		arg.WindowDays,
		arg.AbnormalCount,
		arg.TotalCount,
		arg.AbnormalRate,
		arg.AssociationHits,
	)
	var i BehaviorTraceSnapshot
	err := row.Scan(
		&i.ID,
		&i.DecisionID,
		&i.WindowDays,
		&i.AbnormalCount,
		&i.TotalCount,
		&i.AbnormalRate,
		&i.AssociationHits,
		&i.CreatedAt,
	)
	return i, err
}

const createPlatformConfig = `-- name: CreatePlatformConfig :one


INSERT INTO platform_configs (
    config_key,
    config_value,
    scope_type,
    scope_id
) VALUES (
    $1, $2, $3, $4
) RETURNING id, config_key, config_value, scope_type, scope_id, created_at, updated_at
`

type CreatePlatformConfigParams struct {
	ConfigKey   string      `json:"config_key"`
	ConfigValue []byte      `json:"config_value"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     pgtype.Int8 `json:"scope_id"`
}

// Behavior trace system queries
// ==============================
// platform_configs
// ==============================
func (q *Queries) CreatePlatformConfig(ctx context.Context, arg CreatePlatformConfigParams) (PlatformConfig, error) {
	row := q.db.QueryRow(ctx, createPlatformConfig,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.ScopeType,
		arg.ScopeID,
	)
	var i PlatformConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveBehaviorBlocklist = `-- name: GetActiveBehaviorBlocklist :one
SELECT id, entity_type, entity_id, reason_code, block_until, status, created_at, updated_at FROM behavior_blocklist
WHERE entity_type = $1 AND entity_id = $2 AND status = 'active'
LIMIT 1
`

type GetActiveBehaviorBlocklistParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) GetActiveBehaviorBlocklist(ctx context.Context, arg GetActiveBehaviorBlocklistParams) (BehaviorBlocklist, error) {
	row := q.db.QueryRow(ctx, getActiveBehaviorBlocklist, arg.EntityType, arg.EntityID)
	var i BehaviorBlocklist
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.ReasonCode,
		&i.BlockUntil,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBehaviorDecision = `-- name: GetBehaviorDecision :one
SELECT id, order_id, user_id, merchant_id, rider_id, decision_version, reason_codes, responsible_party, compensation_source, decision_status, trace_summary, created_at, updated_at FROM behavior_decisions
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBehaviorDecision(ctx context.Context, id int64) (BehaviorDecision, error) {
	row := q.db.QueryRow(ctx, getBehaviorDecision, id)
	var i BehaviorDecision
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.RiderID,
		&i.DecisionVersion,
		&i.ReasonCodes,
		&i.ResponsibleParty,
		&i.CompensationSource,
		&i.DecisionStatus,
		&i.TraceSummary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformConfig = `-- name: GetPlatformConfig :one
SELECT id, config_key, config_value, scope_type, scope_id, created_at, updated_at FROM platform_configs
WHERE config_key = $1 AND scope_type = $2 AND scope_id IS NOT DISTINCT FROM $3
LIMIT 1
`

type GetPlatformConfigParams struct {
	ConfigKey string      `json:"config_key"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.Int8 `json:"scope_id"`
}

func (q *Queries) GetPlatformConfig(ctx context.Context, arg GetPlatformConfigParams) (PlatformConfig, error) {
	row := q.db.QueryRow(ctx, getPlatformConfig, arg.ConfigKey, arg.ScopeType, arg.ScopeID)
	var i PlatformConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserClaimWindowStats = `-- name: GetUserClaimWindowStats :one
SELECT 
    (SELECT COUNT(*) FROM orders o WHERE o.user_id = $1 AND o.order_type = 'takeout'
     AND o.created_at >= NOW() - INTERVAL '7 days')::INT as takeout_orders_7d,
    (SELECT COUNT(*) FROM claims c WHERE c.user_id = $1 
     AND c.created_at >= NOW() - INTERVAL '7 days')::INT as claims_7d,
    (SELECT COUNT(*) FROM orders o WHERE o.user_id = $1 AND o.order_type = 'takeout'
     AND o.created_at >= NOW() - INTERVAL '30 days')::INT as takeout_orders_30d,
    (SELECT COUNT(*) FROM claims c WHERE c.user_id = $1 
     AND c.created_at >= NOW() - INTERVAL '30 days')::INT as claims_30d
`

type GetUserClaimWindowStatsRow struct {
	TakeoutOrders7d  int32 `json:"takeout_orders_7d"`
	Claims7d         int32 `json:"claims_7d"`
	TakeoutOrders30d int32 `json:"takeout_orders_30d"`
	Claims30d        int32 `json:"claims_30d"`
}

func (q *Queries) GetUserClaimWindowStats(ctx context.Context, userID int64) (GetUserClaimWindowStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserClaimWindowStats, userID)
	var i GetUserClaimWindowStatsRow
	err := row.Scan(
		&i.TakeoutOrders7d,
		&i.Claims7d,
		&i.TakeoutOrders30d,
		&i.Claims30d,
	)
	return i, err
}

const listActiveBehaviorBlocklists = `-- name: ListActiveBehaviorBlocklists :many
SELECT id, entity_type, entity_id, reason_code, block_until, status, created_at, updated_at FROM behavior_blocklist
WHERE status = 'active'
ORDER BY created_at DESC
`

func (q *Queries) ListActiveBehaviorBlocklists(ctx context.Context) ([]BehaviorBlocklist, error) {
	rows, err := q.db.Query(ctx, listActiveBehaviorBlocklists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BehaviorBlocklist{}
	for rows.Next() {
		var i BehaviorBlocklist
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ReasonCode,
			&i.BlockUntil,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBehaviorActionsByDecision = `-- name: ListBehaviorActionsByDecision :many
SELECT id, decision_id, action_type, target_entity, status, detail, executed_at, created_at FROM behavior_actions
WHERE decision_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBehaviorActionsByDecision(ctx context.Context, decisionID int64) ([]BehaviorAction, error) {
	rows, err := q.db.Query(ctx, listBehaviorActionsByDecision, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BehaviorAction{}
	for rows.Next() {
		var i BehaviorAction
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.ActionType,
			&i.TargetEntity,
			&i.Status,
			&i.Detail,
			&i.ExecutedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBehaviorAppealsByEntity = `-- name: ListBehaviorAppealsByEntity :many
SELECT id, entity_type, entity_id, decision_id, reason, evidence, status, created_at, reeval_at FROM behavior_appeals
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
`

type ListBehaviorAppealsByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) ListBehaviorAppealsByEntity(ctx context.Context, arg ListBehaviorAppealsByEntityParams) ([]BehaviorAppeal, error) {
	rows, err := q.db.Query(ctx, listBehaviorAppealsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BehaviorAppeal{}
	for rows.Next() {
		var i BehaviorAppeal
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.DecisionID,
			&i.Reason,
			&i.Evidence,
			&i.Status,
			&i.CreatedAt,
			&i.ReevalAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBehaviorDecisionsByOrder = `-- name: ListBehaviorDecisionsByOrder :many
SELECT id, order_id, user_id, merchant_id, rider_id, decision_version, reason_codes, responsible_party, compensation_source, decision_status, trace_summary, created_at, updated_at FROM behavior_decisions
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBehaviorDecisionsByOrder(ctx context.Context, orderID int64) ([]BehaviorDecision, error) {
	rows, err := q.db.Query(ctx, listBehaviorDecisionsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BehaviorDecision{}
	for rows.Next() {
		var i BehaviorDecision
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.MerchantID,
			&i.RiderID,
			&i.DecisionVersion,
			&i.ReasonCodes,
			&i.ResponsibleParty,
			&i.CompensationSource,
			&i.DecisionStatus,
			&i.TraceSummary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBehaviorEvidenceByDecision = `-- name: ListBehaviorEvidenceByDecision :many
SELECT id, decision_id, evidence_type, payload, created_at FROM behavior_evidence
WHERE decision_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBehaviorEvidenceByDecision(ctx context.Context, decisionID int64) ([]BehaviorEvidence, error) {
	rows, err := q.db.Query(ctx, listBehaviorEvidenceByDecision, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BehaviorEvidence{}
	for rows.Next() {
		var i BehaviorEvidence
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.EvidenceType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBehaviorTraceSnapshotsByDecision = `-- name: ListBehaviorTraceSnapshotsByDecision :many
SELECT id, decision_id, window_days, abnormal_count, total_count, abnormal_rate, association_hits, created_at FROM behavior_trace_snapshots
WHERE decision_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListBehaviorTraceSnapshotsByDecision(ctx context.Context, decisionID int64) ([]BehaviorTraceSnapshot, error) {
	rows, err := q.db.Query(ctx, listBehaviorTraceSnapshotsByDecision, decisionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BehaviorTraceSnapshot{}
	for rows.Next() {
		var i BehaviorTraceSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.DecisionID,
			&i.WindowDays,
			&i.AbnormalCount,
			&i.TotalCount,
			&i.AbnormalRate,
			&i.AssociationHits,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformConfigsByKey = `-- name: ListPlatformConfigsByKey :many
SELECT id, config_key, config_value, scope_type, scope_id, created_at, updated_at FROM platform_configs
WHERE config_key = $1
ORDER BY scope_type, scope_id
`

func (q *Queries) ListPlatformConfigsByKey(ctx context.Context, configKey string) ([]PlatformConfig, error) {
	rows, err := q.db.Query(ctx, listPlatformConfigsByKey, configKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformConfig{}
	for rows.Next() {
		var i PlatformConfig
		if err := rows.Scan(
			&i.ID,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.ScopeType,
			&i.ScopeID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBehaviorActionStatus = `-- name: UpdateBehaviorActionStatus :exec
UPDATE behavior_actions
SET status = $2,
    executed_at = COALESCE($3, executed_at)
WHERE id = $1
`

type UpdateBehaviorActionStatusParams struct {
	ID         int64              `json:"id"`
	Status     string             `json:"status"`
	ExecutedAt pgtype.Timestamptz `json:"executed_at"`
}

func (q *Queries) UpdateBehaviorActionStatus(ctx context.Context, arg UpdateBehaviorActionStatusParams) error {
	_, err := q.db.Exec(ctx, updateBehaviorActionStatus, arg.ID, arg.Status, arg.ExecutedAt)
	return err
}

const updateBehaviorAppealStatus = `-- name: UpdateBehaviorAppealStatus :exec
UPDATE behavior_appeals
SET status = $2,
    reeval_at = COALESCE($3, reeval_at)
WHERE id = $1
`

type UpdateBehaviorAppealStatusParams struct {
	ID       int64              `json:"id"`
	Status   string             `json:"status"`
	ReevalAt pgtype.Timestamptz `json:"reeval_at"`
}

func (q *Queries) UpdateBehaviorAppealStatus(ctx context.Context, arg UpdateBehaviorAppealStatusParams) error {
	_, err := q.db.Exec(ctx, updateBehaviorAppealStatus, arg.ID, arg.Status, arg.ReevalAt)
	return err
}

const updateBehaviorBlocklistStatus = `-- name: UpdateBehaviorBlocklistStatus :exec
UPDATE behavior_blocklist
SET status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateBehaviorBlocklistStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateBehaviorBlocklistStatus(ctx context.Context, arg UpdateBehaviorBlocklistStatusParams) error {
	_, err := q.db.Exec(ctx, updateBehaviorBlocklistStatus, arg.ID, arg.Status)
	return err
}

const updateBehaviorDecisionStatus = `-- name: UpdateBehaviorDecisionStatus :exec
UPDATE behavior_decisions
SET decision_status = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateBehaviorDecisionStatusParams struct {
	ID             int64  `json:"id"`
	DecisionStatus string `json:"decision_status"`
}

func (q *Queries) UpdateBehaviorDecisionStatus(ctx context.Context, arg UpdateBehaviorDecisionStatusParams) error {
	_, err := q.db.Exec(ctx, updateBehaviorDecisionStatus, arg.ID, arg.DecisionStatus)
	return err
}

const upsertPlatformConfig = `-- name: UpsertPlatformConfig :one
INSERT INTO platform_configs (
    config_key,
    config_value,
    scope_type,
    scope_id
) VALUES (
    $1, $2, $3, $4
) ON CONFLICT (config_key, scope_type, scope_id) DO UPDATE
SET config_value = EXCLUDED.config_value,
    updated_at = NOW()
RETURNING id, config_key, config_value, scope_type, scope_id, created_at, updated_at
`

type UpsertPlatformConfigParams struct {
	ConfigKey   string      `json:"config_key"`
	ConfigValue []byte      `json:"config_value"`
	ScopeType   string      `json:"scope_type"`
	ScopeID     pgtype.Int8 `json:"scope_id"`
}

func (q *Queries) UpsertPlatformConfig(ctx context.Context, arg UpsertPlatformConfigParams) (PlatformConfig, error) {
	row := q.db.QueryRow(ctx, upsertPlatformConfig,
		arg.ConfigKey,
		arg.ConfigValue,
		arg.ScopeType,
		arg.ScopeID,
	)
	var i PlatformConfig
	err := row.Scan(
		&i.ID,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.ScopeType,
		&i.ScopeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
