package db

const (
	UserRoleAdmin         = "admin"
	UserRoleOperator      = "operator"
	UserRoleMerchantOwner = "merchant_owner"
	UserRoleMerchantStaff = "merchant_staff"
	UserRoleRider         = "rider"
	UserRoleCustomer      = "customer"

	MerchantStaffRoleOwner    = "owner"
	MerchantStaffStatusActive = "active"

	MerchantStatusActive            = "active"
	MerchantStatusBindbankSubmitted = "bindbank_submitted"

	MerchantPaymentConfigStatusActive               = "active"
	MerchantPaymentConfigStatusPendingAuthorization = "pending_authorization"

	AccountAuthorizeStateUnauthorized = "AUTHORIZE_STATE_UNAUTHORIZED"
	AccountAuthorizeStateAuthorized   = "AUTHORIZE_STATE_AUTHORIZED"

	MerchantAppDevicePlatformAndroid = "android"

	MerchantAppDeviceProviderHuawei  = "huawei"
	MerchantAppDeviceProviderHonor   = "honor"
	MerchantAppDeviceProviderXiaomi  = "xiaomi"
	MerchantAppDeviceProviderOppo    = "oppo"
	MerchantAppDeviceProviderVivo    = "vivo"
	MerchantAppDeviceProviderUnknown = "unknown"

	MerchantAppDeviceStatusActive   = "active"
	MerchantAppDeviceStatusInactive = "inactive"

	AppVersionPlatformAndroid = "android"
	AppVersionChannelMerchant = "merchant_app"

	AppVersionStatusDraft    = "draft"
	AppVersionStatusActive   = "active"
	AppVersionStatusDisabled = "disabled"

	// Order statuses (SSOT — 所有层引用此处)
	OrderStatusPending                  = "pending"
	OrderStatusPaid                     = "paid"
	OrderStatusPreparing                = "preparing"
	OrderStatusReady                    = "ready"
	OrderStatusCourierAccepted          = "courier_accepted"
	OrderStatusPicked                   = "picked"
	OrderStatusDelivering               = "delivering"
	OrderStatusRiderDelivered           = "rider_delivered"
	OrderStatusUserDelivered            = "user_delivered"
	OrderStatusCompleted                = "completed"
	OrderStatusCancelled                = "cancelled"
	OrderExceptionStateFoodSafetyPaused = "food_safety_paused"
	ClaimChannelFoodSafety              = "food_safety"

	ClaimStatusPending                     = "pending"
	ClaimStatusAutoApproved                = "auto-approved"
	ClaimStatusWaitingCustomerConfirmation = "waiting_customer_confirmation"
	ClaimStatusApproved                    = "approved"
	ClaimStatusRejected                    = "rejected"
	ClaimStatusWithdrawn                   = "withdrawn"

	OrderTypeTakeout     = "takeout"
	OrderTypeReservation = "reservation"

	BehaviorDecisionModeMerchantRecovery = "merchant_recovery"
	BehaviorDecisionModeRiderRecovery    = "rider_recovery"
	BehaviorDecisionModeUserRestricted   = "user_restricted"

	BehaviorResponsibilityDomainMerchant = "merchant_domain"
	BehaviorResponsibilityDomainRider    = "rider_domain"
	BehaviorResponsibilityDomainUser     = "user_domain"
	BehaviorResponsibilityDomainUnknown  = "unknown"

	BehaviorPayoutModeInstantPaid = "instant_paid"
	BehaviorPayoutModeLimitedPaid = "limited_paid"
	BehaviorPayoutModeRejected    = "rejected"

	BehaviorEffectiveStatusEffective = "effective"

	BehaviorDecisionEffectStatusApplied  = "applied"
	BehaviorDecisionEffectStatusReverted = "reverted"

	ClaimRecoveryEventTypeCreated        = "created"
	ClaimRecoveryEventTypePayable        = "payable"
	ClaimRecoveryEventTypePaymentStarted = "payment_started"
	ClaimRecoveryEventTypePaid           = "paid"
	ClaimRecoveryEventTypeOverdue        = "overdue"
	ClaimRecoveryEventTypeDisputed       = "disputed"
	ClaimRecoveryEventTypeWaived         = "waived"
	ClaimRecoveryEventTypeResumed        = "resumed"
	ClaimRecoveryEventTypeClosed         = "closed"
	ClaimRecoveryEventTypeOverturned     = "overturned"

	ClaimRecoveryBasisMerchantRecovery = "merchant_recovery"
	ClaimRecoveryBasisRiderRecovery    = "rider_recovery"

	BehaviorSnapshotWindowKey7d  = "7d"
	BehaviorSnapshotWindowKey30d = "30d"
	BehaviorSnapshotScopeRaw     = "raw"
	BehaviorSnapshotScopeNet     = "net_effective"
	BehaviorSnapshotVersionV2    = "v2"

	RiderStatusApproved  = "approved"
	RiderStatusActive    = "active"
	RiderStatusSuspended = "suspended"

	RiderApplicationStatusDraft     = "draft"
	RiderApplicationStatusSubmitted = "submitted"
	RiderApplicationStatusApproved  = "approved"

	PlatformConfigScopeGlobal        = "global"
	PlatformConfigKeyRiderDepositFen = "platform_rule.rider_deposit_fen"
	DefaultRiderDepositThresholdFen  = 20000

	FulfillmentStatusScheduled      = "scheduled"
	FulfillmentStatusPendingKitchen = "pending_kitchen"
	FulfillmentStatusPreparing      = "preparing"
	FulfillmentStatusReady          = "ready"
	FulfillmentStatusCompleted      = "completed"
	FulfillmentStatusCancelled      = "cancelled"

	CloudPrinterReconciliationActionRegister = "register"
	CloudPrinterReconciliationActionRemove   = "remove"

	CloudPrinterReconciliationSourceCreate = "create"
	CloudPrinterReconciliationSourceDelete = "delete"

	CloudPrinterReconciliationStatusPending  = "pending"
	CloudPrinterReconciliationStatusResolved = "resolved"

	MerchantCapabilityStatusUnknown = "unknown"
	MerchantCapabilityStatusYes     = "yes"
	MerchantCapabilityStatusNo      = "no"

	MerchantCancelWithdrawLocalSyncStateCreated         = "created"
	MerchantCancelWithdrawLocalSyncStateSubmitSucceeded = "submit_succeeded"
	MerchantCancelWithdrawLocalSyncStateSubmitUnknown   = "submit_unknown"
	MerchantCancelWithdrawLocalSyncStateSyncFailed      = "sync_failed"

	MerchantCancelWithdrawModeNoWithdraw = "NOT_APPLY_WITHDRAW"
	MerchantCancelWithdrawModeWithdraw   = "APPLY_WITHDRAW"

	MerchantCancelWithdrawBusinessLicenseStatusActive   = "ACTIVE"
	MerchantCancelWithdrawBusinessLicenseStatusCanceled = "CANCELED"
	MerchantCancelWithdrawBusinessLicenseStatusRevoked  = "REVOKED"

	MerchantCancelStateAccepted               = "ACCEPTED"
	MerchantCancelStateReviewing              = "REVIEWING"
	MerchantCancelStateRejected               = "REJECTED"
	MerchantCancelStateWaitingMerchantConfirm = "WAITING_MERCHANT_CONFIRM"
	MerchantCancelStateRevoked                = "REVOKED"
	MerchantCancelStateSystemProcessing       = "SYSTEM_PROCESSING"
	MerchantCancelStateCanceled               = "CANCELED"
	MerchantCancelStateFundProcessing         = "FUND_PROCESSING"
	MerchantCancelStateFinish                 = "FINISH"

	PaymentChannelDirect                  = "direct"
	PaymentChannelEcommerce               = "ecommerce"
	PaymentChannelOrdinaryServiceProvider = "ordinary_service_provider"
	PaymentChannelBaofuAggregate          = "baofu_aggregate"

	ExternalPaymentProviderWechat = "wechat"
	ExternalPaymentProviderBaofu  = "baofu"

	BaofuAccountOwnerTypeMerchant = "merchant"
	BaofuAccountOwnerTypeRider    = "rider"
	BaofuAccountOwnerTypeOperator = "operator"
	BaofuAccountOwnerTypePlatform = "platform"

	BaofuAccountTypePersonal = "personal"
	BaofuAccountTypeBusiness = "business"
	BaofuAccountTypePlatform = "platform"

	BaofuAccountOpenStateProcessing = "processing"
	BaofuAccountOpenStateActive     = "active"
	BaofuAccountOpenStateFailed     = "failed"
	BaofuAccountOpenStateAbnormal   = "abnormal"

	BaofuFeeTypePaymentFee           = "payment_fee"
	BaofuFeeTypeAccountOpenVerifyFee = "account_open_verify_fee"
	BaofuFeePayerTypeMerchant        = "merchant"
	BaofuFeePayerTypePlatform        = "platform"

	BaofuWithdrawalStatusProcessing = "processing"
	BaofuWithdrawalStatusSucceeded  = "succeeded"
	BaofuWithdrawalStatusFailed     = "failed"
	BaofuWithdrawalStatusReturned   = "returned"

	BaofuMerchantReportTypeWechat = "WECHAT"
	BaofuMerchantReportTypeAlipay = "ALIPAY"

	BaofuMerchantReportStateProcessing = "processing"
	BaofuMerchantReportStateSucceeded  = "succeeded"
	BaofuMerchantReportStateFailed     = "failed"
	BaofuMerchantReportStateUnknown    = "unknown"

	BaofuMerchantReportAppletAuthStatePending     = "pending"
	BaofuMerchantReportAppletAuthStateSucceeded   = "succeeded"
	BaofuMerchantReportAppletAuthStateFailed      = "failed"
	BaofuMerchantReportAppletAuthStateNotRequired = "not_required"

	ProfitSharingReceiverOwnerTypeRider    = "rider"
	ProfitSharingReceiverOwnerTypeOperator = "operator"
	ProfitSharingReceiverOwnerTypeManual   = "manual"

	ProfitSharingReceiverTypePersonalOpenID = "PERSONAL_OPENID"
	ProfitSharingReceiverTypeMerchantID     = "MERCHANT_ID"

	ProfitSharingReceiverDesiredStatePresent = "present"
	ProfitSharingReceiverDesiredStateAbsent  = "absent"

	ProfitSharingReceiverSyncStatusPending    = "pending"
	ProfitSharingReceiverSyncStatusProcessing = "processing"
	ProfitSharingReceiverSyncStatusSynced     = "synced"
	ProfitSharingReceiverSyncStatusFailed     = "failed"
	ProfitSharingReceiverSyncStatusSkipped    = "skipped"

	ProfitSharingReceiverAttemptActionEnsure = "ensure"
	ProfitSharingReceiverAttemptActionDelete = "delete"

	ProfitSharingReceiverAttemptStatusProcessing = "processing"
	ProfitSharingReceiverAttemptStatusSucceeded  = "succeeded"
	ProfitSharingReceiverAttemptStatusFailed     = "failed"
	ProfitSharingReceiverAttemptStatusSkipped    = "skipped"

	ExternalPaymentCapabilityDirectJSAPIPayment  = "direct_jsapi_payment"
	ExternalPaymentCapabilityDirectRefund        = "direct_refund"
	ExternalPaymentCapabilityPartnerJSAPIPayment = "partner_jsapi_payment"
	ExternalPaymentCapabilityPartnerRefund       = "partner_refund"
	ExternalPaymentCapabilityCombinePayment      = "combine_payment"
	ExternalPaymentCapabilityEcommerceRefund     = "ecommerce_refund"
	ExternalPaymentCapabilityProfitSharing       = "profit_sharing"
	ExternalPaymentCapabilitySubsidy             = "subsidy"
	ExternalPaymentCapabilityApplyment           = "applyment"
	ExternalPaymentCapabilitySettlement          = "settlement"
	ExternalPaymentCapabilityWithdraw            = "withdraw"
	ExternalPaymentCapabilityCancelWithdraw      = "cancel_withdraw"
	ExternalPaymentCapabilityMerchantTransfer    = "merchant_transfer"
	ExternalPaymentCapabilityBaofuAccount        = "baofu_account"
	ExternalPaymentCapabilityBaofuMerchantReport = "baofu_merchant_report"
	ExternalPaymentCapabilityBaofuPayment        = "baofu_payment"
	ExternalPaymentCapabilityBaofuRefund         = "baofu_refund"
	ExternalPaymentCapabilityBaofuProfitSharing  = "baofu_profit_sharing"
	ExternalPaymentCapabilityBaofuWithdraw       = "baofu_withdraw"

	ExternalPaymentCommandTypeCreatePayment             = "create_payment"
	ExternalPaymentCommandTypeClosePayment              = "close_payment"
	ExternalPaymentCommandTypeCreateRefund              = "create_refund"
	ExternalPaymentCommandTypeCreateProfitSharing       = "create_profit_sharing"
	ExternalPaymentCommandTypeCreateProfitSharingReturn = "create_profit_sharing_return"
	ExternalPaymentCommandTypeFinishProfitSharing       = "finish_profit_sharing"
	ExternalPaymentCommandTypeCreateSubsidy             = "create_subsidy"
	ExternalPaymentCommandTypeReturnSubsidy             = "return_subsidy"
	ExternalPaymentCommandTypeCancelSubsidy             = "cancel_subsidy"
	ExternalPaymentCommandTypeCreateApplyment           = "create_applyment"
	ExternalPaymentCommandTypeCreateSettlement          = "create_settlement"
	ExternalPaymentCommandTypeCreateWithdraw            = "create_withdraw"
	ExternalPaymentCommandTypeCreateCancelWithdraw      = "create_cancel_withdraw"
	ExternalPaymentCommandTypeCreateTransfer            = "create_transfer"
	ExternalPaymentCommandTypeOpenBaofuAccount          = "open_baofu_account"
	ExternalPaymentCommandTypeQueryBaofuAccount         = "query_baofu_account"
	ExternalPaymentCommandTypeQueryBaofuBalance         = "query_baofu_balance"
	ExternalPaymentCommandTypeCreateBaofuWithdraw       = "create_baofu_withdraw"
	ExternalPaymentCommandTypeQueryBaofuWithdraw        = "query_baofu_withdraw"
	ExternalPaymentCommandTypeBaofuMerchantReport       = "baofu_merchant_report"
	ExternalPaymentCommandTypeBaofuMerchantReportQuery  = "baofu_merchant_report_query"
	ExternalPaymentCommandTypeBaofuBindSubConfig        = "baofu_bind_sub_config"

	ExternalPaymentBusinessOwnerRiderDeposit  = "rider_deposit"
	ExternalPaymentBusinessOwnerOrder         = "order"
	ExternalPaymentBusinessOwnerReservation   = "reservation"
	ExternalPaymentBusinessOwnerClaimRecovery = "claim_recovery"
	ExternalPaymentBusinessOwnerProfitSharing = "profit_sharing"
	ExternalPaymentBusinessOwnerSubsidy       = "subsidy"
	ExternalPaymentBusinessOwnerApplyment     = "applyment"
	ExternalPaymentBusinessOwnerMerchantFunds = "merchant_finance"

	ExternalPaymentObjectPayment             = "payment"
	ExternalPaymentObjectCombinedPayment     = "combined_payment"
	ExternalPaymentObjectRefund              = "refund"
	ExternalPaymentObjectProfitSharing       = "profit_sharing"
	ExternalPaymentObjectProfitSharingReturn = "profit_sharing_return"
	ExternalPaymentObjectSubsidy             = "subsidy"
	ExternalPaymentObjectSubsidyReturn       = "subsidy_return"
	ExternalPaymentObjectApplyment           = "applyment"
	ExternalPaymentObjectWithdraw            = "withdraw"
	ExternalPaymentObjectCancelWithdraw      = "cancel_withdraw"
	ExternalPaymentObjectMerchantTransfer    = "merchant_transfer"
	ExternalPaymentObjectComplaint           = "complaint"
	ExternalPaymentObjectViolation           = "violation"
	ExternalPaymentObjectSettlement          = "settlement"
	ExternalPaymentObjectBaofuPaymentOrder   = "baofu_payment_order"

	ExternalPaymentCommandStatusSubmitted = "submitted"
	ExternalPaymentCommandStatusAccepted  = "accepted"
	ExternalPaymentCommandStatusRejected  = "rejected"
	ExternalPaymentCommandStatusUnknown   = "unknown"

	ExternalPaymentFactSourceCallback             = "callback"
	ExternalPaymentFactSourceCommandResponse      = "command_response"
	ExternalPaymentFactSourceQuery                = "query"
	ExternalPaymentFactSourceManualReconciliation = "manual_reconciliation"

	ExternalPaymentTerminalStatusSuccess    = "success"
	ExternalPaymentTerminalStatusFailed     = "failed"
	ExternalPaymentTerminalStatusClosed     = "closed"
	ExternalPaymentTerminalStatusExpired    = "expired"
	ExternalPaymentTerminalStatusProcessing = "processing"
	ExternalPaymentTerminalStatusUnknown    = "unknown"

	ExternalPaymentFactProcessingStatusReceived     = "received"
	ExternalPaymentFactProcessingStatusTerminalized = "terminalized"
	ExternalPaymentFactProcessingStatusIgnored      = "ignored"
	ExternalPaymentFactProcessingStatusFailed       = "failed"

	ExternalPaymentFactApplicationStatusPending    = "pending"
	ExternalPaymentFactApplicationStatusProcessing = "processing"
	ExternalPaymentFactApplicationStatusApplied    = "applied"
	ExternalPaymentFactApplicationStatusSkipped    = "skipped"
	ExternalPaymentFactApplicationStatusFailed     = "failed"

	PaymentDomainOutboxStatusPending    = "pending"
	PaymentDomainOutboxStatusProcessing = "processing"
	PaymentDomainOutboxStatusPublished  = "published"
	PaymentDomainOutboxStatusFailed     = "failed"

	PaymentDomainOutboxEventOrderPaymentSucceeded       = "order_payment_succeeded"
	PaymentDomainOutboxEventReservationPaymentSucceeded = "reservation_payment_succeeded"
	PaymentDomainOutboxEventProfitSharingResultReady    = "profit_sharing_result_ready"
	PaymentDomainOutboxEventApplymentActivated          = "applyment_activated"
	PaymentDomainOutboxEventApplymentPendingStateReady  = "applyment_pending_state_ready"
	PaymentDomainOutboxEventApplymentTerminalStateReady = "applyment_terminal_state_ready"
	PaymentDomainOutboxEventOrderRefundSucceeded        = "order_refund_succeeded"
	PaymentDomainOutboxEventOrderRefundAbnormal         = "order_refund_abnormal"
	PaymentDomainOutboxEventRiderDepositRefundAbnormal  = "rider_deposit_refund_abnormal"
	PaymentDomainOutboxEventReservationRefundAbnormal   = "reservation_refund_abnormal"
	PaymentDomainOutboxAggregatePaymentOrder            = "payment_order"
	PaymentDomainOutboxAggregateProfitSharingOrder      = "profit_sharing_order"
	PaymentDomainOutboxAggregateRefundOrder             = "refund_order"
	PaymentDomainOutboxAggregateEcommerceApplyment      = "ecommerce_applyment"

	ProfitSharingOrderStatusPending    = "pending"
	ProfitSharingOrderStatusProcessing = "processing"
	ProfitSharingOrderStatusFinished   = "finished"
	ProfitSharingOrderStatusFailed     = "failed"

	MerchantCancelWithdrawStateProcessing = "WITHDRAW_PROCESSING"
	MerchantCancelWithdrawStateException  = "WITHDRAW_EXCEPTION"
	MerchantCancelWithdrawStateSucceed    = "WITHDRAW_SUCCEED"

	MerchantCapabilitySourceSystemDefault   = "system_default"
	MerchantCapabilitySourceManualReview    = "manual_review"
	MerchantCapabilitySourceMerchantClaim   = "merchant_claim"
	MerchantCapabilitySourceMigration       = "migration_backfill"
	MerchantSystemLabelSourceReconciler     = "capability_reconciler"
	MerchantSystemLabelSourceManualOverride = "manual_override"
	MerchantSystemLabelSourceMigration      = "migration_backfill"

	CredentialDocumentTypeBusinessLicense = "business_license"
	CredentialDocumentTypeFoodPermit      = "food_permit"
	CredentialDocumentTypeHealthCert      = "health_cert"

	CredentialSuspensionReasonDocumentExpired = "document_expired"

	SystemTagHasOpenKitchen = "有明厨亮灶"
	SystemTagNoOpenKitchen  = "无明厨亮灶"
	SystemTagNoDineIn       = "无堂食"
)
