// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: external_payment_fact.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkWechatSettlementTriggerForProfitSharingOrder = `-- name: CheckWechatSettlementTriggerForProfitSharingOrder :one
SELECT EXISTS (
    SELECT 1
    FROM external_payment_facts
    WHERE provider = 'wechat'
      AND channel = 'direct'
      AND capability = 'baofu_profit_sharing'
      AND fact_source = 'callback'
      AND source_event_type = 'trade_manage_order_settlement'
      AND business_owner = 'profit_sharing'
      AND business_object_type = 'profit_sharing_order'
      AND business_object_id = $1
      AND terminal_status = 'success'
      AND is_terminal = TRUE
)
`

func (q *Queries) CheckWechatSettlementTriggerForProfitSharingOrder(ctx context.Context, profitSharingOrderID pgtype.Int8) (bool, error) {
	row := q.db.QueryRow(ctx, checkWechatSettlementTriggerForProfitSharingOrder, profitSharingOrderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const claimExternalPaymentFactApplication = `-- name: ClaimExternalPaymentFactApplication :one
UPDATE external_payment_fact_applications
SET status = 'processing',
    attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $1
    AND status IN ('pending', 'failed')
RETURNING id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
`

func (q *Queries) ClaimExternalPaymentFactApplication(ctx context.Context, id int64) (ExternalPaymentFactApplication, error) {
	row := q.db.QueryRow(ctx, claimExternalPaymentFactApplication, id)
	var i ExternalPaymentFactApplication
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Consumer,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.NextRetryAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPaymentDomainOutbox = `-- name: ClaimPaymentDomainOutbox :one
UPDATE payment_domain_outbox
SET status = 'processing',
    attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $1
    AND status IN ('pending', 'failed')
    AND (next_retry_at IS NULL OR next_retry_at <= $2)
RETURNING id, event_type, aggregate_type, aggregate_id, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
`

type ClaimPaymentDomainOutboxParams struct {
	ID    int64              `json:"id"`
	NowAt pgtype.Timestamptz `json:"now_at"`
}

func (q *Queries) ClaimPaymentDomainOutbox(ctx context.Context, arg ClaimPaymentDomainOutboxParams) (PaymentDomainOutbox, error) {
	row := q.db.QueryRow(ctx, claimPaymentDomainOutbox, arg.ID, arg.NowAt)
	var i PaymentDomainOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExternalPaymentCommand = `-- name: CreateExternalPaymentCommand :one
INSERT INTO external_payment_commands (
    provider,
    channel,
    capability,
    command_type,
    business_owner,
    business_object_type,
    business_object_id,
    external_object_type,
    external_object_key,
    external_secondary_key,
    command_status,
    submitted_at,
    accepted_at,
    rejected_at,
    last_error_code,
    last_error_message,
    request_fingerprint,
    response_snapshot
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18
)
ON CONFLICT (provider, channel, capability, command_type, external_object_type, external_object_key)
DO UPDATE SET updated_at = external_payment_commands.updated_at
RETURNING id, provider, channel, capability, command_type, business_owner, business_object_type, business_object_id, external_object_type, external_object_key, external_secondary_key, command_status, submitted_at, accepted_at, rejected_at, last_error_code, last_error_message, request_fingerprint, response_snapshot, created_at, updated_at
`

type CreateExternalPaymentCommandParams struct {
	Provider             string             `json:"provider"`
	Channel              string             `json:"channel"`
	Capability           string             `json:"capability"`
	CommandType          string             `json:"command_type"`
	BusinessOwner        string             `json:"business_owner"`
	BusinessObjectType   pgtype.Text        `json:"business_object_type"`
	BusinessObjectID     pgtype.Int8        `json:"business_object_id"`
	ExternalObjectType   string             `json:"external_object_type"`
	ExternalObjectKey    string             `json:"external_object_key"`
	ExternalSecondaryKey pgtype.Text        `json:"external_secondary_key"`
	CommandStatus        string             `json:"command_status"`
	SubmittedAt          time.Time          `json:"submitted_at"`
	AcceptedAt           pgtype.Timestamptz `json:"accepted_at"`
	RejectedAt           pgtype.Timestamptz `json:"rejected_at"`
	LastErrorCode        pgtype.Text        `json:"last_error_code"`
	LastErrorMessage     pgtype.Text        `json:"last_error_message"`
	RequestFingerprint   pgtype.Text        `json:"request_fingerprint"`
	ResponseSnapshot     []byte             `json:"response_snapshot"`
}

func (q *Queries) CreateExternalPaymentCommand(ctx context.Context, arg CreateExternalPaymentCommandParams) (ExternalPaymentCommand, error) {
	row := q.db.QueryRow(ctx, createExternalPaymentCommand,
		arg.Provider,
		arg.Channel,
		arg.Capability,
		arg.CommandType,
		arg.BusinessOwner,
		arg.BusinessObjectType,
		arg.BusinessObjectID,
		arg.ExternalObjectType,
		arg.ExternalObjectKey,
		arg.ExternalSecondaryKey,
		arg.CommandStatus,
		arg.SubmittedAt,
		arg.AcceptedAt,
		arg.RejectedAt,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.RequestFingerprint,
		arg.ResponseSnapshot,
	)
	var i ExternalPaymentCommand
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Channel,
		&i.Capability,
		&i.CommandType,
		&i.BusinessOwner,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.ExternalObjectType,
		&i.ExternalObjectKey,
		&i.ExternalSecondaryKey,
		&i.CommandStatus,
		&i.SubmittedAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.RequestFingerprint,
		&i.ResponseSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExternalPaymentFact = `-- name: CreateExternalPaymentFact :one
INSERT INTO external_payment_facts (
    provider,
    channel,
    capability,
    fact_source,
    source_event_id,
    source_event_type,
    external_object_type,
    external_object_key,
    external_secondary_key,
    business_owner,
    business_object_type,
    business_object_id,
    upstream_state,
    terminal_status,
    is_terminal,
    amount,
    currency,
    occurred_at,
    upstream_updated_at,
    observed_at,
    raw_resource,
    dedupe_key,
    processing_status
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23
)
ON CONFLICT (dedupe_key)
DO UPDATE SET dedupe_key = external_payment_facts.dedupe_key
WHERE external_payment_facts.provider = excluded.provider
    AND external_payment_facts.channel = excluded.channel
    AND external_payment_facts.capability = excluded.capability
    AND external_payment_facts.fact_source = excluded.fact_source
    AND external_payment_facts.source_event_id IS NOT DISTINCT FROM excluded.source_event_id
    AND external_payment_facts.source_event_type IS NOT DISTINCT FROM excluded.source_event_type
    AND external_payment_facts.external_object_type = excluded.external_object_type
    AND external_payment_facts.external_object_key = excluded.external_object_key
    AND external_payment_facts.external_secondary_key IS NOT DISTINCT FROM excluded.external_secondary_key
    AND external_payment_facts.business_owner IS NOT DISTINCT FROM excluded.business_owner
    AND external_payment_facts.business_object_type IS NOT DISTINCT FROM excluded.business_object_type
    AND external_payment_facts.business_object_id IS NOT DISTINCT FROM excluded.business_object_id
    AND external_payment_facts.upstream_state = excluded.upstream_state
    AND external_payment_facts.terminal_status = excluded.terminal_status
    AND external_payment_facts.is_terminal = excluded.is_terminal
    AND external_payment_facts.amount IS NOT DISTINCT FROM excluded.amount
    AND external_payment_facts.currency = excluded.currency
RETURNING id, provider, channel, capability, fact_source, source_event_id, source_event_type, external_object_type, external_object_key, external_secondary_key, business_owner, business_object_type, business_object_id, upstream_state, terminal_status, is_terminal, amount, currency, occurred_at, upstream_updated_at, observed_at, raw_resource, dedupe_key, processing_status, processing_error, processed_at, created_at, updated_at
`

type CreateExternalPaymentFactParams struct {
	Provider             string             `json:"provider"`
	Channel              string             `json:"channel"`
	Capability           string             `json:"capability"`
	FactSource           string             `json:"fact_source"`
	SourceEventID        pgtype.Text        `json:"source_event_id"`
	SourceEventType      pgtype.Text        `json:"source_event_type"`
	ExternalObjectType   string             `json:"external_object_type"`
	ExternalObjectKey    string             `json:"external_object_key"`
	ExternalSecondaryKey pgtype.Text        `json:"external_secondary_key"`
	BusinessOwner        pgtype.Text        `json:"business_owner"`
	BusinessObjectType   pgtype.Text        `json:"business_object_type"`
	BusinessObjectID     pgtype.Int8        `json:"business_object_id"`
	UpstreamState        string             `json:"upstream_state"`
	TerminalStatus       string             `json:"terminal_status"`
	IsTerminal           bool               `json:"is_terminal"`
	Amount               pgtype.Int8        `json:"amount"`
	Currency             string             `json:"currency"`
	OccurredAt           pgtype.Timestamptz `json:"occurred_at"`
	UpstreamUpdatedAt    pgtype.Timestamptz `json:"upstream_updated_at"`
	ObservedAt           time.Time          `json:"observed_at"`
	RawResource          []byte             `json:"raw_resource"`
	DedupeKey            string             `json:"dedupe_key"`
	ProcessingStatus     string             `json:"processing_status"`
}

func (q *Queries) CreateExternalPaymentFact(ctx context.Context, arg CreateExternalPaymentFactParams) (ExternalPaymentFact, error) {
	row := q.db.QueryRow(ctx, createExternalPaymentFact,
		arg.Provider,
		arg.Channel,
		arg.Capability,
		arg.FactSource,
		arg.SourceEventID,
		arg.SourceEventType,
		arg.ExternalObjectType,
		arg.ExternalObjectKey,
		arg.ExternalSecondaryKey,
		arg.BusinessOwner,
		arg.BusinessObjectType,
		arg.BusinessObjectID,
		arg.UpstreamState,
		arg.TerminalStatus,
		arg.IsTerminal,
		arg.Amount,
		arg.Currency,
		arg.OccurredAt,
		arg.UpstreamUpdatedAt,
		arg.ObservedAt,
		arg.RawResource,
		arg.DedupeKey,
		arg.ProcessingStatus,
	)
	var i ExternalPaymentFact
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Channel,
		&i.Capability,
		&i.FactSource,
		&i.SourceEventID,
		&i.SourceEventType,
		&i.ExternalObjectType,
		&i.ExternalObjectKey,
		&i.ExternalSecondaryKey,
		&i.BusinessOwner,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.UpstreamState,
		&i.TerminalStatus,
		&i.IsTerminal,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.UpstreamUpdatedAt,
		&i.ObservedAt,
		&i.RawResource,
		&i.DedupeKey,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExternalPaymentFactApplication = `-- name: CreateExternalPaymentFactApplication :one
INSERT INTO external_payment_fact_applications (
    fact_id,
    consumer,
    business_object_type,
    business_object_id,
    status,
    next_retry_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (fact_id, consumer, business_object_type, business_object_id)
DO UPDATE SET updated_at = external_payment_fact_applications.updated_at
RETURNING id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
`

type CreateExternalPaymentFactApplicationParams struct {
	FactID             int64              `json:"fact_id"`
	Consumer           string             `json:"consumer"`
	BusinessObjectType string             `json:"business_object_type"`
	BusinessObjectID   int64              `json:"business_object_id"`
	Status             string             `json:"status"`
	NextRetryAt        pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) CreateExternalPaymentFactApplication(ctx context.Context, arg CreateExternalPaymentFactApplicationParams) (ExternalPaymentFactApplication, error) {
	row := q.db.QueryRow(ctx, createExternalPaymentFactApplication,
		arg.FactID,
		arg.Consumer,
		arg.BusinessObjectType,
		arg.BusinessObjectID,
		arg.Status,
		arg.NextRetryAt,
	)
	var i ExternalPaymentFactApplication
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Consumer,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.NextRetryAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentDomainOutbox = `-- name: CreatePaymentDomainOutbox :one
INSERT INTO payment_domain_outbox (
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    status,
    next_retry_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, event_type, aggregate_type, aggregate_id, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
`

type CreatePaymentDomainOutboxParams struct {
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) CreatePaymentDomainOutbox(ctx context.Context, arg CreatePaymentDomainOutboxParams) (PaymentDomainOutbox, error) {
	row := q.db.QueryRow(ctx, createPaymentDomainOutbox,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.Status,
		arg.NextRetryAt,
	)
	var i PaymentDomainOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentDomainOutboxOnce = `-- name: CreatePaymentDomainOutboxOnce :one
INSERT INTO payment_domain_outbox (
    event_type,
    aggregate_type,
    aggregate_id,
    payload,
    status,
    next_retry_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (event_type, aggregate_type, aggregate_id)
DO UPDATE SET updated_at = payment_domain_outbox.updated_at
WHERE payment_domain_outbox.payload = excluded.payload
RETURNING id, event_type, aggregate_type, aggregate_id, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
`

type CreatePaymentDomainOutboxOnceParams struct {
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   int64              `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) CreatePaymentDomainOutboxOnce(ctx context.Context, arg CreatePaymentDomainOutboxOnceParams) (PaymentDomainOutbox, error) {
	row := q.db.QueryRow(ctx, createPaymentDomainOutboxOnce,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.Status,
		arg.NextRetryAt,
	)
	var i PaymentDomainOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalPaymentCommandByExternalObject = `-- name: GetExternalPaymentCommandByExternalObject :one
SELECT id, provider, channel, capability, command_type, business_owner, business_object_type, business_object_id, external_object_type, external_object_key, external_secondary_key, command_status, submitted_at, accepted_at, rejected_at, last_error_code, last_error_message, request_fingerprint, response_snapshot, created_at, updated_at
FROM external_payment_commands
WHERE provider = $1
    AND channel = $2
    AND capability = $3
    AND command_type = $4
    AND external_object_type = $5
    AND external_object_key = $6
LIMIT 1
`

type GetExternalPaymentCommandByExternalObjectParams struct {
	Provider           string `json:"provider"`
	Channel            string `json:"channel"`
	Capability         string `json:"capability"`
	CommandType        string `json:"command_type"`
	ExternalObjectType string `json:"external_object_type"`
	ExternalObjectKey  string `json:"external_object_key"`
}

func (q *Queries) GetExternalPaymentCommandByExternalObject(ctx context.Context, arg GetExternalPaymentCommandByExternalObjectParams) (ExternalPaymentCommand, error) {
	row := q.db.QueryRow(ctx, getExternalPaymentCommandByExternalObject,
		arg.Provider,
		arg.Channel,
		arg.Capability,
		arg.CommandType,
		arg.ExternalObjectType,
		arg.ExternalObjectKey,
	)
	var i ExternalPaymentCommand
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Channel,
		&i.Capability,
		&i.CommandType,
		&i.BusinessOwner,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.ExternalObjectType,
		&i.ExternalObjectKey,
		&i.ExternalSecondaryKey,
		&i.CommandStatus,
		&i.SubmittedAt,
		&i.AcceptedAt,
		&i.RejectedAt,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.RequestFingerprint,
		&i.ResponseSnapshot,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalPaymentFact = `-- name: GetExternalPaymentFact :one
SELECT id, provider, channel, capability, fact_source, source_event_id, source_event_type, external_object_type, external_object_key, external_secondary_key, business_owner, business_object_type, business_object_id, upstream_state, terminal_status, is_terminal, amount, currency, occurred_at, upstream_updated_at, observed_at, raw_resource, dedupe_key, processing_status, processing_error, processed_at, created_at, updated_at
FROM external_payment_facts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetExternalPaymentFact(ctx context.Context, id int64) (ExternalPaymentFact, error) {
	row := q.db.QueryRow(ctx, getExternalPaymentFact, id)
	var i ExternalPaymentFact
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Channel,
		&i.Capability,
		&i.FactSource,
		&i.SourceEventID,
		&i.SourceEventType,
		&i.ExternalObjectType,
		&i.ExternalObjectKey,
		&i.ExternalSecondaryKey,
		&i.BusinessOwner,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.UpstreamState,
		&i.TerminalStatus,
		&i.IsTerminal,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.UpstreamUpdatedAt,
		&i.ObservedAt,
		&i.RawResource,
		&i.DedupeKey,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalPaymentFactApplication = `-- name: GetExternalPaymentFactApplication :one
SELECT id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
FROM external_payment_fact_applications
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetExternalPaymentFactApplication(ctx context.Context, id int64) (ExternalPaymentFactApplication, error) {
	row := q.db.QueryRow(ctx, getExternalPaymentFactApplication, id)
	var i ExternalPaymentFactApplication
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Consumer,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.NextRetryAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalPaymentFactByDedupeKey = `-- name: GetExternalPaymentFactByDedupeKey :one
SELECT id, provider, channel, capability, fact_source, source_event_id, source_event_type, external_object_type, external_object_key, external_secondary_key, business_owner, business_object_type, business_object_id, upstream_state, terminal_status, is_terminal, amount, currency, occurred_at, upstream_updated_at, observed_at, raw_resource, dedupe_key, processing_status, processing_error, processed_at, created_at, updated_at
FROM external_payment_facts
WHERE dedupe_key = $1
LIMIT 1
`

func (q *Queries) GetExternalPaymentFactByDedupeKey(ctx context.Context, dedupeKey string) (ExternalPaymentFact, error) {
	row := q.db.QueryRow(ctx, getExternalPaymentFactByDedupeKey, dedupeKey)
	var i ExternalPaymentFact
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Channel,
		&i.Capability,
		&i.FactSource,
		&i.SourceEventID,
		&i.SourceEventType,
		&i.ExternalObjectType,
		&i.ExternalObjectKey,
		&i.ExternalSecondaryKey,
		&i.BusinessOwner,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.UpstreamState,
		&i.TerminalStatus,
		&i.IsTerminal,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.UpstreamUpdatedAt,
		&i.ObservedAt,
		&i.RawResource,
		&i.DedupeKey,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExternalPaymentFactApplicationsByFact = `-- name: ListExternalPaymentFactApplicationsByFact :many
SELECT id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
FROM external_payment_fact_applications
WHERE fact_id = $1
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListExternalPaymentFactApplicationsByFact(ctx context.Context, factID int64) ([]ExternalPaymentFactApplication, error) {
	rows, err := q.db.Query(ctx, listExternalPaymentFactApplicationsByFact, factID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalPaymentFactApplication{}
	for rows.Next() {
		var i ExternalPaymentFactApplication
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.Consumer,
			&i.BusinessObjectType,
			&i.BusinessObjectID,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.NextRetryAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalPaymentFactsByExternalObject = `-- name: ListExternalPaymentFactsByExternalObject :many
SELECT id, provider, channel, capability, fact_source, source_event_id, source_event_type, external_object_type, external_object_key, external_secondary_key, business_owner, business_object_type, business_object_id, upstream_state, terminal_status, is_terminal, amount, currency, occurred_at, upstream_updated_at, observed_at, raw_resource, dedupe_key, processing_status, processing_error, processed_at, created_at, updated_at
FROM external_payment_facts
WHERE provider = $1
    AND channel = $2
    AND external_object_type = $3
    AND external_object_key = $4
ORDER BY created_at DESC, id DESC
`

type ListExternalPaymentFactsByExternalObjectParams struct {
	Provider           string `json:"provider"`
	Channel            string `json:"channel"`
	ExternalObjectType string `json:"external_object_type"`
	ExternalObjectKey  string `json:"external_object_key"`
}

func (q *Queries) ListExternalPaymentFactsByExternalObject(ctx context.Context, arg ListExternalPaymentFactsByExternalObjectParams) ([]ExternalPaymentFact, error) {
	rows, err := q.db.Query(ctx, listExternalPaymentFactsByExternalObject,
		arg.Provider,
		arg.Channel,
		arg.ExternalObjectType,
		arg.ExternalObjectKey,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalPaymentFact{}
	for rows.Next() {
		var i ExternalPaymentFact
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Channel,
			&i.Capability,
			&i.FactSource,
			&i.SourceEventID,
			&i.SourceEventType,
			&i.ExternalObjectType,
			&i.ExternalObjectKey,
			&i.ExternalSecondaryKey,
			&i.BusinessOwner,
			&i.BusinessObjectType,
			&i.BusinessObjectID,
			&i.UpstreamState,
			&i.TerminalStatus,
			&i.IsTerminal,
			&i.Amount,
			&i.Currency,
			&i.OccurredAt,
			&i.UpstreamUpdatedAt,
			&i.ObservedAt,
			&i.RawResource,
			&i.DedupeKey,
			&i.ProcessingStatus,
			&i.ProcessingError,
			&i.ProcessedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPaymentDomainOutbox = `-- name: ListPendingPaymentDomainOutbox :many
SELECT id, event_type, aggregate_type, aggregate_id, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
FROM payment_domain_outbox
WHERE status IN ('pending', 'failed')
    AND (next_retry_at IS NULL OR next_retry_at <= $1)
ORDER BY COALESCE(next_retry_at, created_at) ASC, id ASC
LIMIT $2
`

type ListPendingPaymentDomainOutboxParams struct {
	NowAt      pgtype.Timestamptz `json:"now_at"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListPendingPaymentDomainOutbox(ctx context.Context, arg ListPendingPaymentDomainOutboxParams) ([]PaymentDomainOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingPaymentDomainOutbox, arg.NowAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentDomainOutbox{}
	for rows.Next() {
		var i PaymentDomainOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingPaymentDomainOutboxByEventType = `-- name: ListPendingPaymentDomainOutboxByEventType :many
SELECT id, event_type, aggregate_type, aggregate_id, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
FROM payment_domain_outbox
WHERE event_type = $1
    AND status IN ('pending', 'failed')
    AND (next_retry_at IS NULL OR next_retry_at <= $2)
ORDER BY COALESCE(next_retry_at, created_at) ASC, id ASC
LIMIT $3
`

type ListPendingPaymentDomainOutboxByEventTypeParams struct {
	EventType  string             `json:"event_type"`
	NowAt      pgtype.Timestamptz `json:"now_at"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListPendingPaymentDomainOutboxByEventType(ctx context.Context, arg ListPendingPaymentDomainOutboxByEventTypeParams) ([]PaymentDomainOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingPaymentDomainOutboxByEventType, arg.EventType, arg.NowAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentDomainOutbox{}
	for rows.Next() {
		var i PaymentDomainOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetryableExternalPaymentFactApplications = `-- name: ListRetryableExternalPaymentFactApplications :many
SELECT id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
FROM external_payment_fact_applications
WHERE status IN ('pending', 'failed')
    AND (next_retry_at IS NULL OR next_retry_at <= $1)
ORDER BY COALESCE(next_retry_at, created_at) ASC, id ASC
LIMIT $2
`

type ListRetryableExternalPaymentFactApplicationsParams struct {
	NowAt      pgtype.Timestamptz `json:"now_at"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListRetryableExternalPaymentFactApplications(ctx context.Context, arg ListRetryableExternalPaymentFactApplicationsParams) ([]ExternalPaymentFactApplication, error) {
	rows, err := q.db.Query(ctx, listRetryableExternalPaymentFactApplications, arg.NowAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalPaymentFactApplication{}
	for rows.Next() {
		var i ExternalPaymentFactApplication
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.Consumer,
			&i.BusinessObjectType,
			&i.BusinessObjectID,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.NextRetryAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetryableExternalPaymentFactApplicationsByTarget = `-- name: ListRetryableExternalPaymentFactApplicationsByTarget :many
SELECT id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
FROM external_payment_fact_applications
WHERE consumer = $1
    AND business_object_type = $2
    AND status IN ('pending', 'failed')
    AND (next_retry_at IS NULL OR next_retry_at <= $3)
ORDER BY COALESCE(next_retry_at, created_at) ASC, id ASC
LIMIT $4
`

type ListRetryableExternalPaymentFactApplicationsByTargetParams struct {
	Consumer           string             `json:"consumer"`
	BusinessObjectType string             `json:"business_object_type"`
	NowAt              pgtype.Timestamptz `json:"now_at"`
	LimitCount         int32              `json:"limit_count"`
}

func (q *Queries) ListRetryableExternalPaymentFactApplicationsByTarget(ctx context.Context, arg ListRetryableExternalPaymentFactApplicationsByTargetParams) ([]ExternalPaymentFactApplication, error) {
	rows, err := q.db.Query(ctx, listRetryableExternalPaymentFactApplicationsByTarget,
		arg.Consumer,
		arg.BusinessObjectType,
		arg.NowAt,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalPaymentFactApplication{}
	for rows.Next() {
		var i ExternalPaymentFactApplication
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.Consumer,
			&i.BusinessObjectType,
			&i.BusinessObjectID,
			&i.Status,
			&i.AttemptCount,
			&i.LastError,
			&i.NextRetryAt,
			&i.AppliedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExternalPaymentFactApplicationApplied = `-- name: MarkExternalPaymentFactApplicationApplied :one
UPDATE external_payment_fact_applications
SET status = 'applied',
    last_error = NULL,
    next_retry_at = NULL,
    applied_at = $1,
    updated_at = now()
WHERE id = $2
    AND status = 'processing'
RETURNING id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
`

type MarkExternalPaymentFactApplicationAppliedParams struct {
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
	ID        int64              `json:"id"`
}

func (q *Queries) MarkExternalPaymentFactApplicationApplied(ctx context.Context, arg MarkExternalPaymentFactApplicationAppliedParams) (ExternalPaymentFactApplication, error) {
	row := q.db.QueryRow(ctx, markExternalPaymentFactApplicationApplied, arg.AppliedAt, arg.ID)
	var i ExternalPaymentFactApplication
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Consumer,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.NextRetryAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExternalPaymentFactApplicationFailed = `-- name: MarkExternalPaymentFactApplicationFailed :one
UPDATE external_payment_fact_applications
SET status = 'failed',
    last_error = $1,
    next_retry_at = $2,
    updated_at = now()
WHERE id = $3
    AND status = 'processing'
RETURNING id, fact_id, consumer, business_object_type, business_object_id, status, attempt_count, last_error, next_retry_at, applied_at, created_at, updated_at
`

type MarkExternalPaymentFactApplicationFailedParams struct {
	LastError   pgtype.Text        `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	ID          int64              `json:"id"`
}

func (q *Queries) MarkExternalPaymentFactApplicationFailed(ctx context.Context, arg MarkExternalPaymentFactApplicationFailedParams) (ExternalPaymentFactApplication, error) {
	row := q.db.QueryRow(ctx, markExternalPaymentFactApplicationFailed, arg.LastError, arg.NextRetryAt, arg.ID)
	var i ExternalPaymentFactApplication
	err := row.Scan(
		&i.ID,
		&i.FactID,
		&i.Consumer,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.Status,
		&i.AttemptCount,
		&i.LastError,
		&i.NextRetryAt,
		&i.AppliedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentDomainOutboxFailed = `-- name: MarkPaymentDomainOutboxFailed :one
UPDATE payment_domain_outbox
SET status = 'failed',
    last_error = $1,
    next_retry_at = $2,
    updated_at = now()
WHERE id = $3
    AND status = 'processing'
RETURNING id, event_type, aggregate_type, aggregate_id, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
`

type MarkPaymentDomainOutboxFailedParams struct {
	LastError   pgtype.Text        `json:"last_error"`
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	ID          int64              `json:"id"`
}

func (q *Queries) MarkPaymentDomainOutboxFailed(ctx context.Context, arg MarkPaymentDomainOutboxFailedParams) (PaymentDomainOutbox, error) {
	row := q.db.QueryRow(ctx, markPaymentDomainOutboxFailed, arg.LastError, arg.NextRetryAt, arg.ID)
	var i PaymentDomainOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markPaymentDomainOutboxPublished = `-- name: MarkPaymentDomainOutboxPublished :one
UPDATE payment_domain_outbox
SET status = 'published',
    next_retry_at = NULL,
    last_error = NULL,
    updated_at = now()
WHERE id = $1
    AND status = 'processing'
RETURNING id, event_type, aggregate_type, aggregate_id, payload, status, attempt_count, next_retry_at, last_error, created_at, updated_at
`

func (q *Queries) MarkPaymentDomainOutboxPublished(ctx context.Context, id int64) (PaymentDomainOutbox, error) {
	row := q.db.QueryRow(ctx, markPaymentDomainOutboxPublished, id)
	var i PaymentDomainOutbox
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.AttemptCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateExternalPaymentFactProcessingStatus = `-- name: UpdateExternalPaymentFactProcessingStatus :one
UPDATE external_payment_facts
SET processing_status = $1,
    processing_error = $2,
    processed_at = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, provider, channel, capability, fact_source, source_event_id, source_event_type, external_object_type, external_object_key, external_secondary_key, business_owner, business_object_type, business_object_id, upstream_state, terminal_status, is_terminal, amount, currency, occurred_at, upstream_updated_at, observed_at, raw_resource, dedupe_key, processing_status, processing_error, processed_at, created_at, updated_at
`

type UpdateExternalPaymentFactProcessingStatusParams struct {
	ProcessingStatus string             `json:"processing_status"`
	ProcessingError  pgtype.Text        `json:"processing_error"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	ID               int64              `json:"id"`
}

func (q *Queries) UpdateExternalPaymentFactProcessingStatus(ctx context.Context, arg UpdateExternalPaymentFactProcessingStatusParams) (ExternalPaymentFact, error) {
	row := q.db.QueryRow(ctx, updateExternalPaymentFactProcessingStatus,
		arg.ProcessingStatus,
		arg.ProcessingError,
		arg.ProcessedAt,
		arg.ID,
	)
	var i ExternalPaymentFact
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Channel,
		&i.Capability,
		&i.FactSource,
		&i.SourceEventID,
		&i.SourceEventType,
		&i.ExternalObjectType,
		&i.ExternalObjectKey,
		&i.ExternalSecondaryKey,
		&i.BusinessOwner,
		&i.BusinessObjectType,
		&i.BusinessObjectID,
		&i.UpstreamState,
		&i.TerminalStatus,
		&i.IsTerminal,
		&i.Amount,
		&i.Currency,
		&i.OccurredAt,
		&i.UpstreamUpdatedAt,
		&i.ObservedAt,
		&i.RawResource,
		&i.DedupeKey,
		&i.ProcessingStatus,
		&i.ProcessingError,
		&i.ProcessedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
