// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant_app_device.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearMerchantAppDevicePushFailure = `-- name: ClearMerchantAppDevicePushFailure :execrows
UPDATE merchant_app_devices
SET push_failure_count = 0,
    last_push_failure_reason = NULL,
    last_push_failure_at = NULL,
    push_degraded_at = NULL,
    updated_at = now()
WHERE id = $1
  AND push_token = $2
  AND status = 'active'
  AND (
      push_failure_count <> 0
      OR last_push_failure_reason IS NOT NULL
      OR last_push_failure_at IS NOT NULL
      OR push_degraded_at IS NOT NULL
  )
`

type ClearMerchantAppDevicePushFailureParams struct {
	ID        int64  `json:"id"`
	PushToken string `json:"push_token"`
}

func (q *Queries) ClearMerchantAppDevicePushFailure(ctx context.Context, arg ClearMerchantAppDevicePushFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearMerchantAppDevicePushFailure, arg.ID, arg.PushToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateMerchantAppDevicesByPushToken = `-- name: DeactivateMerchantAppDevicesByPushToken :exec
UPDATE merchant_app_devices
SET status = 'inactive',
    unregistered_at = COALESCE(unregistered_at, now()),
    updated_at = now()
WHERE push_token = $1
  AND device_id <> $2
  AND status = 'active'
`

type DeactivateMerchantAppDevicesByPushTokenParams struct {
	PushToken string `json:"push_token"`
	DeviceID  string `json:"device_id"`
}

func (q *Queries) DeactivateMerchantAppDevicesByPushToken(ctx context.Context, arg DeactivateMerchantAppDevicesByPushTokenParams) error {
	_, err := q.db.Exec(ctx, deactivateMerchantAppDevicesByPushToken, arg.PushToken, arg.DeviceID)
	return err
}

const deactivateStaleMerchantAppDevices = `-- name: DeactivateStaleMerchantAppDevices :execrows
UPDATE merchant_app_devices
SET status = 'inactive',
    unregistered_at = COALESCE(unregistered_at, now()),
    updated_at = now()
WHERE status = 'active'
  AND last_active_at < $1
`

func (q *Queries) DeactivateStaleMerchantAppDevices(ctx context.Context, lastActiveBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateStaleMerchantAppDevices, lastActiveBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveMerchantAppDevice = `-- name: GetActiveMerchantAppDevice :one
SELECT id, merchant_id, user_id, device_id, platform, provider, push_token, status, device_model, os_version, app_version, last_registered_at, last_active_at, unregistered_at, created_at, updated_at, push_failure_count, last_push_failure_reason, last_push_failure_at, push_degraded_at
FROM merchant_app_devices
WHERE merchant_id = $1
  AND device_id = $2
  AND status = 'active'
LIMIT 1
`

type GetActiveMerchantAppDeviceParams struct {
	MerchantID int64  `json:"merchant_id"`
	DeviceID   string `json:"device_id"`
}

func (q *Queries) GetActiveMerchantAppDevice(ctx context.Context, arg GetActiveMerchantAppDeviceParams) (MerchantAppDevice, error) {
	row := q.db.QueryRow(ctx, getActiveMerchantAppDevice, arg.MerchantID, arg.DeviceID)
	var i MerchantAppDevice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.Provider,
		&i.PushToken,
		&i.Status,
		&i.DeviceModel,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastRegisteredAt,
		&i.LastActiveAt,
		&i.UnregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushFailureCount,
		&i.LastPushFailureReason,
		&i.LastPushFailureAt,
		&i.PushDegradedAt,
	)
	return i, err
}

const listActiveMerchantAppDevicesByMerchant = `-- name: ListActiveMerchantAppDevicesByMerchant :many
SELECT id, merchant_id, user_id, device_id, platform, provider, push_token, status, device_model, os_version, app_version, last_registered_at, last_active_at, unregistered_at, created_at, updated_at, push_failure_count, last_push_failure_reason, last_push_failure_at, push_degraded_at
FROM merchant_app_devices
WHERE merchant_id = $1
  AND status = 'active'
ORDER BY last_active_at DESC, id DESC
`

func (q *Queries) ListActiveMerchantAppDevicesByMerchant(ctx context.Context, merchantID int64) ([]MerchantAppDevice, error) {
	rows, err := q.db.Query(ctx, listActiveMerchantAppDevicesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantAppDevice{}
	for rows.Next() {
		var i MerchantAppDevice
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.UserID,
			&i.DeviceID,
			&i.Platform,
			&i.Provider,
			&i.PushToken,
			&i.Status,
			&i.DeviceModel,
			&i.OsVersion,
			&i.AppVersion,
			&i.LastRegisteredAt,
			&i.LastActiveAt,
			&i.UnregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushFailureCount,
			&i.LastPushFailureReason,
			&i.LastPushFailureAt,
			&i.PushDegradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveMerchantAppDevicesByMerchantAndProvider = `-- name: ListActiveMerchantAppDevicesByMerchantAndProvider :many
SELECT id, merchant_id, user_id, device_id, platform, provider, push_token, status, device_model, os_version, app_version, last_registered_at, last_active_at, unregistered_at, created_at, updated_at, push_failure_count, last_push_failure_reason, last_push_failure_at, push_degraded_at
FROM merchant_app_devices
WHERE merchant_id = $1
  AND provider = $2
  AND status = 'active'
ORDER BY last_active_at DESC, id DESC
`

type ListActiveMerchantAppDevicesByMerchantAndProviderParams struct {
	MerchantID int64  `json:"merchant_id"`
	Provider   string `json:"provider"`
}

func (q *Queries) ListActiveMerchantAppDevicesByMerchantAndProvider(ctx context.Context, arg ListActiveMerchantAppDevicesByMerchantAndProviderParams) ([]MerchantAppDevice, error) {
	rows, err := q.db.Query(ctx, listActiveMerchantAppDevicesByMerchantAndProvider, arg.MerchantID, arg.Provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantAppDevice{}
	for rows.Next() {
		var i MerchantAppDevice
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.UserID,
			&i.DeviceID,
			&i.Platform,
			&i.Provider,
			&i.PushToken,
			&i.Status,
			&i.DeviceModel,
			&i.OsVersion,
			&i.AppVersion,
			&i.LastRegisteredAt,
			&i.LastActiveAt,
			&i.UnregisteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushFailureCount,
			&i.LastPushFailureReason,
			&i.LastPushFailureAt,
			&i.PushDegradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMerchantAppDevicePermanentPushFailure = `-- name: RecordMerchantAppDevicePermanentPushFailure :execrows
UPDATE merchant_app_devices
SET push_failure_count = push_failure_count + 1,
    last_push_failure_reason = $1,
    last_push_failure_at = now(),
    push_degraded_at = COALESCE(push_degraded_at, now()),
    status = CASE
        WHEN push_failure_count + 1 >= $2::integer THEN 'inactive'
        ELSE status
    END,
    unregistered_at = CASE
        WHEN push_failure_count + 1 >= $2::integer THEN COALESCE(unregistered_at, now())
        ELSE unregistered_at
    END,
    updated_at = now()
WHERE id = $3
  AND push_token = $4
  AND status = 'active'
`

type RecordMerchantAppDevicePermanentPushFailureParams struct {
	LastPushFailureReason pgtype.Text `json:"last_push_failure_reason"`
	DeactivateAfterCount  int32       `json:"deactivate_after_count"`
	ID                    int64       `json:"id"`
	PushToken             string      `json:"push_token"`
}

func (q *Queries) RecordMerchantAppDevicePermanentPushFailure(ctx context.Context, arg RecordMerchantAppDevicePermanentPushFailureParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordMerchantAppDevicePermanentPushFailure,
		arg.LastPushFailureReason,
		arg.DeactivateAfterCount,
		arg.ID,
		arg.PushToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registerMerchantAppDevice = `-- name: RegisterMerchantAppDevice :one
INSERT INTO merchant_app_devices (
    merchant_id,
    user_id,
    device_id,
    platform,
    provider,
    push_token,
    status,
    device_model,
    os_version,
    app_version,
    last_registered_at,
    last_active_at,
    unregistered_at,
    push_failure_count,
    last_push_failure_reason,
    last_push_failure_at,
    push_degraded_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    'active',
    $7,
    $8,
    $9,
    now(),
    now(),
    NULL,
    0,
    NULL,
    NULL,
    NULL
)
ON CONFLICT (device_id) WHERE status = 'active' DO UPDATE
SET merchant_id = EXCLUDED.merchant_id,
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    provider = EXCLUDED.provider,
    push_token = EXCLUDED.push_token,
    status = 'active',
    device_model = EXCLUDED.device_model,
    os_version = EXCLUDED.os_version,
    app_version = EXCLUDED.app_version,
    last_registered_at = now(),
    last_active_at = now(),
    unregistered_at = NULL,
    push_failure_count = 0,
    last_push_failure_reason = NULL,
    last_push_failure_at = NULL,
    push_degraded_at = NULL,
    updated_at = now()
RETURNING id, merchant_id, user_id, device_id, platform, provider, push_token, status, device_model, os_version, app_version, last_registered_at, last_active_at, unregistered_at, created_at, updated_at, push_failure_count, last_push_failure_reason, last_push_failure_at, push_degraded_at
`

type RegisterMerchantAppDeviceParams struct {
	MerchantID  int64       `json:"merchant_id"`
	UserID      int64       `json:"user_id"`
	DeviceID    string      `json:"device_id"`
	Platform    string      `json:"platform"`
	Provider    string      `json:"provider"`
	PushToken   string      `json:"push_token"`
	DeviceModel pgtype.Text `json:"device_model"`
	OsVersion   pgtype.Text `json:"os_version"`
	AppVersion  pgtype.Text `json:"app_version"`
}

func (q *Queries) RegisterMerchantAppDevice(ctx context.Context, arg RegisterMerchantAppDeviceParams) (MerchantAppDevice, error) {
	row := q.db.QueryRow(ctx, registerMerchantAppDevice,
		arg.MerchantID,
		arg.UserID,
		arg.DeviceID,
		arg.Platform,
		arg.Provider,
		arg.PushToken,
		arg.DeviceModel,
		arg.OsVersion,
		arg.AppVersion,
	)
	var i MerchantAppDevice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.Provider,
		&i.PushToken,
		&i.Status,
		&i.DeviceModel,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastRegisteredAt,
		&i.LastActiveAt,
		&i.UnregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushFailureCount,
		&i.LastPushFailureReason,
		&i.LastPushFailureAt,
		&i.PushDegradedAt,
	)
	return i, err
}

const unregisterMerchantAppDevice = `-- name: UnregisterMerchantAppDevice :execrows
UPDATE merchant_app_devices
SET status = 'inactive',
    unregistered_at = COALESCE(unregistered_at, now()),
    updated_at = now()
WHERE merchant_id = $1
  AND device_id = $2
  AND status = 'active'
`

type UnregisterMerchantAppDeviceParams struct {
	MerchantID int64  `json:"merchant_id"`
	DeviceID   string `json:"device_id"`
}

func (q *Queries) UnregisterMerchantAppDevice(ctx context.Context, arg UnregisterMerchantAppDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, unregisterMerchantAppDevice, arg.MerchantID, arg.DeviceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMerchantAppDeviceHeartbeat = `-- name: UpdateMerchantAppDeviceHeartbeat :one
UPDATE merchant_app_devices
SET provider = COALESCE($1, provider),
    push_token = COALESCE($2, push_token),
    device_model = COALESCE($3, device_model),
    os_version = COALESCE($4, os_version),
    app_version = COALESCE($5, app_version),
    last_active_at = now(),
    push_failure_count = 0,
    last_push_failure_reason = NULL,
    last_push_failure_at = NULL,
    push_degraded_at = NULL,
    updated_at = now()
WHERE merchant_id = $6
  AND device_id = $7
  AND status = 'active'
RETURNING id, merchant_id, user_id, device_id, platform, provider, push_token, status, device_model, os_version, app_version, last_registered_at, last_active_at, unregistered_at, created_at, updated_at, push_failure_count, last_push_failure_reason, last_push_failure_at, push_degraded_at
`

type UpdateMerchantAppDeviceHeartbeatParams struct {
	Provider    pgtype.Text `json:"provider"`
	PushToken   pgtype.Text `json:"push_token"`
	DeviceModel pgtype.Text `json:"device_model"`
	OsVersion   pgtype.Text `json:"os_version"`
	AppVersion  pgtype.Text `json:"app_version"`
	MerchantID  int64       `json:"merchant_id"`
	DeviceID    string      `json:"device_id"`
}

func (q *Queries) UpdateMerchantAppDeviceHeartbeat(ctx context.Context, arg UpdateMerchantAppDeviceHeartbeatParams) (MerchantAppDevice, error) {
	row := q.db.QueryRow(ctx, updateMerchantAppDeviceHeartbeat,
		arg.Provider,
		arg.PushToken,
		arg.DeviceModel,
		arg.OsVersion,
		arg.AppVersion,
		arg.MerchantID,
		arg.DeviceID,
	)
	var i MerchantAppDevice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.UserID,
		&i.DeviceID,
		&i.Platform,
		&i.Provider,
		&i.PushToken,
		&i.Status,
		&i.DeviceModel,
		&i.OsVersion,
		&i.AppVersion,
		&i.LastRegisteredAt,
		&i.LastActiveAt,
		&i.UnregisteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushFailureCount,
		&i.LastPushFailureReason,
		&i.LastPushFailureAt,
		&i.PushDegradedAt,
	)
	return i, err
}
