// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchant_settlement_adjustment.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMerchantSettlementAdjustments = `-- name: CountMerchantSettlementAdjustments :one
SELECT COUNT(*)::bigint
FROM merchant_settlement_adjustments
WHERE merchant_id = $1
  AND created_at >= $2 AND created_at <= $3
`

type CountMerchantSettlementAdjustmentsParams struct {
	MerchantID int64     `json:"merchant_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
}

func (q *Queries) CountMerchantSettlementAdjustments(ctx context.Context, arg CountMerchantSettlementAdjustmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMerchantSettlementAdjustments, arg.MerchantID, arg.StartAt, arg.EndAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countMerchantSettlementTimeline = `-- name: CountMerchantSettlementTimeline :one
SELECT (
  (SELECT COUNT(*) FROM profit_sharing_orders p
   WHERE p.merchant_id = $1
     AND p.created_at >= $2 AND p.created_at <= $3)
  +
  (SELECT COUNT(*) FROM merchant_settlement_adjustments a
   WHERE a.merchant_id = $1
     AND a.created_at >= $2 AND a.created_at <= $3)
)::bigint AS total_count
`

type CountMerchantSettlementTimelineParams struct {
	MerchantID int64     `json:"merchant_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
}

func (q *Queries) CountMerchantSettlementTimeline(ctx context.Context, arg CountMerchantSettlementTimelineParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMerchantSettlementTimeline, arg.MerchantID, arg.StartAt, arg.EndAt)
	var total_count int64
	err := row.Scan(&total_count)
	return total_count, err
}

const createMerchantSettlementAdjustment = `-- name: CreateMerchantSettlementAdjustment :one

INSERT INTO merchant_settlement_adjustments (
  merchant_id,
  adjustment_type,
  amount,
  status,
  related_type,
  related_id,
  note,
  posted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, merchant_id, adjustment_type, amount, status, related_type, related_id, note, posted_at, created_at, updated_at
`

type CreateMerchantSettlementAdjustmentParams struct {
	MerchantID     int64              `json:"merchant_id"`
	AdjustmentType string             `json:"adjustment_type"`
	Amount         int64              `json:"amount"`
	Status         string             `json:"status"`
	RelatedType    pgtype.Text        `json:"related_type"`
	RelatedID      pgtype.Int8        `json:"related_id"`
	Note           pgtype.Text        `json:"note"`
	PostedAt       pgtype.Timestamptz `json:"posted_at"`
}

// Merchant settlement adjustment queries
func (q *Queries) CreateMerchantSettlementAdjustment(ctx context.Context, arg CreateMerchantSettlementAdjustmentParams) (MerchantSettlementAdjustment, error) {
	row := q.db.QueryRow(ctx, createMerchantSettlementAdjustment,
		arg.MerchantID,
		arg.AdjustmentType,
		arg.Amount,
		arg.Status,
		arg.RelatedType,
		arg.RelatedID,
		arg.Note,
		arg.PostedAt,
	)
	var i MerchantSettlementAdjustment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AdjustmentType,
		&i.Amount,
		&i.Status,
		&i.RelatedType,
		&i.RelatedID,
		&i.Note,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMerchantSettlementAdjustmentByRelatedAndType = `-- name: GetMerchantSettlementAdjustmentByRelatedAndType :one
SELECT id, merchant_id, adjustment_type, amount, status, related_type, related_id, note, posted_at, created_at, updated_at FROM merchant_settlement_adjustments
WHERE related_type = $1 AND related_id = $2 AND adjustment_type = $3
LIMIT 1
`

type GetMerchantSettlementAdjustmentByRelatedAndTypeParams struct {
	RelatedType    pgtype.Text `json:"related_type"`
	RelatedID      pgtype.Int8 `json:"related_id"`
	AdjustmentType string      `json:"adjustment_type"`
}

func (q *Queries) GetMerchantSettlementAdjustmentByRelatedAndType(ctx context.Context, arg GetMerchantSettlementAdjustmentByRelatedAndTypeParams) (MerchantSettlementAdjustment, error) {
	row := q.db.QueryRow(ctx, getMerchantSettlementAdjustmentByRelatedAndType, arg.RelatedType, arg.RelatedID, arg.AdjustmentType)
	var i MerchantSettlementAdjustment
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.AdjustmentType,
		&i.Amount,
		&i.Status,
		&i.RelatedType,
		&i.RelatedID,
		&i.Note,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMerchantDailySettlementAdjustments = `-- name: ListMerchantDailySettlementAdjustments :many
SELECT DATE(created_at) AS date,
       COALESCE(SUM(amount), 0)::bigint AS total_adjustment
FROM merchant_settlement_adjustments
WHERE merchant_id = $1
  AND status = 'finished'
  AND created_at >= $2 AND created_at <= $3
GROUP BY DATE(created_at)
ORDER BY date DESC
`

type ListMerchantDailySettlementAdjustmentsParams struct {
	MerchantID int64     `json:"merchant_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
}

type ListMerchantDailySettlementAdjustmentsRow struct {
	Date            pgtype.Date `json:"date"`
	TotalAdjustment int64       `json:"total_adjustment"`
}

func (q *Queries) ListMerchantDailySettlementAdjustments(ctx context.Context, arg ListMerchantDailySettlementAdjustmentsParams) ([]ListMerchantDailySettlementAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, listMerchantDailySettlementAdjustments, arg.MerchantID, arg.StartAt, arg.EndAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantDailySettlementAdjustmentsRow{}
	for rows.Next() {
		var i ListMerchantDailySettlementAdjustmentsRow
		if err := rows.Scan(&i.Date, &i.TotalAdjustment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantSettlementAdjustments = `-- name: ListMerchantSettlementAdjustments :many
SELECT id, merchant_id, adjustment_type, amount, status, related_type, related_id, note, posted_at, created_at, updated_at FROM merchant_settlement_adjustments
WHERE merchant_id = $1
  AND created_at >= $2 AND created_at <= $3
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListMerchantSettlementAdjustmentsParams struct {
	MerchantID int64     `json:"merchant_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
	Offset     int32     `json:"offset"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListMerchantSettlementAdjustments(ctx context.Context, arg ListMerchantSettlementAdjustmentsParams) ([]MerchantSettlementAdjustment, error) {
	rows, err := q.db.Query(ctx, listMerchantSettlementAdjustments,
		arg.MerchantID,
		arg.StartAt,
		arg.EndAt,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantSettlementAdjustment{}
	for rows.Next() {
		var i MerchantSettlementAdjustment
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.AdjustmentType,
			&i.Amount,
			&i.Status,
			&i.RelatedType,
			&i.RelatedID,
			&i.Note,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantSettlementTimeline = `-- name: ListMerchantSettlementTimeline :many
SELECT
  'profit_sharing'::text AS record_type,
  p.id,
  p.payment_order_id,
  p.order_source,
  p.total_amount,
  (p.platform_commission + p.operator_commission)::bigint AS platform_service_fee_amount,
  (CASE WHEN p.calculation_version = 'baofu_fee_v2' THEN p.merchant_payment_fee ELSE p.payment_fee END)::bigint AS payment_channel_fee_amount,
  p.merchant_amount AS merchant_receivable_amount,
  p.out_order_no,
  p.sharing_order_id,
  p.status,
  p.created_at,
  p.finished_at,
  NULL::text AS adjustment_type,
  NULL::text AS related_type,
  NULL::bigint AS related_id
FROM profit_sharing_orders p
WHERE p.merchant_id = $3
  AND p.created_at >= $4 AND p.created_at <= $5
UNION ALL
SELECT
  'adjustment'::text AS record_type,
  a.id,
  0 AS payment_order_id,
  'adjustment'::text AS order_source,
  0 AS total_amount,
  0::bigint AS platform_service_fee_amount,
  0::bigint AS payment_channel_fee_amount,
  a.amount AS merchant_receivable_amount,
  NULL::text AS out_order_no,
  NULL::text AS sharing_order_id,
  a.status,
  a.created_at,
  a.posted_at AS finished_at,
  a.adjustment_type,
  a.related_type,
  a.related_id
FROM merchant_settlement_adjustments a
WHERE a.merchant_id = $3
  AND a.created_at >= $4 AND a.created_at <= $5
ORDER BY created_at DESC
LIMIT $2 OFFSET $1
`

type ListMerchantSettlementTimelineParams struct {
	Offset     int32     `json:"offset"`
	Limit      int32     `json:"limit"`
	MerchantID int64     `json:"merchant_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
}

type ListMerchantSettlementTimelineRow struct {
	RecordType               string             `json:"record_type"`
	ID                       int64              `json:"id"`
	PaymentOrderID           int64              `json:"payment_order_id"`
	OrderSource              string             `json:"order_source"`
	TotalAmount              int64              `json:"total_amount"`
	PlatformServiceFeeAmount int64              `json:"platform_service_fee_amount"`
	PaymentChannelFeeAmount  int64              `json:"payment_channel_fee_amount"`
	MerchantReceivableAmount int64              `json:"merchant_receivable_amount"`
	OutOrderNo               string             `json:"out_order_no"`
	SharingOrderID           pgtype.Text        `json:"sharing_order_id"`
	Status                   string             `json:"status"`
	CreatedAt                time.Time          `json:"created_at"`
	FinishedAt               pgtype.Timestamptz `json:"finished_at"`
	AdjustmentType           pgtype.Text        `json:"adjustment_type"`
	RelatedType              pgtype.Text        `json:"related_type"`
	RelatedID                pgtype.Int8        `json:"related_id"`
}

func (q *Queries) ListMerchantSettlementTimeline(ctx context.Context, arg ListMerchantSettlementTimelineParams) ([]ListMerchantSettlementTimelineRow, error) {
	rows, err := q.db.Query(ctx, listMerchantSettlementTimeline,
		arg.Offset,
		arg.Limit,
		arg.MerchantID,
		arg.StartAt,
		arg.EndAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMerchantSettlementTimelineRow{}
	for rows.Next() {
		var i ListMerchantSettlementTimelineRow
		if err := rows.Scan(
			&i.RecordType,
			&i.ID,
			&i.PaymentOrderID,
			&i.OrderSource,
			&i.TotalAmount,
			&i.PlatformServiceFeeAmount,
			&i.PaymentChannelFeeAmount,
			&i.MerchantReceivableAmount,
			&i.OutOrderNo,
			&i.SharingOrderID,
			&i.Status,
			&i.CreatedAt,
			&i.FinishedAt,
			&i.AdjustmentType,
			&i.RelatedType,
			&i.RelatedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMerchantSettlementAdjustments = `-- name: SumMerchantSettlementAdjustments :one
SELECT COALESCE(SUM(amount), 0)::bigint AS total_adjustment
FROM merchant_settlement_adjustments
WHERE merchant_id = $1
  AND status = 'finished'
  AND created_at >= $2 AND created_at <= $3
`

type SumMerchantSettlementAdjustmentsParams struct {
	MerchantID int64     `json:"merchant_id"`
	StartAt    time.Time `json:"start_at"`
	EndAt      time.Time `json:"end_at"`
}

func (q *Queries) SumMerchantSettlementAdjustments(ctx context.Context, arg SumMerchantSettlementAdjustmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumMerchantSettlementAdjustments, arg.MerchantID, arg.StartAt, arg.EndAt)
	var total_adjustment int64
	err := row.Scan(&total_adjustment)
	return total_adjustment, err
}
