// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: merchant_cancel_withdraw.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMerchantCancelWithdrawApplicationsByMerchant = `-- name: CountMerchantCancelWithdrawApplicationsByMerchant :one
SELECT COUNT(*) FROM merchant_cancel_withdraw_applications
WHERE merchant_id = $1
`

func (q *Queries) CountMerchantCancelWithdrawApplicationsByMerchant(ctx context.Context, merchantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMerchantCancelWithdrawApplicationsByMerchant, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMerchantCancelWithdrawApplication = `-- name: CreateMerchantCancelWithdrawApplication :one
INSERT INTO merchant_cancel_withdraw_applications (
    merchant_id,
    created_by_user_id,
    sub_mch_id,
    out_request_no,
    withdraw,
    business_license_status_declaration,
    proof_media_asset_ids,
    additional_material_asset_ids,
    remark,
    local_sync_state
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
) RETURNING id, merchant_id, created_by_user_id, sub_mch_id, out_request_no, applyment_id, withdraw, proof_media_asset_ids, additional_material_asset_ids, remark, local_sync_state, cancel_state, cancel_state_description, withdraw_state, withdraw_state_description, confirm_cancel_url, account_info, account_withdraw_result, latest_query_response, last_error, modify_time, submitted_at, last_query_at, created_at, updated_at, business_license_status_declaration
`

type CreateMerchantCancelWithdrawApplicationParams struct {
	MerchantID                       int64       `json:"merchant_id"`
	CreatedByUserID                  int64       `json:"created_by_user_id"`
	SubMchID                         string      `json:"sub_mch_id"`
	OutRequestNo                     string      `json:"out_request_no"`
	Withdraw                         string      `json:"withdraw"`
	BusinessLicenseStatusDeclaration pgtype.Text `json:"business_license_status_declaration"`
	ProofMediaAssetIds               []byte      `json:"proof_media_asset_ids"`
	AdditionalMaterialAssetIds       []byte      `json:"additional_material_asset_ids"`
	Remark                           pgtype.Text `json:"remark"`
	LocalSyncState                   string      `json:"local_sync_state"`
}

func (q *Queries) CreateMerchantCancelWithdrawApplication(ctx context.Context, arg CreateMerchantCancelWithdrawApplicationParams) (MerchantCancelWithdrawApplication, error) {
	row := q.db.QueryRow(ctx, createMerchantCancelWithdrawApplication,
		arg.MerchantID,
		arg.CreatedByUserID,
		arg.SubMchID,
		arg.OutRequestNo,
		arg.Withdraw,
		arg.BusinessLicenseStatusDeclaration,
		arg.ProofMediaAssetIds,
		arg.AdditionalMaterialAssetIds,
		arg.Remark,
		arg.LocalSyncState,
	)
	var i MerchantCancelWithdrawApplication
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CreatedByUserID,
		&i.SubMchID,
		&i.OutRequestNo,
		&i.ApplymentID,
		&i.Withdraw,
		&i.ProofMediaAssetIds,
		&i.AdditionalMaterialAssetIds,
		&i.Remark,
		&i.LocalSyncState,
		&i.CancelState,
		&i.CancelStateDescription,
		&i.WithdrawState,
		&i.WithdrawStateDescription,
		&i.ConfirmCancelUrl,
		&i.AccountInfo,
		&i.AccountWithdrawResult,
		&i.LatestQueryResponse,
		&i.LastError,
		&i.ModifyTime,
		&i.SubmittedAt,
		&i.LastQueryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessLicenseStatusDeclaration,
	)
	return i, err
}

const getMerchantCancelWithdrawApplication = `-- name: GetMerchantCancelWithdrawApplication :one
SELECT id, merchant_id, created_by_user_id, sub_mch_id, out_request_no, applyment_id, withdraw, proof_media_asset_ids, additional_material_asset_ids, remark, local_sync_state, cancel_state, cancel_state_description, withdraw_state, withdraw_state_description, confirm_cancel_url, account_info, account_withdraw_result, latest_query_response, last_error, modify_time, submitted_at, last_query_at, created_at, updated_at, business_license_status_declaration FROM merchant_cancel_withdraw_applications
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMerchantCancelWithdrawApplication(ctx context.Context, id int64) (MerchantCancelWithdrawApplication, error) {
	row := q.db.QueryRow(ctx, getMerchantCancelWithdrawApplication, id)
	var i MerchantCancelWithdrawApplication
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CreatedByUserID,
		&i.SubMchID,
		&i.OutRequestNo,
		&i.ApplymentID,
		&i.Withdraw,
		&i.ProofMediaAssetIds,
		&i.AdditionalMaterialAssetIds,
		&i.Remark,
		&i.LocalSyncState,
		&i.CancelState,
		&i.CancelStateDescription,
		&i.WithdrawState,
		&i.WithdrawStateDescription,
		&i.ConfirmCancelUrl,
		&i.AccountInfo,
		&i.AccountWithdrawResult,
		&i.LatestQueryResponse,
		&i.LastError,
		&i.ModifyTime,
		&i.SubmittedAt,
		&i.LastQueryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessLicenseStatusDeclaration,
	)
	return i, err
}

const getMerchantCancelWithdrawApplicationByApplymentID = `-- name: GetMerchantCancelWithdrawApplicationByApplymentID :one
SELECT id, merchant_id, created_by_user_id, sub_mch_id, out_request_no, applyment_id, withdraw, proof_media_asset_ids, additional_material_asset_ids, remark, local_sync_state, cancel_state, cancel_state_description, withdraw_state, withdraw_state_description, confirm_cancel_url, account_info, account_withdraw_result, latest_query_response, last_error, modify_time, submitted_at, last_query_at, created_at, updated_at, business_license_status_declaration FROM merchant_cancel_withdraw_applications
WHERE applyment_id = $1 LIMIT 1
`

func (q *Queries) GetMerchantCancelWithdrawApplicationByApplymentID(ctx context.Context, applymentID pgtype.Text) (MerchantCancelWithdrawApplication, error) {
	row := q.db.QueryRow(ctx, getMerchantCancelWithdrawApplicationByApplymentID, applymentID)
	var i MerchantCancelWithdrawApplication
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CreatedByUserID,
		&i.SubMchID,
		&i.OutRequestNo,
		&i.ApplymentID,
		&i.Withdraw,
		&i.ProofMediaAssetIds,
		&i.AdditionalMaterialAssetIds,
		&i.Remark,
		&i.LocalSyncState,
		&i.CancelState,
		&i.CancelStateDescription,
		&i.WithdrawState,
		&i.WithdrawStateDescription,
		&i.ConfirmCancelUrl,
		&i.AccountInfo,
		&i.AccountWithdrawResult,
		&i.LatestQueryResponse,
		&i.LastError,
		&i.ModifyTime,
		&i.SubmittedAt,
		&i.LastQueryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessLicenseStatusDeclaration,
	)
	return i, err
}

const getMerchantCancelWithdrawApplicationByOutRequestNo = `-- name: GetMerchantCancelWithdrawApplicationByOutRequestNo :one
SELECT id, merchant_id, created_by_user_id, sub_mch_id, out_request_no, applyment_id, withdraw, proof_media_asset_ids, additional_material_asset_ids, remark, local_sync_state, cancel_state, cancel_state_description, withdraw_state, withdraw_state_description, confirm_cancel_url, account_info, account_withdraw_result, latest_query_response, last_error, modify_time, submitted_at, last_query_at, created_at, updated_at, business_license_status_declaration FROM merchant_cancel_withdraw_applications
WHERE out_request_no = $1 LIMIT 1
`

func (q *Queries) GetMerchantCancelWithdrawApplicationByOutRequestNo(ctx context.Context, outRequestNo string) (MerchantCancelWithdrawApplication, error) {
	row := q.db.QueryRow(ctx, getMerchantCancelWithdrawApplicationByOutRequestNo, outRequestNo)
	var i MerchantCancelWithdrawApplication
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CreatedByUserID,
		&i.SubMchID,
		&i.OutRequestNo,
		&i.ApplymentID,
		&i.Withdraw,
		&i.ProofMediaAssetIds,
		&i.AdditionalMaterialAssetIds,
		&i.Remark,
		&i.LocalSyncState,
		&i.CancelState,
		&i.CancelStateDescription,
		&i.WithdrawState,
		&i.WithdrawStateDescription,
		&i.ConfirmCancelUrl,
		&i.AccountInfo,
		&i.AccountWithdrawResult,
		&i.LatestQueryResponse,
		&i.LastError,
		&i.ModifyTime,
		&i.SubmittedAt,
		&i.LastQueryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessLicenseStatusDeclaration,
	)
	return i, err
}

const listMerchantCancelWithdrawApplicationsByMerchant = `-- name: ListMerchantCancelWithdrawApplicationsByMerchant :many
SELECT id, merchant_id, created_by_user_id, sub_mch_id, out_request_no, applyment_id, withdraw, proof_media_asset_ids, additional_material_asset_ids, remark, local_sync_state, cancel_state, cancel_state_description, withdraw_state, withdraw_state_description, confirm_cancel_url, account_info, account_withdraw_result, latest_query_response, last_error, modify_time, submitted_at, last_query_at, created_at, updated_at, business_license_status_declaration FROM merchant_cancel_withdraw_applications
WHERE merchant_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListMerchantCancelWithdrawApplicationsByMerchantParams struct {
	MerchantID int64 `json:"merchant_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListMerchantCancelWithdrawApplicationsByMerchant(ctx context.Context, arg ListMerchantCancelWithdrawApplicationsByMerchantParams) ([]MerchantCancelWithdrawApplication, error) {
	rows, err := q.db.Query(ctx, listMerchantCancelWithdrawApplicationsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantCancelWithdrawApplication{}
	for rows.Next() {
		var i MerchantCancelWithdrawApplication
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CreatedByUserID,
			&i.SubMchID,
			&i.OutRequestNo,
			&i.ApplymentID,
			&i.Withdraw,
			&i.ProofMediaAssetIds,
			&i.AdditionalMaterialAssetIds,
			&i.Remark,
			&i.LocalSyncState,
			&i.CancelState,
			&i.CancelStateDescription,
			&i.WithdrawState,
			&i.WithdrawStateDescription,
			&i.ConfirmCancelUrl,
			&i.AccountInfo,
			&i.AccountWithdrawResult,
			&i.LatestQueryResponse,
			&i.LastError,
			&i.ModifyTime,
			&i.SubmittedAt,
			&i.LastQueryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusinessLicenseStatusDeclaration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMerchantCancelWithdrawApplications = `-- name: ListPendingMerchantCancelWithdrawApplications :many
SELECT id, merchant_id, created_by_user_id, sub_mch_id, out_request_no, applyment_id, withdraw, proof_media_asset_ids, additional_material_asset_ids, remark, local_sync_state, cancel_state, cancel_state_description, withdraw_state, withdraw_state_description, confirm_cancel_url, account_info, account_withdraw_result, latest_query_response, last_error, modify_time, submitted_at, last_query_at, created_at, updated_at, business_license_status_declaration FROM merchant_cancel_withdraw_applications
WHERE local_sync_state IN ('submit_succeeded', 'submit_unknown')
    AND COALESCE(cancel_state, '') NOT IN ('REJECTED', 'REVOKED', 'CANCELED', 'FINISH')
ORDER BY COALESCE(last_query_at, created_at) ASC, id ASC
LIMIT $1
`

func (q *Queries) ListPendingMerchantCancelWithdrawApplications(ctx context.Context, limit int32) ([]MerchantCancelWithdrawApplication, error) {
	rows, err := q.db.Query(ctx, listPendingMerchantCancelWithdrawApplications, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MerchantCancelWithdrawApplication{}
	for rows.Next() {
		var i MerchantCancelWithdrawApplication
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CreatedByUserID,
			&i.SubMchID,
			&i.OutRequestNo,
			&i.ApplymentID,
			&i.Withdraw,
			&i.ProofMediaAssetIds,
			&i.AdditionalMaterialAssetIds,
			&i.Remark,
			&i.LocalSyncState,
			&i.CancelState,
			&i.CancelStateDescription,
			&i.WithdrawState,
			&i.WithdrawStateDescription,
			&i.ConfirmCancelUrl,
			&i.AccountInfo,
			&i.AccountWithdrawResult,
			&i.LatestQueryResponse,
			&i.LastError,
			&i.ModifyTime,
			&i.SubmittedAt,
			&i.LastQueryAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BusinessLicenseStatusDeclaration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantCancelWithdrawApplicationSync = `-- name: UpdateMerchantCancelWithdrawApplicationSync :one
UPDATE merchant_cancel_withdraw_applications
SET
    applyment_id = $1,
    local_sync_state = $2,
    cancel_state = $3,
    cancel_state_description = $4,
    withdraw_state = $5,
    withdraw_state_description = $6,
    confirm_cancel_url = $7,
    account_info = $8,
    account_withdraw_result = $9,
    latest_query_response = $10,
    last_error = CASE
        WHEN $11::bool THEN NULL
        ELSE $12
    END,
    modify_time = $13,
    submitted_at = CASE
        WHEN $14::bool AND submitted_at IS NULL THEN now()
        ELSE submitted_at
    END,
    last_query_at = $15,
    updated_at = now()
WHERE id = $16
RETURNING id, merchant_id, created_by_user_id, sub_mch_id, out_request_no, applyment_id, withdraw, proof_media_asset_ids, additional_material_asset_ids, remark, local_sync_state, cancel_state, cancel_state_description, withdraw_state, withdraw_state_description, confirm_cancel_url, account_info, account_withdraw_result, latest_query_response, last_error, modify_time, submitted_at, last_query_at, created_at, updated_at, business_license_status_declaration
`

type UpdateMerchantCancelWithdrawApplicationSyncParams struct {
	ApplymentID              pgtype.Text        `json:"applyment_id"`
	LocalSyncState           string             `json:"local_sync_state"`
	CancelState              pgtype.Text        `json:"cancel_state"`
	CancelStateDescription   pgtype.Text        `json:"cancel_state_description"`
	WithdrawState            pgtype.Text        `json:"withdraw_state"`
	WithdrawStateDescription pgtype.Text        `json:"withdraw_state_description"`
	ConfirmCancelUrl         pgtype.Text        `json:"confirm_cancel_url"`
	AccountInfo              []byte             `json:"account_info"`
	AccountWithdrawResult    []byte             `json:"account_withdraw_result"`
	LatestQueryResponse      []byte             `json:"latest_query_response"`
	ClearLastError           bool               `json:"clear_last_error"`
	LastError                pgtype.Text        `json:"last_error"`
	ModifyTime               pgtype.Timestamptz `json:"modify_time"`
	MarkSubmitted            bool               `json:"mark_submitted"`
	LastQueryAt              pgtype.Timestamptz `json:"last_query_at"`
	ID                       int64              `json:"id"`
}

func (q *Queries) UpdateMerchantCancelWithdrawApplicationSync(ctx context.Context, arg UpdateMerchantCancelWithdrawApplicationSyncParams) (MerchantCancelWithdrawApplication, error) {
	row := q.db.QueryRow(ctx, updateMerchantCancelWithdrawApplicationSync,
		arg.ApplymentID,
		arg.LocalSyncState,
		arg.CancelState,
		arg.CancelStateDescription,
		arg.WithdrawState,
		arg.WithdrawStateDescription,
		arg.ConfirmCancelUrl,
		arg.AccountInfo,
		arg.AccountWithdrawResult,
		arg.LatestQueryResponse,
		arg.ClearLastError,
		arg.LastError,
		arg.ModifyTime,
		arg.MarkSubmitted,
		arg.LastQueryAt,
		arg.ID,
	)
	var i MerchantCancelWithdrawApplication
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CreatedByUserID,
		&i.SubMchID,
		&i.OutRequestNo,
		&i.ApplymentID,
		&i.Withdraw,
		&i.ProofMediaAssetIds,
		&i.AdditionalMaterialAssetIds,
		&i.Remark,
		&i.LocalSyncState,
		&i.CancelState,
		&i.CancelStateDescription,
		&i.WithdrawState,
		&i.WithdrawStateDescription,
		&i.ConfirmCancelUrl,
		&i.AccountInfo,
		&i.AccountWithdrawResult,
		&i.LatestQueryResponse,
		&i.LastError,
		&i.ModifyTime,
		&i.SubmittedAt,
		&i.LastQueryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BusinessLicenseStatusDeclaration,
	)
	return i, err
}
