// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onboarding_review.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveMerchantOnboardingReviewRunsForApplication = `-- name: CancelActiveMerchantOnboardingReviewRunsForApplication :many
UPDATE onboarding_review_runs
SET run_status = 'cancelled',
    outcome = $1,
    reason_code = $2,
    reason_message = COALESCE($3, reason_message),
    finished_at = NOW(),
    updated_at = NOW()
WHERE application_type = 'merchant'
  AND merchant_application_id = $4
  AND run_status IN ('queued', 'processing')
RETURNING id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
`

type CancelActiveMerchantOnboardingReviewRunsForApplicationParams struct {
	Outcome               pgtype.Text `json:"outcome"`
	ReasonCode            pgtype.Text `json:"reason_code"`
	ReasonMessage         pgtype.Text `json:"reason_message"`
	MerchantApplicationID pgtype.Int8 `json:"merchant_application_id"`
}

func (q *Queries) CancelActiveMerchantOnboardingReviewRunsForApplication(ctx context.Context, arg CancelActiveMerchantOnboardingReviewRunsForApplicationParams) ([]OnboardingReviewRun, error) {
	rows, err := q.db.Query(ctx, cancelActiveMerchantOnboardingReviewRunsForApplication,
		arg.Outcome,
		arg.ReasonCode,
		arg.ReasonMessage,
		arg.MerchantApplicationID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnboardingReviewRun{}
	for rows.Next() {
		var i OnboardingReviewRun
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationType,
			&i.MerchantApplicationID,
			&i.RiderApplicationID,
			&i.RunStatus,
			&i.Stage,
			&i.Outcome,
			&i.ReasonCode,
			&i.ReasonMessage,
			&i.Evidence,
			&i.RuleHits,
			&i.OcrJobRefs,
			&i.Snapshot,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const cancelOnboardingReviewRun = `-- name: CancelOnboardingReviewRun :one
UPDATE onboarding_review_runs
SET run_status = 'cancelled',
    outcome = 'needs_resubmit',
    reason_code = $1,
    reason_message = COALESCE($2, reason_message),
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $3
  AND run_status IN ('queued', 'processing')
RETURNING id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
`

type CancelOnboardingReviewRunParams struct {
	ReasonCode    pgtype.Text `json:"reason_code"`
	ReasonMessage pgtype.Text `json:"reason_message"`
	ID            int64       `json:"id"`
}

func (q *Queries) CancelOnboardingReviewRun(ctx context.Context, arg CancelOnboardingReviewRunParams) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, cancelOnboardingReviewRun, arg.ReasonCode, arg.ReasonMessage, arg.ID)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeOnboardingReviewRun = `-- name: CompleteOnboardingReviewRun :one
UPDATE onboarding_review_runs
SET run_status = 'completed',
    stage = $1,
    outcome = $2,
    reason_code = $3,
    reason_message = COALESCE($4, reason_message),
    evidence = COALESCE($5, evidence),
    rule_hits = COALESCE($6, rule_hits),
    ocr_job_refs = COALESCE($7, ocr_job_refs),
    snapshot = COALESCE($8, snapshot),
    reviewed_by = COALESCE($9, reviewed_by),
    finished_at = NOW(),
    updated_at = NOW()
WHERE id = $10
  AND run_status IN ('queued', 'processing')
RETURNING id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
`

type CompleteOnboardingReviewRunParams struct {
	Stage         string      `json:"stage"`
	Outcome       pgtype.Text `json:"outcome"`
	ReasonCode    pgtype.Text `json:"reason_code"`
	ReasonMessage pgtype.Text `json:"reason_message"`
	Evidence      []byte      `json:"evidence"`
	RuleHits      []string    `json:"rule_hits"`
	OcrJobRefs    []int64     `json:"ocr_job_refs"`
	Snapshot      []byte      `json:"snapshot"`
	ReviewedBy    pgtype.Int8 `json:"reviewed_by"`
	ID            int64       `json:"id"`
}

func (q *Queries) CompleteOnboardingReviewRun(ctx context.Context, arg CompleteOnboardingReviewRunParams) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, completeOnboardingReviewRun,
		arg.Stage,
		arg.Outcome,
		arg.ReasonCode,
		arg.ReasonMessage,
		arg.Evidence,
		arg.RuleHits,
		arg.OcrJobRefs,
		arg.Snapshot,
		arg.ReviewedBy,
		arg.ID,
	)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMerchantOnboardingReviewRun = `-- name: CreateMerchantOnboardingReviewRun :one
INSERT INTO onboarding_review_runs (
    application_type,
    merchant_application_id,
    run_status,
    stage,
    evidence,
    rule_hits,
    ocr_job_refs,
    snapshot,
    requested_by
) VALUES (
    'merchant',
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
`

type CreateMerchantOnboardingReviewRunParams struct {
	MerchantApplicationID pgtype.Int8 `json:"merchant_application_id"`
	RunStatus             string      `json:"run_status"`
	Stage                 string      `json:"stage"`
	Evidence              []byte      `json:"evidence"`
	RuleHits              []string    `json:"rule_hits"`
	OcrJobRefs            []int64     `json:"ocr_job_refs"`
	Snapshot              []byte      `json:"snapshot"`
	RequestedBy           pgtype.Int8 `json:"requested_by"`
}

func (q *Queries) CreateMerchantOnboardingReviewRun(ctx context.Context, arg CreateMerchantOnboardingReviewRunParams) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, createMerchantOnboardingReviewRun,
		arg.MerchantApplicationID,
		arg.RunStatus,
		arg.Stage,
		arg.Evidence,
		arg.RuleHits,
		arg.OcrJobRefs,
		arg.Snapshot,
		arg.RequestedBy,
	)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRiderOnboardingReviewRun = `-- name: CreateRiderOnboardingReviewRun :one
INSERT INTO onboarding_review_runs (
    application_type,
    rider_application_id,
    run_status,
    stage,
    evidence,
    rule_hits,
    ocr_job_refs,
    snapshot,
    requested_by
) VALUES (
    'rider',
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
`

type CreateRiderOnboardingReviewRunParams struct {
	RiderApplicationID pgtype.Int8 `json:"rider_application_id"`
	RunStatus          string      `json:"run_status"`
	Stage              string      `json:"stage"`
	Evidence           []byte      `json:"evidence"`
	RuleHits           []string    `json:"rule_hits"`
	OcrJobRefs         []int64     `json:"ocr_job_refs"`
	Snapshot           []byte      `json:"snapshot"`
	RequestedBy        pgtype.Int8 `json:"requested_by"`
}

func (q *Queries) CreateRiderOnboardingReviewRun(ctx context.Context, arg CreateRiderOnboardingReviewRunParams) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, createRiderOnboardingReviewRun,
		arg.RiderApplicationID,
		arg.RunStatus,
		arg.Stage,
		arg.Evidence,
		arg.RuleHits,
		arg.OcrJobRefs,
		arg.Snapshot,
		arg.RequestedBy,
	)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestMerchantOnboardingReviewRun = `-- name: GetLatestMerchantOnboardingReviewRun :one
SELECT id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
FROM onboarding_review_runs
WHERE merchant_application_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestMerchantOnboardingReviewRun(ctx context.Context, merchantApplicationID pgtype.Int8) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, getLatestMerchantOnboardingReviewRun, merchantApplicationID)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestRiderOnboardingReviewRun = `-- name: GetLatestRiderOnboardingReviewRun :one
SELECT id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
FROM onboarding_review_runs
WHERE rider_application_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestRiderOnboardingReviewRun(ctx context.Context, riderApplicationID pgtype.Int8) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, getLatestRiderOnboardingReviewRun, riderApplicationID)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOnboardingReviewRun = `-- name: GetOnboardingReviewRun :one
SELECT id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
FROM onboarding_review_runs
WHERE id = $1
`

func (q *Queries) GetOnboardingReviewRun(ctx context.Context, id int64) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, getOnboardingReviewRun, id)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQueuedOnboardingReviewRuns = `-- name: ListQueuedOnboardingReviewRuns :many
SELECT id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
FROM onboarding_review_runs
WHERE run_status = 'queued'
  AND (($1)::text = '' OR application_type = ($1)::text)
ORDER BY queued_at ASC, id ASC
LIMIT $3 OFFSET $2
`

type ListQueuedOnboardingReviewRunsParams struct {
	ApplicationType string `json:"application_type"`
	PageOffset      int32  `json:"page_offset"`
	PageLimit       int32  `json:"page_limit"`
}

func (q *Queries) ListQueuedOnboardingReviewRuns(ctx context.Context, arg ListQueuedOnboardingReviewRunsParams) ([]OnboardingReviewRun, error) {
	rows, err := q.db.Query(ctx, listQueuedOnboardingReviewRuns, arg.ApplicationType, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnboardingReviewRun{}
	for rows.Next() {
		var i OnboardingReviewRun
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationType,
			&i.MerchantApplicationID,
			&i.RiderApplicationID,
			&i.RunStatus,
			&i.Stage,
			&i.Outcome,
			&i.ReasonCode,
			&i.ReasonMessage,
			&i.Evidence,
			&i.RuleHits,
			&i.OcrJobRefs,
			&i.Snapshot,
			&i.RequestedBy,
			&i.ReviewedBy,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOnboardingReviewRunProcessing = `-- name: MarkOnboardingReviewRunProcessing :one
UPDATE onboarding_review_runs
SET run_status = 'processing',
    started_at = COALESCE(started_at, NOW()),
    updated_at = NOW()
WHERE id = $1
  AND run_status = 'queued'
RETURNING id, application_type, merchant_application_id, rider_application_id, run_status, stage, outcome, reason_code, reason_message, evidence, rule_hits, ocr_job_refs, snapshot, requested_by, reviewed_by, queued_at, started_at, finished_at, created_at, updated_at
`

func (q *Queries) MarkOnboardingReviewRunProcessing(ctx context.Context, id int64) (OnboardingReviewRun, error) {
	row := q.db.QueryRow(ctx, markOnboardingReviewRunProcessing, id)
	var i OnboardingReviewRun
	err := row.Scan(
		&i.ID,
		&i.ApplicationType,
		&i.MerchantApplicationID,
		&i.RiderApplicationID,
		&i.RunStatus,
		&i.Stage,
		&i.Outcome,
		&i.ReasonCode,
		&i.ReasonMessage,
		&i.Evidence,
		&i.RuleHits,
		&i.OcrJobRefs,
		&i.Snapshot,
		&i.RequestedBy,
		&i.ReviewedBy,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
