// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_item.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BatchCreateOrderItemsParams struct {
	OrderID        int64       `json:"order_id"`
	DishID         pgtype.Int8 `json:"dish_id"`
	ComboID        pgtype.Int8 `json:"combo_id"`
	Name           string      `json:"name"`
	UnitPrice      int64       `json:"unit_price"`
	Quantity       int16       `json:"quantity"`
	Subtotal       int64       `json:"subtotal"`
	Customizations []byte      `json:"customizations"`
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    order_id,
    dish_id,
    combo_id,
    name,
    unit_price,
    quantity,
    subtotal,
    customizations
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, order_id, dish_id, combo_id, name, unit_price, quantity, subtotal, customizations, created_at
`

type CreateOrderItemParams struct {
	OrderID        int64       `json:"order_id"`
	DishID         pgtype.Int8 `json:"dish_id"`
	ComboID        pgtype.Int8 `json:"combo_id"`
	Name           string      `json:"name"`
	UnitPrice      int64       `json:"unit_price"`
	Quantity       int16       `json:"quantity"`
	Subtotal       int64       `json:"subtotal"`
	Customizations []byte      `json:"customizations"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.DishID,
		arg.ComboID,
		arg.Name,
		arg.UnitPrice,
		arg.Quantity,
		arg.Subtotal,
		arg.Customizations,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.DishID,
		&i.ComboID,
		&i.Name,
		&i.UnitPrice,
		&i.Quantity,
		&i.Subtotal,
		&i.Customizations,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrderItems = `-- name: DeleteOrderItems :exec
DELETE FROM order_items
WHERE order_id = $1
`

func (q *Queries) DeleteOrderItems(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deleteOrderItems, orderID)
	return err
}

const getOrderItem = `-- name: GetOrderItem :one
SELECT id, order_id, dish_id, combo_id, name, unit_price, quantity, subtotal, customizations, created_at FROM order_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderItem(ctx context.Context, id int64) (OrderItem, error) {
	row := q.db.QueryRow(ctx, getOrderItem, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.DishID,
		&i.ComboID,
		&i.Name,
		&i.UnitPrice,
		&i.Quantity,
		&i.Subtotal,
		&i.Customizations,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, dish_id, combo_id, name, unit_price, quantity, subtotal, customizations, created_at FROM order_items
WHERE order_id = $1
ORDER BY id
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.DishID,
			&i.ComboID,
			&i.Name,
			&i.UnitPrice,
			&i.Quantity,
			&i.Subtotal,
			&i.Customizations,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsWithDishByOrder = `-- name: ListOrderItemsWithDishByOrder :many
SELECT 
    oi.id, oi.order_id, oi.dish_id, oi.combo_id, oi.name, oi.unit_price, oi.quantity, oi.subtotal, oi.customizations, oi.created_at,
    d.image_url as dish_image_url
FROM order_items oi
LEFT JOIN dishes d ON oi.dish_id = d.id
WHERE oi.order_id = $1
ORDER BY oi.id
`

type ListOrderItemsWithDishByOrderRow struct {
	ID             int64       `json:"id"`
	OrderID        int64       `json:"order_id"`
	DishID         pgtype.Int8 `json:"dish_id"`
	ComboID        pgtype.Int8 `json:"combo_id"`
	Name           string      `json:"name"`
	UnitPrice      int64       `json:"unit_price"`
	Quantity       int16       `json:"quantity"`
	Subtotal       int64       `json:"subtotal"`
	Customizations []byte      `json:"customizations"`
	CreatedAt      time.Time   `json:"created_at"`
	DishImageUrl   pgtype.Text `json:"dish_image_url"`
}

func (q *Queries) ListOrderItemsWithDishByOrder(ctx context.Context, orderID int64) ([]ListOrderItemsWithDishByOrderRow, error) {
	rows, err := q.db.Query(ctx, listOrderItemsWithDishByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderItemsWithDishByOrderRow{}
	for rows.Next() {
		var i ListOrderItemsWithDishByOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.DishID,
			&i.ComboID,
			&i.Name,
			&i.UnitPrice,
			&i.Quantity,
			&i.Subtotal,
			&i.Customizations,
			&i.CreatedAt,
			&i.DishImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
