// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_display_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderDisplayConfig = `-- name: CreateOrderDisplayConfig :one
INSERT INTO order_display_configs (
    merchant_id,
    enable_print,
    print_takeout,
    print_dine_in,
    print_reservation,
    print_dispatch_mode,
    print_trigger_mode,
    auto_accept_paid_orders,
    enable_voice,
    voice_takeout,
    voice_dine_in,
    enable_kds,
    kds_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, merchant_id, enable_print, print_takeout, print_dine_in, print_reservation, enable_voice, voice_takeout, voice_dine_in, enable_kds, kds_url, created_at, updated_at, print_dispatch_mode, print_trigger_mode, auto_accept_paid_orders
`

type CreateOrderDisplayConfigParams struct {
	MerchantID           int64       `json:"merchant_id"`
	EnablePrint          bool        `json:"enable_print"`
	PrintTakeout         bool        `json:"print_takeout"`
	PrintDineIn          bool        `json:"print_dine_in"`
	PrintReservation     bool        `json:"print_reservation"`
	PrintDispatchMode    string      `json:"print_dispatch_mode"`
	PrintTriggerMode     string      `json:"print_trigger_mode"`
	AutoAcceptPaidOrders bool        `json:"auto_accept_paid_orders"`
	EnableVoice          bool        `json:"enable_voice"`
	VoiceTakeout         bool        `json:"voice_takeout"`
	VoiceDineIn          bool        `json:"voice_dine_in"`
	EnableKds            bool        `json:"enable_kds"`
	KdsUrl               pgtype.Text `json:"kds_url"`
}

func (q *Queries) CreateOrderDisplayConfig(ctx context.Context, arg CreateOrderDisplayConfigParams) (OrderDisplayConfig, error) {
	row := q.db.QueryRow(ctx, createOrderDisplayConfig,
		arg.MerchantID,
		arg.EnablePrint,
		arg.PrintTakeout,
		arg.PrintDineIn,
		arg.PrintReservation,
		arg.PrintDispatchMode,
		arg.PrintTriggerMode,
		arg.AutoAcceptPaidOrders,
		arg.EnableVoice,
		arg.VoiceTakeout,
		arg.VoiceDineIn,
		arg.EnableKds,
		arg.KdsUrl,
	)
	var i OrderDisplayConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EnablePrint,
		&i.PrintTakeout,
		&i.PrintDineIn,
		&i.PrintReservation,
		&i.EnableVoice,
		&i.VoiceTakeout,
		&i.VoiceDineIn,
		&i.EnableKds,
		&i.KdsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrintDispatchMode,
		&i.PrintTriggerMode,
		&i.AutoAcceptPaidOrders,
	)
	return i, err
}

const getOrderDisplayConfig = `-- name: GetOrderDisplayConfig :one
SELECT id, merchant_id, enable_print, print_takeout, print_dine_in, print_reservation, enable_voice, voice_takeout, voice_dine_in, enable_kds, kds_url, created_at, updated_at, print_dispatch_mode, print_trigger_mode, auto_accept_paid_orders FROM order_display_configs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderDisplayConfig(ctx context.Context, id int64) (OrderDisplayConfig, error) {
	row := q.db.QueryRow(ctx, getOrderDisplayConfig, id)
	var i OrderDisplayConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EnablePrint,
		&i.PrintTakeout,
		&i.PrintDineIn,
		&i.PrintReservation,
		&i.EnableVoice,
		&i.VoiceTakeout,
		&i.VoiceDineIn,
		&i.EnableKds,
		&i.KdsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrintDispatchMode,
		&i.PrintTriggerMode,
		&i.AutoAcceptPaidOrders,
	)
	return i, err
}

const getOrderDisplayConfigByMerchant = `-- name: GetOrderDisplayConfigByMerchant :one
SELECT id, merchant_id, enable_print, print_takeout, print_dine_in, print_reservation, enable_voice, voice_takeout, voice_dine_in, enable_kds, kds_url, created_at, updated_at, print_dispatch_mode, print_trigger_mode, auto_accept_paid_orders FROM order_display_configs
WHERE merchant_id = $1 LIMIT 1
`

func (q *Queries) GetOrderDisplayConfigByMerchant(ctx context.Context, merchantID int64) (OrderDisplayConfig, error) {
	row := q.db.QueryRow(ctx, getOrderDisplayConfigByMerchant, merchantID)
	var i OrderDisplayConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EnablePrint,
		&i.PrintTakeout,
		&i.PrintDineIn,
		&i.PrintReservation,
		&i.EnableVoice,
		&i.VoiceTakeout,
		&i.VoiceDineIn,
		&i.EnableKds,
		&i.KdsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrintDispatchMode,
		&i.PrintTriggerMode,
		&i.AutoAcceptPaidOrders,
	)
	return i, err
}

const updateOrderDisplayConfig = `-- name: UpdateOrderDisplayConfig :one
UPDATE order_display_configs
SET
    enable_print = COALESCE($2, enable_print),
    print_takeout = COALESCE($3, print_takeout),
    print_dine_in = COALESCE($4, print_dine_in),
    print_reservation = COALESCE($5, print_reservation),
    print_dispatch_mode = COALESCE($6, print_dispatch_mode),
    print_trigger_mode = COALESCE($7, print_trigger_mode),
    auto_accept_paid_orders = COALESCE($8, auto_accept_paid_orders),
    enable_voice = COALESCE($9, enable_voice),
    voice_takeout = COALESCE($10, voice_takeout),
    voice_dine_in = COALESCE($11, voice_dine_in),
    enable_kds = COALESCE($12, enable_kds),
    kds_url = COALESCE($13, kds_url),
    updated_at = now()
WHERE merchant_id = $1
RETURNING id, merchant_id, enable_print, print_takeout, print_dine_in, print_reservation, enable_voice, voice_takeout, voice_dine_in, enable_kds, kds_url, created_at, updated_at, print_dispatch_mode, print_trigger_mode, auto_accept_paid_orders
`

type UpdateOrderDisplayConfigParams struct {
	MerchantID           int64       `json:"merchant_id"`
	EnablePrint          pgtype.Bool `json:"enable_print"`
	PrintTakeout         pgtype.Bool `json:"print_takeout"`
	PrintDineIn          pgtype.Bool `json:"print_dine_in"`
	PrintReservation     pgtype.Bool `json:"print_reservation"`
	PrintDispatchMode    pgtype.Text `json:"print_dispatch_mode"`
	PrintTriggerMode     pgtype.Text `json:"print_trigger_mode"`
	AutoAcceptPaidOrders pgtype.Bool `json:"auto_accept_paid_orders"`
	EnableVoice          pgtype.Bool `json:"enable_voice"`
	VoiceTakeout         pgtype.Bool `json:"voice_takeout"`
	VoiceDineIn          pgtype.Bool `json:"voice_dine_in"`
	EnableKds            pgtype.Bool `json:"enable_kds"`
	KdsUrl               pgtype.Text `json:"kds_url"`
}

func (q *Queries) UpdateOrderDisplayConfig(ctx context.Context, arg UpdateOrderDisplayConfigParams) (OrderDisplayConfig, error) {
	row := q.db.QueryRow(ctx, updateOrderDisplayConfig,
		arg.MerchantID,
		arg.EnablePrint,
		arg.PrintTakeout,
		arg.PrintDineIn,
		arg.PrintReservation,
		arg.PrintDispatchMode,
		arg.PrintTriggerMode,
		arg.AutoAcceptPaidOrders,
		arg.EnableVoice,
		arg.VoiceTakeout,
		arg.VoiceDineIn,
		arg.EnableKds,
		arg.KdsUrl,
	)
	var i OrderDisplayConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EnablePrint,
		&i.PrintTakeout,
		&i.PrintDineIn,
		&i.PrintReservation,
		&i.EnableVoice,
		&i.VoiceTakeout,
		&i.VoiceDineIn,
		&i.EnableKds,
		&i.KdsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrintDispatchMode,
		&i.PrintTriggerMode,
		&i.AutoAcceptPaidOrders,
	)
	return i, err
}

const upsertOrderDisplayConfig = `-- name: UpsertOrderDisplayConfig :one
INSERT INTO order_display_configs (
    merchant_id,
    enable_print,
    print_takeout,
    print_dine_in,
    print_reservation,
    print_dispatch_mode,
    print_trigger_mode,
    auto_accept_paid_orders,
    enable_voice,
    voice_takeout,
    voice_dine_in,
    enable_kds,
    kds_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (merchant_id) DO UPDATE SET
    enable_print = EXCLUDED.enable_print,
    print_takeout = EXCLUDED.print_takeout,
    print_dine_in = EXCLUDED.print_dine_in,
    print_reservation = EXCLUDED.print_reservation,
    print_dispatch_mode = EXCLUDED.print_dispatch_mode,
    print_trigger_mode = EXCLUDED.print_trigger_mode,
    auto_accept_paid_orders = EXCLUDED.auto_accept_paid_orders,
    enable_voice = EXCLUDED.enable_voice,
    voice_takeout = EXCLUDED.voice_takeout,
    voice_dine_in = EXCLUDED.voice_dine_in,
    enable_kds = EXCLUDED.enable_kds,
    kds_url = EXCLUDED.kds_url,
    updated_at = now()
RETURNING id, merchant_id, enable_print, print_takeout, print_dine_in, print_reservation, enable_voice, voice_takeout, voice_dine_in, enable_kds, kds_url, created_at, updated_at, print_dispatch_mode, print_trigger_mode, auto_accept_paid_orders
`

type UpsertOrderDisplayConfigParams struct {
	MerchantID           int64       `json:"merchant_id"`
	EnablePrint          bool        `json:"enable_print"`
	PrintTakeout         bool        `json:"print_takeout"`
	PrintDineIn          bool        `json:"print_dine_in"`
	PrintReservation     bool        `json:"print_reservation"`
	PrintDispatchMode    string      `json:"print_dispatch_mode"`
	PrintTriggerMode     string      `json:"print_trigger_mode"`
	AutoAcceptPaidOrders bool        `json:"auto_accept_paid_orders"`
	EnableVoice          bool        `json:"enable_voice"`
	VoiceTakeout         bool        `json:"voice_takeout"`
	VoiceDineIn          bool        `json:"voice_dine_in"`
	EnableKds            bool        `json:"enable_kds"`
	KdsUrl               pgtype.Text `json:"kds_url"`
}

func (q *Queries) UpsertOrderDisplayConfig(ctx context.Context, arg UpsertOrderDisplayConfigParams) (OrderDisplayConfig, error) {
	row := q.db.QueryRow(ctx, upsertOrderDisplayConfig,
		arg.MerchantID,
		arg.EnablePrint,
		arg.PrintTakeout,
		arg.PrintDineIn,
		arg.PrintReservation,
		arg.PrintDispatchMode,
		arg.PrintTriggerMode,
		arg.AutoAcceptPaidOrders,
		arg.EnableVoice,
		arg.VoiceTakeout,
		arg.VoiceDineIn,
		arg.EnableKds,
		arg.KdsUrl,
	)
	var i OrderDisplayConfig
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EnablePrint,
		&i.PrintTakeout,
		&i.PrintDineIn,
		&i.PrintReservation,
		&i.EnableVoice,
		&i.VoiceTakeout,
		&i.VoiceDineIn,
		&i.EnableKds,
		&i.KdsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PrintDispatchMode,
		&i.PrintTriggerMode,
		&i.AutoAcceptPaidOrders,
	)
	return i, err
}
