// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: peak_hour_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPeakHourConfig = `-- name: CreatePeakHourConfig :one
INSERT INTO peak_hour_configs (
  region_id,
  name,
  start_time,
  end_time,
  coefficient,
  days_of_week,
  is_active
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, region_id, name, start_time, end_time, coefficient, days_of_week, is_active, created_at, updated_at
`

type CreatePeakHourConfigParams struct {
	RegionID    int64          `json:"region_id"`
	Name        string         `json:"name"`
	StartTime   pgtype.Time    `json:"start_time"`
	EndTime     pgtype.Time    `json:"end_time"`
	Coefficient pgtype.Numeric `json:"coefficient"`
	DaysOfWeek  []int16        `json:"days_of_week"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreatePeakHourConfig(ctx context.Context, arg CreatePeakHourConfigParams) (PeakHourConfig, error) {
	row := q.db.QueryRow(ctx, createPeakHourConfig,
		arg.RegionID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.Coefficient,
		arg.DaysOfWeek,
		arg.IsActive,
	)
	var i PeakHourConfig
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.Coefficient,
		&i.DaysOfWeek,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePeakHourConfig = `-- name: DeletePeakHourConfig :exec
DELETE FROM peak_hour_configs
WHERE id = $1
`

func (q *Queries) DeletePeakHourConfig(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePeakHourConfig, id)
	return err
}

const deletePeakHourConfigsByRegion = `-- name: DeletePeakHourConfigsByRegion :exec
DELETE FROM peak_hour_configs
WHERE region_id = $1
`

func (q *Queries) DeletePeakHourConfigsByRegion(ctx context.Context, regionID int64) error {
	_, err := q.db.Exec(ctx, deletePeakHourConfigsByRegion, regionID)
	return err
}

const getPeakHourConfig = `-- name: GetPeakHourConfig :one
SELECT id, region_id, name, start_time, end_time, coefficient, days_of_week, is_active, created_at, updated_at FROM peak_hour_configs
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPeakHourConfig(ctx context.Context, id int64) (PeakHourConfig, error) {
	row := q.db.QueryRow(ctx, getPeakHourConfig, id)
	var i PeakHourConfig
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.Coefficient,
		&i.DaysOfWeek,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePeakHourConfigsByRegion = `-- name: ListActivePeakHourConfigsByRegion :many
SELECT id, region_id, name, start_time, end_time, coefficient, days_of_week, is_active, created_at, updated_at FROM peak_hour_configs
WHERE region_id = $1 AND is_active = true
ORDER BY start_time
`

func (q *Queries) ListActivePeakHourConfigsByRegion(ctx context.Context, regionID int64) ([]PeakHourConfig, error) {
	rows, err := q.db.Query(ctx, listActivePeakHourConfigsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeakHourConfig{}
	for rows.Next() {
		var i PeakHourConfig
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.Coefficient,
			&i.DaysOfWeek,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeakHourConfigsByRegion = `-- name: ListPeakHourConfigsByRegion :many
SELECT id, region_id, name, start_time, end_time, coefficient, days_of_week, is_active, created_at, updated_at FROM peak_hour_configs
WHERE region_id = $1
ORDER BY start_time
`

func (q *Queries) ListPeakHourConfigsByRegion(ctx context.Context, regionID int64) ([]PeakHourConfig, error) {
	rows, err := q.db.Query(ctx, listPeakHourConfigsByRegion, regionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeakHourConfig{}
	for rows.Next() {
		var i PeakHourConfig
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.Coefficient,
			&i.DaysOfWeek,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePeakHourConfig = `-- name: UpdatePeakHourConfig :one
UPDATE peak_hour_configs
SET
  name = COALESCE($2, name),
  start_time = COALESCE($3, start_time),
  end_time = COALESCE($4, end_time),
  coefficient = COALESCE($5, coefficient),
  days_of_week = COALESCE($6, days_of_week),
  is_active = COALESCE($7, is_active),
  updated_at = now()
WHERE id = $1
RETURNING id, region_id, name, start_time, end_time, coefficient, days_of_week, is_active, created_at, updated_at
`

type UpdatePeakHourConfigParams struct {
	ID          int64          `json:"id"`
	Name        pgtype.Text    `json:"name"`
	StartTime   pgtype.Time    `json:"start_time"`
	EndTime     pgtype.Time    `json:"end_time"`
	Coefficient pgtype.Numeric `json:"coefficient"`
	DaysOfWeek  []int16        `json:"days_of_week"`
	IsActive    pgtype.Bool    `json:"is_active"`
}

func (q *Queries) UpdatePeakHourConfig(ctx context.Context, arg UpdatePeakHourConfigParams) (PeakHourConfig, error) {
	row := q.db.QueryRow(ctx, updatePeakHourConfig,
		arg.ID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.Coefficient,
		arg.DaysOfWeek,
		arg.IsActive,
	)
	var i PeakHourConfig
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.Coefficient,
		&i.DaysOfWeek,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
