// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_operator_rule.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformOperatorRuleBaselineFromOperator = `-- name: GetPlatformOperatorRuleBaselineFromOperator :one
SELECT
  commission_rate,
  merchant_deposit,
  rider_deposit
FROM operators
ORDER BY id
LIMIT 1
`

type GetPlatformOperatorRuleBaselineFromOperatorRow struct {
	CommissionRate  pgtype.Numeric `json:"commission_rate"`
	MerchantDeposit int64          `json:"merchant_deposit"`
	RiderDeposit    int64          `json:"rider_deposit"`
}

func (q *Queries) GetPlatformOperatorRuleBaselineFromOperator(ctx context.Context) (GetPlatformOperatorRuleBaselineFromOperatorRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOperatorRuleBaselineFromOperator)
	var i GetPlatformOperatorRuleBaselineFromOperatorRow
	err := row.Scan(&i.CommissionRate, &i.MerchantDeposit, &i.RiderDeposit)
	return i, err
}

const getPlatformOperatorRuleBaselineFromRegion = `-- name: GetPlatformOperatorRuleBaselineFromRegion :one
SELECT
  commission_rate,
  merchant_deposit,
  rider_deposit
FROM region_rule_configs
ORDER BY id
LIMIT 1
`

type GetPlatformOperatorRuleBaselineFromRegionRow struct {
	CommissionRate  pgtype.Numeric `json:"commission_rate"`
	MerchantDeposit int64          `json:"merchant_deposit"`
	RiderDeposit    int64          `json:"rider_deposit"`
}

func (q *Queries) GetPlatformOperatorRuleBaselineFromRegion(ctx context.Context) (GetPlatformOperatorRuleBaselineFromRegionRow, error) {
	row := q.db.QueryRow(ctx, getPlatformOperatorRuleBaselineFromRegion)
	var i GetPlatformOperatorRuleBaselineFromRegionRow
	err := row.Scan(&i.CommissionRate, &i.MerchantDeposit, &i.RiderDeposit)
	return i, err
}

const updateAllOperatorsCommissionRate = `-- name: UpdateAllOperatorsCommissionRate :exec
UPDATE operators
SET
  commission_rate = $1,
  updated_at = NOW()
`

func (q *Queries) UpdateAllOperatorsCommissionRate(ctx context.Context, commissionRate pgtype.Numeric) error {
	_, err := q.db.Exec(ctx, updateAllOperatorsCommissionRate, commissionRate)
	return err
}

const updateAllOperatorsMerchantDeposit = `-- name: UpdateAllOperatorsMerchantDeposit :exec
UPDATE operators
SET
  merchant_deposit = $1,
  updated_at = NOW()
`

func (q *Queries) UpdateAllOperatorsMerchantDeposit(ctx context.Context, merchantDeposit int64) error {
	_, err := q.db.Exec(ctx, updateAllOperatorsMerchantDeposit, merchantDeposit)
	return err
}

const updateAllOperatorsRiderDeposit = `-- name: UpdateAllOperatorsRiderDeposit :exec
UPDATE operators
SET
  rider_deposit = $1,
  updated_at = NOW()
`

func (q *Queries) UpdateAllOperatorsRiderDeposit(ctx context.Context, riderDeposit int64) error {
	_, err := q.db.Exec(ctx, updateAllOperatorsRiderDeposit, riderDeposit)
	return err
}

const updateAllRegionRuleConfigCommissionRate = `-- name: UpdateAllRegionRuleConfigCommissionRate :exec
UPDATE region_rule_configs
SET
  commission_rate = $1,
  updated_at = NOW()
`

func (q *Queries) UpdateAllRegionRuleConfigCommissionRate(ctx context.Context, commissionRate pgtype.Numeric) error {
	_, err := q.db.Exec(ctx, updateAllRegionRuleConfigCommissionRate, commissionRate)
	return err
}

const updateAllRegionRuleConfigMerchantDeposit = `-- name: UpdateAllRegionRuleConfigMerchantDeposit :exec
UPDATE region_rule_configs
SET
  merchant_deposit = $1,
  updated_at = NOW()
`

func (q *Queries) UpdateAllRegionRuleConfigMerchantDeposit(ctx context.Context, merchantDeposit int64) error {
	_, err := q.db.Exec(ctx, updateAllRegionRuleConfigMerchantDeposit, merchantDeposit)
	return err
}

const updateAllRegionRuleConfigRiderDeposit = `-- name: UpdateAllRegionRuleConfigRiderDeposit :exec
UPDATE region_rule_configs
SET
  rider_deposit = $1,
  updated_at = NOW()
`

func (q *Queries) UpdateAllRegionRuleConfigRiderDeposit(ctx context.Context, riderDeposit int64) error {
	_, err := q.db.Exec(ctx, updateAllRegionRuleConfigRiderDeposit, riderDeposit)
	return err
}
