// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_alert_event.sql

package db

import (
	"context"
	"time"
)

const countPlatformAlertEvents = `-- name: CountPlatformAlertEvents :one
SELECT COUNT(*) FROM platform_alert_events
`

func (q *Queries) CountPlatformAlertEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatformAlertEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformAlertEvent = `-- name: CreatePlatformAlertEvent :one
INSERT INTO platform_alert_events (
  alert_type,
  level,
  title,
  message,
  related_id,
  related_type,
  extra,
  emitted_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, alert_type, level, title, message, related_id, related_type, extra, emitted_at
`

type CreatePlatformAlertEventParams struct {
	AlertType   string    `json:"alert_type"`
	Level       string    `json:"level"`
	Title       string    `json:"title"`
	Message     string    `json:"message"`
	RelatedID   int64     `json:"related_id"`
	RelatedType string    `json:"related_type"`
	Extra       []byte    `json:"extra"`
	EmittedAt   time.Time `json:"emitted_at"`
}

func (q *Queries) CreatePlatformAlertEvent(ctx context.Context, arg CreatePlatformAlertEventParams) (PlatformAlertEvent, error) {
	row := q.db.QueryRow(ctx, createPlatformAlertEvent,
		arg.AlertType,
		arg.Level,
		arg.Title,
		arg.Message,
		arg.RelatedID,
		arg.RelatedType,
		arg.Extra,
		arg.EmittedAt,
	)
	var i PlatformAlertEvent
	err := row.Scan(
		&i.ID,
		&i.AlertType,
		&i.Level,
		&i.Title,
		&i.Message,
		&i.RelatedID,
		&i.RelatedType,
		&i.Extra,
		&i.EmittedAt,
	)
	return i, err
}

const listPlatformAlertEvents = `-- name: ListPlatformAlertEvents :many
SELECT id, alert_type, level, title, message, related_id, related_type, extra, emitted_at FROM platform_alert_events
ORDER BY emitted_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListPlatformAlertEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPlatformAlertEvents(ctx context.Context, arg ListPlatformAlertEventsParams) ([]PlatformAlertEvent, error) {
	rows, err := q.db.Query(ctx, listPlatformAlertEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAlertEvent{}
	for rows.Next() {
		var i PlatformAlertEvent
		if err := rows.Scan(
			&i.ID,
			&i.AlertType,
			&i.Level,
			&i.Title,
			&i.Message,
			&i.RelatedID,
			&i.RelatedType,
			&i.Extra,
			&i.EmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
