// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refund_order.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefundOrder = `-- name: CreateRefundOrder :one
INSERT INTO refund_orders (
    payment_order_id,
    refund_type,
    refund_amount,
    refund_reason,
    out_refund_no,
    platform_refund,
    operator_refund,
    merchant_refund,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at
`

type CreateRefundOrderParams struct {
	PaymentOrderID int64       `json:"payment_order_id"`
	RefundType     string      `json:"refund_type"`
	RefundAmount   int64       `json:"refund_amount"`
	RefundReason   pgtype.Text `json:"refund_reason"`
	OutRefundNo    string      `json:"out_refund_no"`
	PlatformRefund pgtype.Int8 `json:"platform_refund"`
	OperatorRefund pgtype.Int8 `json:"operator_refund"`
	MerchantRefund pgtype.Int8 `json:"merchant_refund"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateRefundOrder(ctx context.Context, arg CreateRefundOrderParams) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, createRefundOrder,
		arg.PaymentOrderID,
		arg.RefundType,
		arg.RefundAmount,
		arg.RefundReason,
		arg.OutRefundNo,
		arg.PlatformRefund,
		arg.OperatorRefund,
		arg.MerchantRefund,
		arg.Status,
	)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingRiderDepositRefundAmountByUserID = `-- name: GetPendingRiderDepositRefundAmountByUserID :one
SELECT COALESCE(SUM(ro.refund_amount), 0)::bigint AS pending_rider_deposit_refund_amount
FROM refund_orders ro
JOIN payment_orders po ON po.id = ro.payment_order_id
WHERE po.user_id = $1
    AND po.business_type = 'rider_deposit'
    AND ro.refund_type = 'rider_deposit'
    AND ro.status IN ('pending', 'processing')
`

func (q *Queries) GetPendingRiderDepositRefundAmountByUserID(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getPendingRiderDepositRefundAmountByUserID, userID)
	var pending_rider_deposit_refund_amount int64
	err := row.Scan(&pending_rider_deposit_refund_amount)
	return pending_rider_deposit_refund_amount, err
}

const getRefundOrder = `-- name: GetRefundOrder :one
SELECT id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at FROM refund_orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRefundOrder(ctx context.Context, id int64) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, getRefundOrder, id)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefundOrderByOutRefundNo = `-- name: GetRefundOrderByOutRefundNo :one
SELECT id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at FROM refund_orders
WHERE out_refund_no = $1 LIMIT 1
`

func (q *Queries) GetRefundOrderByOutRefundNo(ctx context.Context, outRefundNo string) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, getRefundOrderByOutRefundNo, outRefundNo)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefundOrderByRefundId = `-- name: GetRefundOrderByRefundId :one
SELECT id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at FROM refund_orders
WHERE refund_id = $1 LIMIT 1
`

func (q *Queries) GetRefundOrderByRefundId(ctx context.Context, refundID pgtype.Text) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, getRefundOrderByRefundId, refundID)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefundOrderForUpdate = `-- name: GetRefundOrderForUpdate :one
SELECT id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at FROM refund_orders
WHERE id = $1 LIMIT 1
FOR UPDATE
`

func (q *Queries) GetRefundOrderForUpdate(ctx context.Context, id int64) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, getRefundOrderForUpdate, id)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalRefundedByPaymentOrder = `-- name: GetTotalRefundedByPaymentOrder :one
SELECT COALESCE(SUM(refund_amount), 0)::bigint as total_refunded
FROM refund_orders
WHERE payment_order_id = $1 AND status IN ('pending', 'processing', 'success')
`

func (q *Queries) GetTotalRefundedByPaymentOrder(ctx context.Context, paymentOrderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalRefundedByPaymentOrder, paymentOrderID)
	var total_refunded int64
	err := row.Scan(&total_refunded)
	return total_refunded, err
}

const listEcommerceRefundOrdersForReconciliation = `-- name: ListEcommerceRefundOrdersForReconciliation :many
SELECT r.id, r.out_refund_no, r.refund_id, r.refund_amount, r.status
FROM refund_orders r
JOIN payment_orders p ON p.id = r.payment_order_id
WHERE r.status = 'success'
  AND r.refunded_at >= $1
  AND r.refunded_at < $2
    AND p.payment_channel = 'ecommerce'
`

type ListEcommerceRefundOrdersForReconciliationParams struct {
	RefundedAt   pgtype.Timestamptz `json:"refunded_at"`
	RefundedAt_2 pgtype.Timestamptz `json:"refunded_at_2"`
}

type ListEcommerceRefundOrdersForReconciliationRow struct {
	ID           int64       `json:"id"`
	OutRefundNo  string      `json:"out_refund_no"`
	RefundID     pgtype.Text `json:"refund_id"`
	RefundAmount int64       `json:"refund_amount"`
	Status       string      `json:"status"`
}

// 获取指定日期范围内收付通退款成功记录（payment_channel='ecommerce'）
// 对应微信 /v3/ecommerce/refunds/apply 产生的退款账单
func (q *Queries) ListEcommerceRefundOrdersForReconciliation(ctx context.Context, arg ListEcommerceRefundOrdersForReconciliationParams) ([]ListEcommerceRefundOrdersForReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listEcommerceRefundOrdersForReconciliation, arg.RefundedAt, arg.RefundedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEcommerceRefundOrdersForReconciliationRow{}
	for rows.Next() {
		var i ListEcommerceRefundOrdersForReconciliationRow
		if err := rows.Scan(
			&i.ID,
			&i.OutRefundNo,
			&i.RefundID,
			&i.RefundAmount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingReservationRefundOrdersForRecovery = `-- name: ListPendingReservationRefundOrdersForRecovery :many
SELECT
    ro.id,
    ro.payment_order_id,
    ro.refund_amount,
    ro.refund_reason,
    ro.out_refund_no,
    po.reservation_id,
    po.business_type
FROM refund_orders ro
JOIN payment_orders po ON po.id = ro.payment_order_id
WHERE ro.status = 'pending'
    AND po.status = 'paid'
    AND po.reservation_id IS NOT NULL
    AND po.business_type IN ('reservation', 'reservation_addon')
    AND ro.created_at < $1
ORDER BY ro.created_at ASC
LIMIT $2::int
`

type ListPendingReservationRefundOrdersForRecoveryParams struct {
	CreatedBefore time.Time `json:"created_before"`
	Limit         int32     `json:"limit"`
}

type ListPendingReservationRefundOrdersForRecoveryRow struct {
	ID             int64       `json:"id"`
	PaymentOrderID int64       `json:"payment_order_id"`
	RefundAmount   int64       `json:"refund_amount"`
	RefundReason   pgtype.Text `json:"refund_reason"`
	OutRefundNo    string      `json:"out_refund_no"`
	ReservationID  pgtype.Int8 `json:"reservation_id"`
	BusinessType   string      `json:"business_type"`
}

func (q *Queries) ListPendingReservationRefundOrdersForRecovery(ctx context.Context, arg ListPendingReservationRefundOrdersForRecoveryParams) ([]ListPendingReservationRefundOrdersForRecoveryRow, error) {
	rows, err := q.db.Query(ctx, listPendingReservationRefundOrdersForRecovery, arg.CreatedBefore, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingReservationRefundOrdersForRecoveryRow{}
	for rows.Next() {
		var i ListPendingReservationRefundOrdersForRecoveryRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentOrderID,
			&i.RefundAmount,
			&i.RefundReason,
			&i.OutRefundNo,
			&i.ReservationID,
			&i.BusinessType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundOrdersByPaymentOrder = `-- name: ListRefundOrdersByPaymentOrder :many
SELECT id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at FROM refund_orders
WHERE payment_order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListRefundOrdersByPaymentOrder(ctx context.Context, paymentOrderID int64) ([]RefundOrder, error) {
	rows, err := q.db.Query(ctx, listRefundOrdersByPaymentOrder, paymentOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundOrder{}
	for rows.Next() {
		var i RefundOrder
		if err := rows.Scan(
			&i.ID,
			&i.PaymentOrderID,
			&i.RefundType,
			&i.RefundAmount,
			&i.RefundReason,
			&i.OutRefundNo,
			&i.RefundID,
			&i.PlatformRefund,
			&i.OperatorRefund,
			&i.MerchantRefund,
			&i.Status,
			&i.RefundedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundOrdersByStatus = `-- name: ListRefundOrdersByStatus :many
SELECT id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at FROM refund_orders
WHERE status = $1
ORDER BY created_at
LIMIT $2 OFFSET $3
`

type ListRefundOrdersByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRefundOrdersByStatus(ctx context.Context, arg ListRefundOrdersByStatusParams) ([]RefundOrder, error) {
	rows, err := q.db.Query(ctx, listRefundOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundOrder{}
	for rows.Next() {
		var i RefundOrder
		if err := rows.Scan(
			&i.ID,
			&i.PaymentOrderID,
			&i.RefundType,
			&i.RefundAmount,
			&i.RefundReason,
			&i.OutRefundNo,
			&i.RefundID,
			&i.PlatformRefund,
			&i.OperatorRefund,
			&i.MerchantRefund,
			&i.Status,
			&i.RefundedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRefundOrdersForReconciliation = `-- name: ListRefundOrdersForReconciliation :many
SELECT r.id, r.out_refund_no, r.refund_id, r.refund_amount, r.status
FROM refund_orders r
JOIN payment_orders p ON p.id = r.payment_order_id
WHERE r.status = 'success'
  AND r.refunded_at >= $1
  AND r.refunded_at < $2
    AND p.payment_channel = 'direct'
`

type ListRefundOrdersForReconciliationParams struct {
	RefundedAt   pgtype.Timestamptz `json:"refunded_at"`
	RefundedAt_2 pgtype.Timestamptz `json:"refunded_at_2"`
}

type ListRefundOrdersForReconciliationRow struct {
	ID           int64       `json:"id"`
	OutRefundNo  string      `json:"out_refund_no"`
	RefundID     pgtype.Text `json:"refund_id"`
	RefundAmount int64       `json:"refund_amount"`
	Status       string      `json:"status"`
}

// 获取指定日期范围内直连支付（miniprogram/deposit等）成功退款订单（用于每日对账）
// 通过 JOIN payment_orders 过滤 payment_channel，排除收付通退款（已单独对账）
func (q *Queries) ListRefundOrdersForReconciliation(ctx context.Context, arg ListRefundOrdersForReconciliationParams) ([]ListRefundOrdersForReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listRefundOrdersForReconciliation, arg.RefundedAt, arg.RefundedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRefundOrdersForReconciliationRow{}
	for rows.Next() {
		var i ListRefundOrdersForReconciliationRow
		if err := rows.Scan(
			&i.ID,
			&i.OutRefundNo,
			&i.RefundID,
			&i.RefundAmount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckProcessingRefundOrders = `-- name: ListStuckProcessingRefundOrders :many
SELECT ro.id, ro.out_refund_no, ro.refund_id, ro.refund_amount, ro.status, ro.created_at,
       po.payment_type
FROM refund_orders ro
JOIN payment_orders po ON po.id = ro.payment_order_id
WHERE ro.status = 'processing'
  AND ro.created_at < $1
ORDER BY ro.created_at ASC
LIMIT $2::int
`

type ListStuckProcessingRefundOrdersParams struct {
	CreatedBefore time.Time `json:"created_before"`
	Limit         int32     `json:"limit"`
}

type ListStuckProcessingRefundOrdersRow struct {
	ID           int64       `json:"id"`
	OutRefundNo  string      `json:"out_refund_no"`
	RefundID     pgtype.Text `json:"refund_id"`
	RefundAmount int64       `json:"refund_amount"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	PaymentType  string      `json:"payment_type"`
}

// 查找持续处于 processing 状态超过阈值时间的退款单（微信回调可能永久丢失）
// 用于运营告警，让人工核查微信商户平台退款结果
func (q *Queries) ListStuckProcessingRefundOrders(ctx context.Context, arg ListStuckProcessingRefundOrdersParams) ([]ListStuckProcessingRefundOrdersRow, error) {
	rows, err := q.db.Query(ctx, listStuckProcessingRefundOrders, arg.CreatedBefore, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStuckProcessingRefundOrdersRow{}
	for rows.Next() {
		var i ListStuckProcessingRefundOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OutRefundNo,
			&i.RefundID,
			&i.RefundAmount,
			&i.Status,
			&i.CreatedAt,
			&i.PaymentType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRefundOrderToClosed = `-- name: UpdateRefundOrderToClosed :one
UPDATE refund_orders
SET
    status = 'closed'
WHERE id = $1 AND status IN ('pending', 'processing')
RETURNING id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at
`

func (q *Queries) UpdateRefundOrderToClosed(ctx context.Context, id int64) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, updateRefundOrderToClosed, id)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRefundOrderToFailed = `-- name: UpdateRefundOrderToFailed :one
UPDATE refund_orders
SET
    status = 'failed'
WHERE id = $1
RETURNING id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at
`

func (q *Queries) UpdateRefundOrderToFailed(ctx context.Context, id int64) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, updateRefundOrderToFailed, id)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRefundOrderToProcessing = `-- name: UpdateRefundOrderToProcessing :one
UPDATE refund_orders
SET
    status = 'processing',
    refund_id = $2
WHERE id = $1 AND status = 'pending'
RETURNING id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at
`

type UpdateRefundOrderToProcessingParams struct {
	ID       int64       `json:"id"`
	RefundID pgtype.Text `json:"refund_id"`
}

func (q *Queries) UpdateRefundOrderToProcessing(ctx context.Context, arg UpdateRefundOrderToProcessingParams) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, updateRefundOrderToProcessing, arg.ID, arg.RefundID)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateRefundOrderToSuccess = `-- name: UpdateRefundOrderToSuccess :one
UPDATE refund_orders
SET
    status = 'success',
    refunded_at = now()
WHERE id = $1 AND status IN ('pending', 'processing')
RETURNING id, payment_order_id, refund_type, refund_amount, refund_reason, out_refund_no, refund_id, platform_refund, operator_refund, merchant_refund, status, refunded_at, created_at
`

func (q *Queries) UpdateRefundOrderToSuccess(ctx context.Context, id int64) (RefundOrder, error) {
	row := q.db.QueryRow(ctx, updateRefundOrderToSuccess, id)
	var i RefundOrder
	err := row.Scan(
		&i.ID,
		&i.PaymentOrderID,
		&i.RefundType,
		&i.RefundAmount,
		&i.RefundReason,
		&i.OutRefundNo,
		&i.RefundID,
		&i.PlatformRefund,
		&i.OperatorRefund,
		&i.MerchantRefund,
		&i.Status,
		&i.RefundedAt,
		&i.CreatedAt,
	)
	return i, err
}
