// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addReviewImage = `-- name: AddReviewImage :one
INSERT INTO review_images (review_id, media_asset_id, sort_order)
VALUES ($1, $2, $3)
RETURNING id, review_id, media_asset_id, sort_order, created_at
`

type AddReviewImageParams struct {
	ReviewID     int64 `json:"review_id"`
	MediaAssetID int64 `json:"media_asset_id"`
	SortOrder    int32 `json:"sort_order"`
}

func (q *Queries) AddReviewImage(ctx context.Context, arg AddReviewImageParams) (ReviewImage, error) {
	row := q.db.QueryRow(ctx, addReviewImage, arg.ReviewID, arg.MediaAssetID, arg.SortOrder)
	var i ReviewImage
	err := row.Scan(
		&i.ID,
		&i.ReviewID,
		&i.MediaAssetID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const countAllReviewsByMerchant = `-- name: CountAllReviewsByMerchant :one
SELECT COUNT(*) FROM reviews
WHERE merchant_id = $1
`

// 商户查看所有评价数量（包含不可见的）
func (q *Queries) CountAllReviewsByMerchant(ctx context.Context, merchantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAllReviewsByMerchant, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByMerchant = `-- name: CountReviewsByMerchant :one
SELECT COUNT(*) FROM reviews
WHERE merchant_id = $1
  AND is_visible = true
`

func (q *Queries) CountReviewsByMerchant(ctx context.Context, merchantID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByMerchant, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByUser = `-- name: CountReviewsByUser :one
SELECT COUNT(*) FROM reviews
WHERE user_id = $1
`

func (q *Queries) CountReviewsByUser(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (
  order_id,
  user_id,
  merchant_id,
  content,
  is_visible
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at
`

type CreateReviewParams struct {
	OrderID    int64  `json:"order_id"`
	UserID     int64  `json:"user_id"`
	MerchantID int64  `json:"merchant_id"`
	Content    string `json:"content"`
	IsVisible  bool   `json:"is_visible"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.OrderID,
		arg.UserID,
		arg.MerchantID,
		arg.Content,
		arg.IsVisible,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.Content,
		&i.IsVisible,
		&i.MerchantReply,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM reviews
WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const deleteReviewImages = `-- name: DeleteReviewImages :exec
DELETE FROM review_images
WHERE review_id = $1
`

func (q *Queries) DeleteReviewImages(ctx context.Context, reviewID int64) error {
	_, err := q.db.Exec(ctx, deleteReviewImages, reviewID)
	return err
}

const getReview = `-- name: GetReview :one
SELECT id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at FROM reviews
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReview(ctx context.Context, id int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReview, id)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.Content,
		&i.IsVisible,
		&i.MerchantReply,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewByOrderID = `-- name: GetReviewByOrderID :one
SELECT id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at FROM reviews
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetReviewByOrderID(ctx context.Context, orderID int64) (Review, error) {
	row := q.db.QueryRow(ctx, getReviewByOrderID, orderID)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.Content,
		&i.IsVisible,
		&i.MerchantReply,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listAllReviewsByMerchant = `-- name: ListAllReviewsByMerchant :many
SELECT id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at FROM reviews
WHERE merchant_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListAllReviewsByMerchantParams struct {
	MerchantID int64 `json:"merchant_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

// 商户查看所有评价（包含不可见的）
func (q *Queries) ListAllReviewsByMerchant(ctx context.Context, arg ListAllReviewsByMerchantParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listAllReviewsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.MerchantID,
			&i.Content,
			&i.IsVisible,
			&i.MerchantReply,
			&i.RepliedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewImages = `-- name: ListReviewImages :many
SELECT id, review_id, media_asset_id, sort_order, created_at FROM review_images
WHERE review_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListReviewImages(ctx context.Context, reviewID int64) ([]ReviewImage, error) {
	rows, err := q.db.Query(ctx, listReviewImages, reviewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewImage{}
	for rows.Next() {
		var i ReviewImage
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.MediaAssetID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewImagesByReviews = `-- name: ListReviewImagesByReviews :many
SELECT id, review_id, media_asset_id, sort_order, created_at FROM review_images
WHERE review_id = ANY($1::bigint[])
ORDER BY review_id, sort_order ASC
`

func (q *Queries) ListReviewImagesByReviews(ctx context.Context, dollar_1 []int64) ([]ReviewImage, error) {
	rows, err := q.db.Query(ctx, listReviewImagesByReviews, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewImage{}
	for rows.Next() {
		var i ReviewImage
		if err := rows.Scan(
			&i.ID,
			&i.ReviewID,
			&i.MediaAssetID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByMerchant = `-- name: ListReviewsByMerchant :many
SELECT id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at FROM reviews
WHERE merchant_id = $1
  AND is_visible = true
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByMerchantParams struct {
	MerchantID int64 `json:"merchant_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListReviewsByMerchant(ctx context.Context, arg ListReviewsByMerchantParams) ([]Review, error) {
	rows, err := q.db.Query(ctx, listReviewsByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Review{}
	for rows.Next() {
		var i Review
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.MerchantID,
			&i.Content,
			&i.IsVisible,
			&i.MerchantReply,
			&i.RepliedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByUser = `-- name: ListReviewsByUser :many
SELECT r.id, r.order_id, r.user_id, r.merchant_id, r.content, r.is_visible, r.merchant_reply, r.replied_at, r.created_at, m.name as merchant_name, m.logo_media_asset_id as merchant_logo_media_asset_id
FROM reviews r
JOIN merchants m ON r.merchant_id = m.id
WHERE r.user_id = $1
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2 OFFSET $3
`

type ListReviewsByUserParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListReviewsByUserRow struct {
	ID                       int64              `json:"id"`
	OrderID                  int64              `json:"order_id"`
	UserID                   int64              `json:"user_id"`
	MerchantID               int64              `json:"merchant_id"`
	Content                  string             `json:"content"`
	IsVisible                bool               `json:"is_visible"`
	MerchantReply            pgtype.Text        `json:"merchant_reply"`
	RepliedAt                pgtype.Timestamptz `json:"replied_at"`
	CreatedAt                time.Time          `json:"created_at"`
	MerchantName             string             `json:"merchant_name"`
	MerchantLogoMediaAssetID pgtype.Int8        `json:"merchant_logo_media_asset_id"`
}

func (q *Queries) ListReviewsByUser(ctx context.Context, arg ListReviewsByUserParams) ([]ListReviewsByUserRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByUserRow{}
	for rows.Next() {
		var i ListReviewsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.MerchantID,
			&i.Content,
			&i.IsVisible,
			&i.MerchantReply,
			&i.RepliedAt,
			&i.CreatedAt,
			&i.MerchantName,
			&i.MerchantLogoMediaAssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantReply = `-- name: UpdateMerchantReply :one
UPDATE reviews
SET merchant_reply = $2,
    replied_at = now()
WHERE id = $1
RETURNING id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at
`

type UpdateMerchantReplyParams struct {
	ID            int64       `json:"id"`
	MerchantReply pgtype.Text `json:"merchant_reply"`
}

func (q *Queries) UpdateMerchantReply(ctx context.Context, arg UpdateMerchantReplyParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateMerchantReply, arg.ID, arg.MerchantReply)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.Content,
		&i.IsVisible,
		&i.MerchantReply,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateReviewContent = `-- name: UpdateReviewContent :one
UPDATE reviews
SET content = $2
WHERE id = $1
RETURNING id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at
`

type UpdateReviewContentParams struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateReviewContent(ctx context.Context, arg UpdateReviewContentParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewContent, arg.ID, arg.Content)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.Content,
		&i.IsVisible,
		&i.MerchantReply,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateReviewVisibility = `-- name: UpdateReviewVisibility :one
UPDATE reviews
SET is_visible = $2
WHERE id = $1
RETURNING id, order_id, user_id, merchant_id, content, is_visible, merchant_reply, replied_at, created_at
`

type UpdateReviewVisibilityParams struct {
	ID        int64 `json:"id"`
	IsVisible bool  `json:"is_visible"`
}

func (q *Queries) UpdateReviewVisibility(ctx context.Context, arg UpdateReviewVisibilityParams) (Review, error) {
	row := q.db.QueryRow(ctx, updateReviewVisibility, arg.ID, arg.IsVisible)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.MerchantID,
		&i.Content,
		&i.IsVisible,
		&i.MerchantReply,
		&i.RepliedAt,
		&i.CreatedAt,
	)
	return i, err
}
