// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules_read.sql

package db

import (
	"context"
)

const getRule = `-- name: GetRule :one
SELECT id, name, category, status, current_version_id, created_by, created_at, updated_at FROM rules WHERE id = $1
`

func (q *Queries) GetRule(ctx context.Context, id int64) (Rule, error) {
	row := q.db.QueryRow(ctx, getRule, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Status,
		&i.CurrentVersionID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuleVersion = `-- name: GetRuleVersion :one
SELECT id, rule_id, version, status, priority, scope, condition, action, gray_config, effective_at, expires_at, created_by, created_at FROM rule_versions WHERE id = $1
`

func (q *Queries) GetRuleVersion(ctx context.Context, id int64) (RuleVersion, error) {
	row := q.db.QueryRow(ctx, getRuleVersion, id)
	var i RuleVersion
	err := row.Scan(
		&i.ID,
		&i.RuleID,
		&i.Version,
		&i.Status,
		&i.Priority,
		&i.Scope,
		&i.Condition,
		&i.Action,
		&i.GrayConfig,
		&i.EffectiveAt,
		&i.ExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listRuleVersionsByRule = `-- name: ListRuleVersionsByRule :many
SELECT id, rule_id, version, status, priority, scope, condition, action, gray_config, effective_at, expires_at, created_by, created_at FROM rule_versions WHERE rule_id = $1 ORDER BY version DESC
`

func (q *Queries) ListRuleVersionsByRule(ctx context.Context, ruleID int64) ([]RuleVersion, error) {
	rows, err := q.db.Query(ctx, listRuleVersionsByRule, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuleVersion{}
	for rows.Next() {
		var i RuleVersion
		if err := rows.Scan(
			&i.ID,
			&i.RuleID,
			&i.Version,
			&i.Status,
			&i.Priority,
			&i.Scope,
			&i.Condition,
			&i.Action,
			&i.GrayConfig,
			&i.EffectiveAt,
			&i.ExpiresAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many

SELECT id, name, category, status, current_version_id, created_by, created_at, updated_at FROM rules
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListRulesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Phase1: 规则读取查询（草案）
func (q *Queries) ListRules(ctx context.Context, arg ListRulesParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Status,
			&i.CurrentVersionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
