// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_history.sql

package db

import (
	"context"
	"time"
)

const clearSearchHistory = `-- name: ClearSearchHistory :exec
DELETE FROM search_histories
WHERE user_id = $1
`

func (q *Queries) ClearSearchHistory(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, clearSearchHistory, userID)
	return err
}

const createSearchHistory = `-- name: CreateSearchHistory :one
INSERT INTO search_histories (user_id, keyword, type)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, user_id, keyword, type, created_at
`

type CreateSearchHistoryParams struct {
	UserID  int64  `json:"user_id"`
	Keyword string `json:"keyword"`
	Type    string `json:"type"`
}

func (q *Queries) CreateSearchHistory(ctx context.Context, arg CreateSearchHistoryParams) (SearchHistory, error) {
	row := q.db.QueryRow(ctx, createSearchHistory, arg.UserID, arg.Keyword, arg.Type)
	var i SearchHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Keyword,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSearchHistory = `-- name: DeleteSearchHistory :exec
DELETE FROM search_histories
WHERE id = $1 AND user_id = $2
`

type DeleteSearchHistoryParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) DeleteSearchHistory(ctx context.Context, arg DeleteSearchHistoryParams) error {
	_, err := q.db.Exec(ctx, deleteSearchHistory, arg.ID, arg.UserID)
	return err
}

const getPopularKeywords = `-- name: GetPopularKeywords :many
SELECT keyword, type, count
FROM search_popular_keywords
WHERE type = $1
ORDER BY count DESC
LIMIT $2
`

type GetPopularKeywordsParams struct {
	Type  string `json:"type"`
	Limit int32  `json:"limit"`
}

type GetPopularKeywordsRow struct {
	Keyword string `json:"keyword"`
	Type    string `json:"type"`
	Count   int32  `json:"count"`
}

func (q *Queries) GetPopularKeywords(ctx context.Context, arg GetPopularKeywordsParams) ([]GetPopularKeywordsRow, error) {
	rows, err := q.db.Query(ctx, getPopularKeywords, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPopularKeywordsRow{}
	for rows.Next() {
		var i GetPopularKeywordsRow
		if err := rows.Scan(&i.Keyword, &i.Type, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPopularKeyword = `-- name: IncrementPopularKeyword :exec
INSERT INTO search_popular_keywords (keyword, type, count, updated_at)
VALUES ($1, $2, 1, NOW())
ON CONFLICT (keyword, type) DO UPDATE
  SET count = search_popular_keywords.count + 1,
      updated_at = NOW()
`

type IncrementPopularKeywordParams struct {
	Keyword string `json:"keyword"`
	Type    string `json:"type"`
}

func (q *Queries) IncrementPopularKeyword(ctx context.Context, arg IncrementPopularKeywordParams) error {
	_, err := q.db.Exec(ctx, incrementPopularKeyword, arg.Keyword, arg.Type)
	return err
}

const listSearchHistory = `-- name: ListSearchHistory :many
SELECT id, keyword, type, created_at
FROM search_histories
WHERE user_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListSearchHistoryParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
}

type ListSearchHistoryRow struct {
	ID        int64     `json:"id"`
	Keyword   string    `json:"keyword"`
	Type      string    `json:"type"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListSearchHistory(ctx context.Context, arg ListSearchHistoryParams) ([]ListSearchHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSearchHistory, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSearchHistoryRow{}
	for rows.Next() {
		var i ListSearchHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Keyword,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSearchHistory = `-- name: UpsertSearchHistory :one
INSERT INTO search_histories (user_id, keyword, type, created_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id, keyword, type) DO UPDATE
  SET created_at = NOW()
RETURNING id, user_id, keyword, type, created_at
`

type UpsertSearchHistoryParams struct {
	UserID  int64  `json:"user_id"`
	Keyword string `json:"keyword"`
	Type    string `json:"type"`
}

// 插入或更新搜索历史（同一关键词存在时更新时间戳）
func (q *Queries) UpsertSearchHistory(ctx context.Context, arg UpsertSearchHistoryParams) (SearchHistory, error) {
	row := q.db.QueryRow(ctx, upsertSearchHistory, arg.UserID, arg.Keyword, arg.Type)
	var i SearchHistory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Keyword,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}
