// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wanted_merchant.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveWantedMerchantsByRegion = `-- name: CountActiveWantedMerchantsByRegion :one
SELECT COUNT(*)
FROM wanted_merchants
WHERE region_id = $1
  AND status = 'active'
`

func (q *Queries) CountActiveWantedMerchantsByRegion(ctx context.Context, regionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveWantedMerchantsByRegion, regionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrGetActiveWantedMerchant = `-- name: CreateOrGetActiveWantedMerchant :one
INSERT INTO wanted_merchants (
  region_id,
  normalized_name,
  display_name,
  address,
  latitude,
  longitude,
  source,
  created_by_user_id
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (region_id, normalized_name) WHERE status = 'active'
DO UPDATE SET updated_at = wanted_merchants.updated_at
RETURNING id, region_id, normalized_name, display_name, address, latitude, longitude, source, status, want_count, created_by_user_id, matched_merchant_id, last_voted_at, matched_at, created_at, updated_at
`

type CreateOrGetActiveWantedMerchantParams struct {
	RegionID        int64          `json:"region_id"`
	NormalizedName  string         `json:"normalized_name"`
	DisplayName     string         `json:"display_name"`
	Address         pgtype.Text    `json:"address"`
	Latitude        pgtype.Numeric `json:"latitude"`
	Longitude       pgtype.Numeric `json:"longitude"`
	Source          string         `json:"source"`
	CreatedByUserID int64          `json:"created_by_user_id"`
}

func (q *Queries) CreateOrGetActiveWantedMerchant(ctx context.Context, arg CreateOrGetActiveWantedMerchantParams) (WantedMerchant, error) {
	row := q.db.QueryRow(ctx, createOrGetActiveWantedMerchant,
		arg.RegionID,
		arg.NormalizedName,
		arg.DisplayName,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Source,
		arg.CreatedByUserID,
	)
	var i WantedMerchant
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.NormalizedName,
		&i.DisplayName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.Status,
		&i.WantCount,
		&i.CreatedByUserID,
		&i.MatchedMerchantID,
		&i.LastVotedAt,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWantedMerchantVote = `-- name: CreateWantedMerchantVote :one
INSERT INTO wanted_merchant_votes (
  wanted_merchant_id,
  region_id,
  user_id
) VALUES (
  $1, $2, $3
)
ON CONFLICT (region_id, user_id, wanted_merchant_id) DO NOTHING
RETURNING id, wanted_merchant_id, region_id, user_id, created_at
`

type CreateWantedMerchantVoteParams struct {
	WantedMerchantID int64 `json:"wanted_merchant_id"`
	RegionID         int64 `json:"region_id"`
	UserID           int64 `json:"user_id"`
}

func (q *Queries) CreateWantedMerchantVote(ctx context.Context, arg CreateWantedMerchantVoteParams) (WantedMerchantVote, error) {
	row := q.db.QueryRow(ctx, createWantedMerchantVote, arg.WantedMerchantID, arg.RegionID, arg.UserID)
	var i WantedMerchantVote
	err := row.Scan(
		&i.ID,
		&i.WantedMerchantID,
		&i.RegionID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const findActiveTakeoutMerchantByNormalizedName = `-- name: FindActiveTakeoutMerchantByNormalizedName :one
SELECT m.id, m.owner_user_id, m.name, m.description, m.phone, m.address, m.latitude, m.longitude, m.status, m.application_data, m.created_at, m.updated_at, m.version, m.region_id, m.is_open, m.auto_close_at, m.deleted_at, m.pending_owner_bind, m.bind_code, m.bind_code_expires_at, m.group_id, m.brand_id, m.logo_media_asset_id, m.auto_open_by_business_hours, m.storefront_images, m.environment_images
FROM merchants m
LEFT JOIN merchant_profiles mp ON m.id = mp.merchant_id
WHERE m.region_id = $1
  AND m.status = 'active'
  AND m.deleted_at IS NULL
  AND COALESCE(mp.is_takeout_suspended, false) = false
  AND lower(regexp_replace(m.name, '[[:space:]]+', '', 'g')) = $2::text
ORDER BY m.id ASC
LIMIT 1
`

type FindActiveTakeoutMerchantByNormalizedNameParams struct {
	RegionID       int64  `json:"region_id"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) FindActiveTakeoutMerchantByNormalizedName(ctx context.Context, arg FindActiveTakeoutMerchantByNormalizedNameParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, findActiveTakeoutMerchantByNormalizedName, arg.RegionID, arg.NormalizedName)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Name,
		&i.Description,
		&i.Phone,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Status,
		&i.ApplicationData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
		&i.RegionID,
		&i.IsOpen,
		&i.AutoCloseAt,
		&i.DeletedAt,
		&i.PendingOwnerBind,
		&i.BindCode,
		&i.BindCodeExpiresAt,
		&i.GroupID,
		&i.BrandID,
		&i.LogoMediaAssetID,
		&i.AutoOpenByBusinessHours,
		&i.StorefrontImages,
		&i.EnvironmentImages,
	)
	return i, err
}

const findActiveWantedMerchantByNormalizedName = `-- name: FindActiveWantedMerchantByNormalizedName :one
SELECT id, region_id, normalized_name, display_name, address, latitude, longitude, source, status, want_count, created_by_user_id, matched_merchant_id, last_voted_at, matched_at, created_at, updated_at
FROM wanted_merchants
WHERE region_id = $1
  AND normalized_name = $2
  AND status = 'active'
LIMIT 1
`

type FindActiveWantedMerchantByNormalizedNameParams struct {
	RegionID       int64  `json:"region_id"`
	NormalizedName string `json:"normalized_name"`
}

func (q *Queries) FindActiveWantedMerchantByNormalizedName(ctx context.Context, arg FindActiveWantedMerchantByNormalizedNameParams) (WantedMerchant, error) {
	row := q.db.QueryRow(ctx, findActiveWantedMerchantByNormalizedName, arg.RegionID, arg.NormalizedName)
	var i WantedMerchant
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.NormalizedName,
		&i.DisplayName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.Status,
		&i.WantCount,
		&i.CreatedByUserID,
		&i.MatchedMerchantID,
		&i.LastVotedAt,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveWantedMerchantByID = `-- name: GetActiveWantedMerchantByID :one
SELECT id, region_id, normalized_name, display_name, address, latitude, longitude, source, status, want_count, created_by_user_id, matched_merchant_id, last_voted_at, matched_at, created_at, updated_at
FROM wanted_merchants
WHERE id = $1
  AND region_id = $2
  AND status = 'active'
LIMIT 1
`

type GetActiveWantedMerchantByIDParams struct {
	ID       int64 `json:"id"`
	RegionID int64 `json:"region_id"`
}

func (q *Queries) GetActiveWantedMerchantByID(ctx context.Context, arg GetActiveWantedMerchantByIDParams) (WantedMerchant, error) {
	row := q.db.QueryRow(ctx, getActiveWantedMerchantByID, arg.ID, arg.RegionID)
	var i WantedMerchant
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.NormalizedName,
		&i.DisplayName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.Status,
		&i.WantCount,
		&i.CreatedByUserID,
		&i.MatchedMerchantID,
		&i.LastVotedAt,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveWantedMerchantByIDForUpdate = `-- name: GetActiveWantedMerchantByIDForUpdate :one
SELECT id, region_id, normalized_name, display_name, address, latitude, longitude, source, status, want_count, created_by_user_id, matched_merchant_id, last_voted_at, matched_at, created_at, updated_at
FROM wanted_merchants
WHERE id = $1
  AND region_id = $2
  AND status = 'active'
LIMIT 1
FOR UPDATE
`

type GetActiveWantedMerchantByIDForUpdateParams struct {
	ID       int64 `json:"id"`
	RegionID int64 `json:"region_id"`
}

func (q *Queries) GetActiveWantedMerchantByIDForUpdate(ctx context.Context, arg GetActiveWantedMerchantByIDForUpdateParams) (WantedMerchant, error) {
	row := q.db.QueryRow(ctx, getActiveWantedMerchantByIDForUpdate, arg.ID, arg.RegionID)
	var i WantedMerchant
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.NormalizedName,
		&i.DisplayName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.Status,
		&i.WantCount,
		&i.CreatedByUserID,
		&i.MatchedMerchantID,
		&i.LastVotedAt,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWantedMerchantRank = `-- name: GetWantedMerchantRank :one
SELECT (COUNT(*) + 1)::bigint AS rank
FROM wanted_merchants w
JOIN wanted_merchants target
  ON target.id = $2
  AND target.region_id = $1
  AND target.status = 'active'
WHERE w.region_id = target.region_id
  AND w.status = 'active'
  AND (
    w.want_count > target.want_count
    OR (
      w.want_count = target.want_count
      AND COALESCE(w.last_voted_at, 'epoch'::timestamptz) > COALESCE(target.last_voted_at, 'epoch'::timestamptz)
    )
    OR (
      w.want_count = target.want_count
      AND COALESCE(w.last_voted_at, 'epoch'::timestamptz) = COALESCE(target.last_voted_at, 'epoch'::timestamptz)
      AND w.id < target.id
    )
  )
`

type GetWantedMerchantRankParams struct {
	RegionID int64 `json:"region_id"`
	ID       int64 `json:"id"`
}

func (q *Queries) GetWantedMerchantRank(ctx context.Context, arg GetWantedMerchantRankParams) (int64, error) {
	row := q.db.QueryRow(ctx, getWantedMerchantRank, arg.RegionID, arg.ID)
	var rank int64
	err := row.Scan(&rank)
	return rank, err
}

const incrementWantedMerchantWantCount = `-- name: IncrementWantedMerchantWantCount :one
UPDATE wanted_merchants
SET
  want_count = want_count + 1,
  last_voted_at = now(),
  updated_at = now()
WHERE id = $1
  AND region_id = $2
  AND status = 'active'
RETURNING id, region_id, normalized_name, display_name, address, latitude, longitude, source, status, want_count, created_by_user_id, matched_merchant_id, last_voted_at, matched_at, created_at, updated_at
`

type IncrementWantedMerchantWantCountParams struct {
	ID       int64 `json:"id"`
	RegionID int64 `json:"region_id"`
}

func (q *Queries) IncrementWantedMerchantWantCount(ctx context.Context, arg IncrementWantedMerchantWantCountParams) (WantedMerchant, error) {
	row := q.db.QueryRow(ctx, incrementWantedMerchantWantCount, arg.ID, arg.RegionID)
	var i WantedMerchant
	err := row.Scan(
		&i.ID,
		&i.RegionID,
		&i.NormalizedName,
		&i.DisplayName,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.Status,
		&i.WantCount,
		&i.CreatedByUserID,
		&i.MatchedMerchantID,
		&i.LastVotedAt,
		&i.MatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWantedMerchantLeaderboard = `-- name: ListWantedMerchantLeaderboard :many
SELECT
  w.id,
  w.region_id,
  w.normalized_name,
  w.display_name,
  w.address,
  w.latitude,
  w.longitude,
  w.source,
  w.status,
  w.want_count,
  w.last_voted_at,
  w.created_at,
  w.updated_at,
  (ROW_NUMBER() OVER (
    ORDER BY w.want_count DESC, w.last_voted_at DESC NULLS LAST, w.id ASC
  ))::bigint AS rank,
  EXISTS (
    SELECT 1
    FROM wanted_merchant_votes v
    WHERE v.region_id = w.region_id
      AND v.wanted_merchant_id = w.id
      AND v.user_id = $2
  ) AS has_voted
FROM wanted_merchants w
WHERE w.region_id = $1
  AND w.status = 'active'
ORDER BY w.want_count DESC, w.last_voted_at DESC NULLS LAST, w.id ASC
LIMIT $3 OFFSET $4
`

type ListWantedMerchantLeaderboardParams struct {
	RegionID int64 `json:"region_id"`
	UserID   int64 `json:"user_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

type ListWantedMerchantLeaderboardRow struct {
	ID             int64              `json:"id"`
	RegionID       int64              `json:"region_id"`
	NormalizedName string             `json:"normalized_name"`
	DisplayName    string             `json:"display_name"`
	Address        pgtype.Text        `json:"address"`
	Latitude       pgtype.Numeric     `json:"latitude"`
	Longitude      pgtype.Numeric     `json:"longitude"`
	Source         string             `json:"source"`
	Status         string             `json:"status"`
	WantCount      int32              `json:"want_count"`
	LastVotedAt    pgtype.Timestamptz `json:"last_voted_at"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	Rank           int64              `json:"rank"`
	HasVoted       bool               `json:"has_voted"`
}

func (q *Queries) ListWantedMerchantLeaderboard(ctx context.Context, arg ListWantedMerchantLeaderboardParams) ([]ListWantedMerchantLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, listWantedMerchantLeaderboard,
		arg.RegionID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWantedMerchantLeaderboardRow{}
	for rows.Next() {
		var i ListWantedMerchantLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.RegionID,
			&i.NormalizedName,
			&i.DisplayName,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Source,
			&i.Status,
			&i.WantCount,
			&i.LastVotedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
			&i.HasVoted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markActiveWantedMerchantMatchedByMerchant = `-- name: MarkActiveWantedMerchantMatchedByMerchant :exec
UPDATE wanted_merchants
SET
  status = 'matched',
  matched_merchant_id = $3,
  matched_at = now(),
  updated_at = now()
WHERE region_id = $1
  AND normalized_name = $2
  AND status = 'active'
`

type MarkActiveWantedMerchantMatchedByMerchantParams struct {
	RegionID          int64       `json:"region_id"`
	NormalizedName    string      `json:"normalized_name"`
	MatchedMerchantID pgtype.Int8 `json:"matched_merchant_id"`
}

func (q *Queries) MarkActiveWantedMerchantMatchedByMerchant(ctx context.Context, arg MarkActiveWantedMerchantMatchedByMerchantParams) error {
	_, err := q.db.Exec(ctx, markActiveWantedMerchantMatchedByMerchant, arg.RegionID, arg.NormalizedName, arg.MatchedMerchantID)
	return err
}
