DB_URL=postgresql:///locallife_test?host=/var/run/postgresql&sslmode=disable

network:
	docker network create bank-network

postgres:
	docker run --name postgres --network bank-network -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=secret -d postgres:14-alpine

mysql:
	docker run --name mysql8 -p 3306:3306  -e MYSQL_ROOT_PASSWORD=secret -d mysql:8

createdb:
	createdb locallife_test

dropdb:
	dropdb locallife_test

migrateup:
	migrate -path db/migration -database "$(DB_URL)" -verbose up

migrateup1:
	migrate -path db/migration -database "$(DB_URL)" -verbose up 1

migratedown:
	migrate -path db/migration -database "$(DB_URL)" -verbose down

migratedown1:
	migrate -path db/migration -database "$(DB_URL)" -verbose down 1

new_migration:
	migrate create -ext sql -dir db/migration -seq $(name)

db_docs:
	dbdocs build doc/db.dbml

db_schema:
	dbml2sql --postgres -o doc/schema.sql doc/db.dbml

sqlc:
	sqlc generate
	mockgen -package mockdb -destination db/mock/store.go github.com/merrydance/locallife/db/sqlc Store
	mockgen -package mockwk -destination worker/mock/distributor.go github.com/merrydance/locallife/worker TaskDistributor
	mockgen -package mockwechat -destination wechat/mock/wechat_client.go github.com/merrydance/locallife/wechat WechatClient
	mockgen -package mockwechat -destination wechat/mock/payment_client.go github.com/merrydance/locallife/wechat PaymentClientInterface,EcommerceClientInterface

test:
	go test -v -cover -short ./...

# Sync regions from Tencent LBS (Hebei + Guangzhou, up to level 3)
sync_regions_test:
	go run ./cmd/sync_regions_tencent -config . -db "$(DB_URL)"

swagger:
	swag init -g main.go -o docs --parseDependency --parseInternal

server:
	go run main.go

mock:
	mockgen -package mockdb -destination db/mock/store.go github.com/merrydance/locallife/db/sqlc Store
	mockgen -package mockwk -destination worker/mock/distributor.go github.com/merrydance/locallife/worker TaskDistributor
	mockgen -package mockwechat -destination wechat/mock/wechat_client.go github.com/merrydance/locallife/wechat WechatClient
	mockgen -package mockwechat -destination wechat/mock/payment_client.go github.com/merrydance/locallife/wechat PaymentClientInterface,EcommerceClientInterface

proto:
	rm -f pb/*.go
	rm -f doc/swagger/*.swagger.json
	protoc --proto_path=proto --go_out=pb --go_opt=paths=source_relative \
	--go-grpc_out=pb --go-grpc_opt=paths=source_relative \
	--grpc-gateway_out=pb --grpc-gateway_opt=paths=source_relative \
	--openapiv2_out=doc/swagger --openapiv2_opt=allow_merge=true,merge_file_name=locallife \
	proto/*.proto
	statik -src=./doc/swagger -dest=./doc

evans:
	evans --host localhost --port 9090 -r repl

redis:
	docker run --name redis -p 6379:6379 -d redis:7-alpine

.PHONY: network postgres createdb dropdb migrateup migratedown migrateup1 migratedown1 new_migration db_docs db_schema sqlc swagger test server mock proto evans redis sync_regions_test
