// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/merrydance/locallife/wechat (interfaces: PaymentClientInterface,EcommerceClientInterface)
//
// Generated by this command:
//
//	mockgen -package mockwechat -destination wechat/mock/payment_client.go github.com/merrydance/locallife/wechat PaymentClientInterface,EcommerceClientInterface
//

// Package mockwechat is a generated GoMock package.
package mockwechat

import (
	context "context"
	reflect "reflect"

	wechat "github.com/merrydance/locallife/wechat"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentClientInterface is a mock of PaymentClientInterface interface.
type MockPaymentClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentClientInterfaceMockRecorder
	isgomock struct{}
}

// MockPaymentClientInterfaceMockRecorder is the mock recorder for MockPaymentClientInterface.
type MockPaymentClientInterfaceMockRecorder struct {
	mock *MockPaymentClientInterface
}

// NewMockPaymentClientInterface creates a new mock instance.
func NewMockPaymentClientInterface(ctrl *gomock.Controller) *MockPaymentClientInterface {
	mock := &MockPaymentClientInterface{ctrl: ctrl}
	mock.recorder = &MockPaymentClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentClientInterface) EXPECT() *MockPaymentClientInterfaceMockRecorder {
	return m.recorder
}

// CloseOrder mocks base method.
func (m *MockPaymentClientInterface) CloseOrder(ctx context.Context, outTradeNo string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseOrder", ctx, outTradeNo)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseOrder indicates an expected call of CloseOrder.
func (mr *MockPaymentClientInterfaceMockRecorder) CloseOrder(ctx, outTradeNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseOrder", reflect.TypeOf((*MockPaymentClientInterface)(nil).CloseOrder), ctx, outTradeNo)
}

// CreateJSAPIOrder mocks base method.
func (m *MockPaymentClientInterface) CreateJSAPIOrder(ctx context.Context, req *wechat.JSAPIOrderRequest) (*wechat.JSAPIOrderResponse, *wechat.JSAPIPayParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJSAPIOrder", ctx, req)
	ret0, _ := ret[0].(*wechat.JSAPIOrderResponse)
	ret1, _ := ret[1].(*wechat.JSAPIPayParams)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateJSAPIOrder indicates an expected call of CreateJSAPIOrder.
func (mr *MockPaymentClientInterfaceMockRecorder) CreateJSAPIOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJSAPIOrder", reflect.TypeOf((*MockPaymentClientInterface)(nil).CreateJSAPIOrder), ctx, req)
}

// CreateRefund mocks base method.
func (m *MockPaymentClientInterface) CreateRefund(ctx context.Context, req *wechat.RefundRequest) (*wechat.RefundResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRefund", ctx, req)
	ret0, _ := ret[0].(*wechat.RefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRefund indicates an expected call of CreateRefund.
func (mr *MockPaymentClientInterfaceMockRecorder) CreateRefund(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRefund", reflect.TypeOf((*MockPaymentClientInterface)(nil).CreateRefund), ctx, req)
}

// CreateTransfer mocks base method.
func (m *MockPaymentClientInterface) CreateTransfer(ctx context.Context, req *wechat.TransferRequest) (*wechat.TransferResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", ctx, req)
	ret0, _ := ret[0].(*wechat.TransferResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockPaymentClientInterfaceMockRecorder) CreateTransfer(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockPaymentClientInterface)(nil).CreateTransfer), ctx, req)
}

// DecryptNotificationRaw mocks base method.
func (m *MockPaymentClientInterface) DecryptNotificationRaw(notification *wechat.PaymentNotification) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptNotificationRaw", notification)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptNotificationRaw indicates an expected call of DecryptNotificationRaw.
func (mr *MockPaymentClientInterfaceMockRecorder) DecryptNotificationRaw(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptNotificationRaw", reflect.TypeOf((*MockPaymentClientInterface)(nil).DecryptNotificationRaw), notification)
}

// DecryptPaymentNotification mocks base method.
func (m *MockPaymentClientInterface) DecryptPaymentNotification(notification *wechat.PaymentNotification) (*wechat.PaymentNotificationResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptPaymentNotification", notification)
	ret0, _ := ret[0].(*wechat.PaymentNotificationResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptPaymentNotification indicates an expected call of DecryptPaymentNotification.
func (mr *MockPaymentClientInterfaceMockRecorder) DecryptPaymentNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptPaymentNotification", reflect.TypeOf((*MockPaymentClientInterface)(nil).DecryptPaymentNotification), notification)
}

// DecryptRefundNotification mocks base method.
func (m *MockPaymentClientInterface) DecryptRefundNotification(notification *wechat.PaymentNotification) (*wechat.RefundNotificationResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptRefundNotification", notification)
	ret0, _ := ret[0].(*wechat.RefundNotificationResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptRefundNotification indicates an expected call of DecryptRefundNotification.
func (mr *MockPaymentClientInterfaceMockRecorder) DecryptRefundNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptRefundNotification", reflect.TypeOf((*MockPaymentClientInterface)(nil).DecryptRefundNotification), notification)
}

// QueryOrderByOutTradeNo mocks base method.
func (m *MockPaymentClientInterface) QueryOrderByOutTradeNo(ctx context.Context, outTradeNo string) (*wechat.OrderQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryOrderByOutTradeNo", ctx, outTradeNo)
	ret0, _ := ret[0].(*wechat.OrderQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryOrderByOutTradeNo indicates an expected call of QueryOrderByOutTradeNo.
func (mr *MockPaymentClientInterfaceMockRecorder) QueryOrderByOutTradeNo(ctx, outTradeNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryOrderByOutTradeNo", reflect.TypeOf((*MockPaymentClientInterface)(nil).QueryOrderByOutTradeNo), ctx, outTradeNo)
}

// QueryRefund mocks base method.
func (m *MockPaymentClientInterface) QueryRefund(ctx context.Context, outRefundNo string) (*wechat.RefundResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryRefund", ctx, outRefundNo)
	ret0, _ := ret[0].(*wechat.RefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryRefund indicates an expected call of QueryRefund.
func (mr *MockPaymentClientInterfaceMockRecorder) QueryRefund(ctx, outRefundNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRefund", reflect.TypeOf((*MockPaymentClientInterface)(nil).QueryRefund), ctx, outRefundNo)
}

// VerifyNotificationSignature mocks base method.
func (m *MockPaymentClientInterface) VerifyNotificationSignature(signature, timestamp, nonce, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyNotificationSignature", signature, timestamp, nonce, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyNotificationSignature indicates an expected call of VerifyNotificationSignature.
func (mr *MockPaymentClientInterfaceMockRecorder) VerifyNotificationSignature(signature, timestamp, nonce, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyNotificationSignature", reflect.TypeOf((*MockPaymentClientInterface)(nil).VerifyNotificationSignature), signature, timestamp, nonce, body)
}

// MockEcommerceClientInterface is a mock of EcommerceClientInterface interface.
type MockEcommerceClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEcommerceClientInterfaceMockRecorder
	isgomock struct{}
}

// MockEcommerceClientInterfaceMockRecorder is the mock recorder for MockEcommerceClientInterface.
type MockEcommerceClientInterfaceMockRecorder struct {
	mock *MockEcommerceClientInterface
}

// NewMockEcommerceClientInterface creates a new mock instance.
func NewMockEcommerceClientInterface(ctrl *gomock.Controller) *MockEcommerceClientInterface {
	mock := &MockEcommerceClientInterface{ctrl: ctrl}
	mock.recorder = &MockEcommerceClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcommerceClientInterface) EXPECT() *MockEcommerceClientInterfaceMockRecorder {
	return m.recorder
}

// AddProfitSharingReceiver mocks base method.
func (m *MockEcommerceClientInterface) AddProfitSharingReceiver(ctx context.Context, req *wechat.AddReceiverRequest) (*wechat.AddReceiverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddProfitSharingReceiver", ctx, req)
	ret0, _ := ret[0].(*wechat.AddReceiverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddProfitSharingReceiver indicates an expected call of AddProfitSharingReceiver.
func (mr *MockEcommerceClientInterfaceMockRecorder) AddProfitSharingReceiver(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddProfitSharingReceiver", reflect.TypeOf((*MockEcommerceClientInterface)(nil).AddProfitSharingReceiver), ctx, req)
}

// CloseCombineOrder mocks base method.
func (m *MockEcommerceClientInterface) CloseCombineOrder(ctx context.Context, combineOutTradeNo string, subOrders []wechat.SubOrderClose) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseCombineOrder", ctx, combineOutTradeNo, subOrders)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseCombineOrder indicates an expected call of CloseCombineOrder.
func (mr *MockEcommerceClientInterfaceMockRecorder) CloseCombineOrder(ctx, combineOutTradeNo, subOrders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseCombineOrder", reflect.TypeOf((*MockEcommerceClientInterface)(nil).CloseCombineOrder), ctx, combineOutTradeNo, subOrders)
}

// CreateCombineOrder mocks base method.
func (m *MockEcommerceClientInterface) CreateCombineOrder(ctx context.Context, req *wechat.CombineOrderRequest) (*wechat.CombineOrderResponse, *wechat.JSAPIPayParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCombineOrder", ctx, req)
	ret0, _ := ret[0].(*wechat.CombineOrderResponse)
	ret1, _ := ret[1].(*wechat.JSAPIPayParams)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateCombineOrder indicates an expected call of CreateCombineOrder.
func (mr *MockEcommerceClientInterfaceMockRecorder) CreateCombineOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCombineOrder", reflect.TypeOf((*MockEcommerceClientInterface)(nil).CreateCombineOrder), ctx, req)
}

// CreateEcommerceApplyment mocks base method.
func (m *MockEcommerceClientInterface) CreateEcommerceApplyment(ctx context.Context, req *wechat.EcommerceApplymentRequest) (*wechat.EcommerceApplymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEcommerceApplyment", ctx, req)
	ret0, _ := ret[0].(*wechat.EcommerceApplymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEcommerceApplyment indicates an expected call of CreateEcommerceApplyment.
func (mr *MockEcommerceClientInterfaceMockRecorder) CreateEcommerceApplyment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEcommerceApplyment", reflect.TypeOf((*MockEcommerceClientInterface)(nil).CreateEcommerceApplyment), ctx, req)
}

// CreateEcommerceRefund mocks base method.
func (m *MockEcommerceClientInterface) CreateEcommerceRefund(ctx context.Context, req *wechat.EcommerceRefundRequest) (*wechat.EcommerceRefundResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEcommerceRefund", ctx, req)
	ret0, _ := ret[0].(*wechat.EcommerceRefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEcommerceRefund indicates an expected call of CreateEcommerceRefund.
func (mr *MockEcommerceClientInterfaceMockRecorder) CreateEcommerceRefund(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEcommerceRefund", reflect.TypeOf((*MockEcommerceClientInterface)(nil).CreateEcommerceRefund), ctx, req)
}

// CreateProfitSharing mocks base method.
func (m *MockEcommerceClientInterface) CreateProfitSharing(ctx context.Context, req *wechat.ProfitSharingRequest) (*wechat.ProfitSharingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfitSharing", ctx, req)
	ret0, _ := ret[0].(*wechat.ProfitSharingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfitSharing indicates an expected call of CreateProfitSharing.
func (mr *MockEcommerceClientInterfaceMockRecorder) CreateProfitSharing(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfitSharing", reflect.TypeOf((*MockEcommerceClientInterface)(nil).CreateProfitSharing), ctx, req)
}

// CreateProfitSharingReturn mocks base method.
func (m *MockEcommerceClientInterface) CreateProfitSharingReturn(ctx context.Context, req *wechat.ProfitSharingReturnRequest) (*wechat.ProfitSharingReturnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfitSharingReturn", ctx, req)
	ret0, _ := ret[0].(*wechat.ProfitSharingReturnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProfitSharingReturn indicates an expected call of CreateProfitSharingReturn.
func (mr *MockEcommerceClientInterfaceMockRecorder) CreateProfitSharingReturn(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfitSharingReturn", reflect.TypeOf((*MockEcommerceClientInterface)(nil).CreateProfitSharingReturn), ctx, req)
}

// DecryptCombinePaymentNotification mocks base method.
func (m *MockEcommerceClientInterface) DecryptCombinePaymentNotification(notification *wechat.PaymentNotification) (*wechat.CombinePaymentNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptCombinePaymentNotification", notification)
	ret0, _ := ret[0].(*wechat.CombinePaymentNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptCombinePaymentNotification indicates an expected call of DecryptCombinePaymentNotification.
func (mr *MockEcommerceClientInterfaceMockRecorder) DecryptCombinePaymentNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptCombinePaymentNotification", reflect.TypeOf((*MockEcommerceClientInterface)(nil).DecryptCombinePaymentNotification), notification)
}

// DecryptEcommerceRefundNotification mocks base method.
func (m *MockEcommerceClientInterface) DecryptEcommerceRefundNotification(notification *wechat.PaymentNotification) (*wechat.EcommerceRefundNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptEcommerceRefundNotification", notification)
	ret0, _ := ret[0].(*wechat.EcommerceRefundNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptEcommerceRefundNotification indicates an expected call of DecryptEcommerceRefundNotification.
func (mr *MockEcommerceClientInterfaceMockRecorder) DecryptEcommerceRefundNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptEcommerceRefundNotification", reflect.TypeOf((*MockEcommerceClientInterface)(nil).DecryptEcommerceRefundNotification), notification)
}

// DecryptProfitSharingNotification mocks base method.
func (m *MockEcommerceClientInterface) DecryptProfitSharingNotification(notification *wechat.PaymentNotification) (*wechat.ProfitSharingNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecryptProfitSharingNotification", notification)
	ret0, _ := ret[0].(*wechat.ProfitSharingNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecryptProfitSharingNotification indicates an expected call of DecryptProfitSharingNotification.
func (mr *MockEcommerceClientInterfaceMockRecorder) DecryptProfitSharingNotification(notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecryptProfitSharingNotification", reflect.TypeOf((*MockEcommerceClientInterface)(nil).DecryptProfitSharingNotification), notification)
}

// DeleteProfitSharingReceiver mocks base method.
func (m *MockEcommerceClientInterface) DeleteProfitSharingReceiver(ctx context.Context, req *wechat.DeleteReceiverRequest) (*wechat.DeleteReceiverResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProfitSharingReceiver", ctx, req)
	ret0, _ := ret[0].(*wechat.DeleteReceiverResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProfitSharingReceiver indicates an expected call of DeleteProfitSharingReceiver.
func (mr *MockEcommerceClientInterfaceMockRecorder) DeleteProfitSharingReceiver(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProfitSharingReceiver", reflect.TypeOf((*MockEcommerceClientInterface)(nil).DeleteProfitSharingReceiver), ctx, req)
}

// EncryptSensitiveData mocks base method.
func (m *MockEcommerceClientInterface) EncryptSensitiveData(plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EncryptSensitiveData", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EncryptSensitiveData indicates an expected call of EncryptSensitiveData.
func (mr *MockEcommerceClientInterfaceMockRecorder) EncryptSensitiveData(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EncryptSensitiveData", reflect.TypeOf((*MockEcommerceClientInterface)(nil).EncryptSensitiveData), plaintext)
}

// FinishProfitSharing mocks base method.
func (m *MockEcommerceClientInterface) FinishProfitSharing(ctx context.Context, subMchID, transactionID, outOrderNo, description string) (*wechat.ProfitSharingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FinishProfitSharing", ctx, subMchID, transactionID, outOrderNo, description)
	ret0, _ := ret[0].(*wechat.ProfitSharingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FinishProfitSharing indicates an expected call of FinishProfitSharing.
func (mr *MockEcommerceClientInterfaceMockRecorder) FinishProfitSharing(ctx, subMchID, transactionID, outOrderNo, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FinishProfitSharing", reflect.TypeOf((*MockEcommerceClientInterface)(nil).FinishProfitSharing), ctx, subMchID, transactionID, outOrderNo, description)
}

// GetPlatformCertificateSerial mocks base method.
func (m *MockEcommerceClientInterface) GetPlatformCertificateSerial() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlatformCertificateSerial")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPlatformCertificateSerial indicates an expected call of GetPlatformCertificateSerial.
func (mr *MockEcommerceClientInterfaceMockRecorder) GetPlatformCertificateSerial() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlatformCertificateSerial", reflect.TypeOf((*MockEcommerceClientInterface)(nil).GetPlatformCertificateSerial))
}

// GetSpAppID mocks base method.
func (m *MockEcommerceClientInterface) GetSpAppID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpAppID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSpAppID indicates an expected call of GetSpAppID.
func (mr *MockEcommerceClientInterfaceMockRecorder) GetSpAppID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpAppID", reflect.TypeOf((*MockEcommerceClientInterface)(nil).GetSpAppID))
}

// GetSpMchID mocks base method.
func (m *MockEcommerceClientInterface) GetSpMchID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSpMchID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSpMchID indicates an expected call of GetSpMchID.
func (mr *MockEcommerceClientInterfaceMockRecorder) GetSpMchID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSpMchID", reflect.TypeOf((*MockEcommerceClientInterface)(nil).GetSpMchID))
}

// QueryCombineOrder mocks base method.
func (m *MockEcommerceClientInterface) QueryCombineOrder(ctx context.Context, combineOutTradeNo string) (*wechat.CombineQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCombineOrder", ctx, combineOutTradeNo)
	ret0, _ := ret[0].(*wechat.CombineQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryCombineOrder indicates an expected call of QueryCombineOrder.
func (mr *MockEcommerceClientInterfaceMockRecorder) QueryCombineOrder(ctx, combineOutTradeNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCombineOrder", reflect.TypeOf((*MockEcommerceClientInterface)(nil).QueryCombineOrder), ctx, combineOutTradeNo)
}

// QueryEcommerceApplymentByID mocks base method.
func (m *MockEcommerceClientInterface) QueryEcommerceApplymentByID(ctx context.Context, applymentID int64) (*wechat.EcommerceApplymentQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryEcommerceApplymentByID", ctx, applymentID)
	ret0, _ := ret[0].(*wechat.EcommerceApplymentQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryEcommerceApplymentByID indicates an expected call of QueryEcommerceApplymentByID.
func (mr *MockEcommerceClientInterfaceMockRecorder) QueryEcommerceApplymentByID(ctx, applymentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryEcommerceApplymentByID", reflect.TypeOf((*MockEcommerceClientInterface)(nil).QueryEcommerceApplymentByID), ctx, applymentID)
}

// QueryEcommerceApplymentByOutRequestNo mocks base method.
func (m *MockEcommerceClientInterface) QueryEcommerceApplymentByOutRequestNo(ctx context.Context, outRequestNo string) (*wechat.EcommerceApplymentQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryEcommerceApplymentByOutRequestNo", ctx, outRequestNo)
	ret0, _ := ret[0].(*wechat.EcommerceApplymentQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryEcommerceApplymentByOutRequestNo indicates an expected call of QueryEcommerceApplymentByOutRequestNo.
func (mr *MockEcommerceClientInterfaceMockRecorder) QueryEcommerceApplymentByOutRequestNo(ctx, outRequestNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryEcommerceApplymentByOutRequestNo", reflect.TypeOf((*MockEcommerceClientInterface)(nil).QueryEcommerceApplymentByOutRequestNo), ctx, outRequestNo)
}

// QueryEcommerceRefund mocks base method.
func (m *MockEcommerceClientInterface) QueryEcommerceRefund(ctx context.Context, subMchID, outRefundNo string) (*wechat.EcommerceRefundResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryEcommerceRefund", ctx, subMchID, outRefundNo)
	ret0, _ := ret[0].(*wechat.EcommerceRefundResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryEcommerceRefund indicates an expected call of QueryEcommerceRefund.
func (mr *MockEcommerceClientInterfaceMockRecorder) QueryEcommerceRefund(ctx, subMchID, outRefundNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryEcommerceRefund", reflect.TypeOf((*MockEcommerceClientInterface)(nil).QueryEcommerceRefund), ctx, subMchID, outRefundNo)
}

// QueryProfitSharing mocks base method.
func (m *MockEcommerceClientInterface) QueryProfitSharing(ctx context.Context, subMchID, transactionID, outOrderNo string) (*wechat.ProfitSharingQueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryProfitSharing", ctx, subMchID, transactionID, outOrderNo)
	ret0, _ := ret[0].(*wechat.ProfitSharingQueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryProfitSharing indicates an expected call of QueryProfitSharing.
func (mr *MockEcommerceClientInterfaceMockRecorder) QueryProfitSharing(ctx, subMchID, transactionID, outOrderNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryProfitSharing", reflect.TypeOf((*MockEcommerceClientInterface)(nil).QueryProfitSharing), ctx, subMchID, transactionID, outOrderNo)
}

// QueryProfitSharingReturn mocks base method.
func (m *MockEcommerceClientInterface) QueryProfitSharingReturn(ctx context.Context, subMchID, outReturnNo, outOrderNo string) (*wechat.ProfitSharingReturnResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryProfitSharingReturn", ctx, subMchID, outReturnNo, outOrderNo)
	ret0, _ := ret[0].(*wechat.ProfitSharingReturnResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryProfitSharingReturn indicates an expected call of QueryProfitSharingReturn.
func (mr *MockEcommerceClientInterfaceMockRecorder) QueryProfitSharingReturn(ctx, subMchID, outReturnNo, outOrderNo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryProfitSharingReturn", reflect.TypeOf((*MockEcommerceClientInterface)(nil).QueryProfitSharingReturn), ctx, subMchID, outReturnNo, outOrderNo)
}

// UploadImage mocks base method.
func (m *MockEcommerceClientInterface) UploadImage(ctx context.Context, filename string, fileData []byte) (*wechat.ImageUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, filename, fileData)
	ret0, _ := ret[0].(*wechat.ImageUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockEcommerceClientInterfaceMockRecorder) UploadImage(ctx, filename, fileData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockEcommerceClientInterface)(nil).UploadImage), ctx, filename, fileData)
}

// VerifyNotificationSignature mocks base method.
func (m *MockEcommerceClientInterface) VerifyNotificationSignature(signature, timestamp, nonce, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyNotificationSignature", signature, timestamp, nonce, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// VerifyNotificationSignature indicates an expected call of VerifyNotificationSignature.
func (mr *MockEcommerceClientInterfaceMockRecorder) VerifyNotificationSignature(signature, timestamp, nonce, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyNotificationSignature", reflect.TypeOf((*MockEcommerceClientInterface)(nil).VerifyNotificationSignature), signature, timestamp, nonce, body)
}
