// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/merrydance/locallife/wechat (interfaces: WechatClient)
//
// Generated by this command:
//
//	mockgen -package mockwechat -destination wechat/mock/wechat_client.go github.com/merrydance/locallife/wechat WechatClient
//

// Package mockwechat is a generated GoMock package.
package mockwechat

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	wechat "github.com/merrydance/locallife/wechat"
	gomock "go.uber.org/mock/gomock"
)

// MockWechatClient is a mock of WechatClient interface.
type MockWechatClient struct {
	ctrl     *gomock.Controller
	recorder *MockWechatClientMockRecorder
	isgomock struct{}
}

// MockWechatClientMockRecorder is the mock recorder for MockWechatClient.
type MockWechatClientMockRecorder struct {
	mock *MockWechatClient
}

// NewMockWechatClient creates a new mock instance.
func NewMockWechatClient(ctrl *gomock.Controller) *MockWechatClient {
	mock := &MockWechatClient{ctrl: ctrl}
	mock.recorder = &MockWechatClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWechatClient) EXPECT() *MockWechatClientMockRecorder {
	return m.recorder
}

// Code2Session mocks base method.
func (m *MockWechatClient) Code2Session(ctx context.Context, code string) (*wechat.Code2SessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Code2Session", ctx, code)
	ret0, _ := ret[0].(*wechat.Code2SessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Code2Session indicates an expected call of Code2Session.
func (mr *MockWechatClientMockRecorder) Code2Session(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Code2Session", reflect.TypeOf((*MockWechatClient)(nil).Code2Session), ctx, code)
}

// GetWXACodeUnlimited mocks base method.
func (m *MockWechatClient) GetWXACodeUnlimited(ctx context.Context, req *wechat.WXACodeRequest) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWXACodeUnlimited", ctx, req)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWXACodeUnlimited indicates an expected call of GetWXACodeUnlimited.
func (mr *MockWechatClientMockRecorder) GetWXACodeUnlimited(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWXACodeUnlimited", reflect.TypeOf((*MockWechatClient)(nil).GetWXACodeUnlimited), ctx, req)
}

// ImgSecCheck mocks base method.
func (m *MockWechatClient) ImgSecCheck(ctx context.Context, imgFile multipart.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ImgSecCheck", ctx, imgFile)
	ret0, _ := ret[0].(error)
	return ret0
}

// ImgSecCheck indicates an expected call of ImgSecCheck.
func (mr *MockWechatClientMockRecorder) ImgSecCheck(ctx, imgFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ImgSecCheck", reflect.TypeOf((*MockWechatClient)(nil).ImgSecCheck), ctx, imgFile)
}

// MsgSecCheck mocks base method.
func (m *MockWechatClient) MsgSecCheck(ctx context.Context, openid string, scene int, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MsgSecCheck", ctx, openid, scene, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// MsgSecCheck indicates an expected call of MsgSecCheck.
func (mr *MockWechatClientMockRecorder) MsgSecCheck(ctx, openid, scene, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MsgSecCheck", reflect.TypeOf((*MockWechatClient)(nil).MsgSecCheck), ctx, openid, scene, content)
}

// OCRBusinessLicense mocks base method.
func (m *MockWechatClient) OCRBusinessLicense(ctx context.Context, imgFile multipart.File) (*wechat.BusinessLicenseOCRResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OCRBusinessLicense", ctx, imgFile)
	ret0, _ := ret[0].(*wechat.BusinessLicenseOCRResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OCRBusinessLicense indicates an expected call of OCRBusinessLicense.
func (mr *MockWechatClientMockRecorder) OCRBusinessLicense(ctx, imgFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OCRBusinessLicense", reflect.TypeOf((*MockWechatClient)(nil).OCRBusinessLicense), ctx, imgFile)
}

// OCRIDCard mocks base method.
func (m *MockWechatClient) OCRIDCard(ctx context.Context, imgFile multipart.File, cardSide string) (*wechat.IDCardOCRResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OCRIDCard", ctx, imgFile, cardSide)
	ret0, _ := ret[0].(*wechat.IDCardOCRResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OCRIDCard indicates an expected call of OCRIDCard.
func (mr *MockWechatClientMockRecorder) OCRIDCard(ctx, imgFile, cardSide any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OCRIDCard", reflect.TypeOf((*MockWechatClient)(nil).OCRIDCard), ctx, imgFile, cardSide)
}

// OCRPrintedText mocks base method.
func (m *MockWechatClient) OCRPrintedText(ctx context.Context, imgFile multipart.File) (*wechat.PrintedTextOCRResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OCRPrintedText", ctx, imgFile)
	ret0, _ := ret[0].(*wechat.PrintedTextOCRResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OCRPrintedText indicates an expected call of OCRPrintedText.
func (mr *MockWechatClientMockRecorder) OCRPrintedText(ctx, imgFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OCRPrintedText", reflect.TypeOf((*MockWechatClient)(nil).OCRPrintedText), ctx, imgFile)
}
